### ISSUE TITLE
Please add me - Lianyungang

### ISSUE THREAD

**Issue by jsonBeginner** [githubschool/open-enrollment-classes-introduction-to-github#10004]
## Adding Lianyungang to the map

Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude: 119.221611
- Latitude: 34.596653

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
