### ISSUE TITLE
please add me- Hyderabad,India

### ISSUE THREAD

**Issue by kesavakadiyala** [githubschool/open-enrollment-classes-introduction-to-github#10043]
Hello! :wave: Please add me as a collaborator to this repo. 
##Adding Hyderab to map

-Longitude: 17.3850
-Latitude: 78.4867

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
