### ISSUE TITLE
Adding Portland, OR to the map

### ISSUE THREAD

**Issue by ClevelandHighSchool** [githubschool/open-enrollment-classes-introduction-to-github#1008]
## Adding Portland, OR to the map

Hi everyone! This issue is to track the addition of Portland, OR to the map, which can be found at:

- Longitude:  -122.676482
- Latitude:  45.523062

**Comment by SleepyPandas** [comment]
just following instructions. dont mind me

**Comment by leighannand** [comment]
same ^

**Comment by WyldPhyr** [comment]
See above ^. About to add my pin.

**Comment by leighannand** [comment]
dudes why isn't letting me add my pin

**Comment by StateofGrey** [comment]
I will be adding my name to this city.

**Comment by SamLn** [comment]
I will be adding my name to this city, too.

**Comment by Wonthanh** [comment]
Commenting on the issue to let others know that I will be adding my name to the same city!
