### ISSUE TITLE
please add me as copycat123

### ISSUE THREAD

**Issue by copycat123** [githubschool/open-enrollment-classes-introduction-to-github#10091]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by copycat123** [comment]
Your Latitude: 30.7343
Your Longitude: 76.7933

add please, my location

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
