### ISSUE TITLE
Please add me - Hillsboro, OR

### ISSUE THREAD

**Issue by BryceTheOldGoat** [githubschool/open-enrollment-classes-introduction-to-github#10109]
## Adding Hillsboro to the map

Hi everyone.  This issue is to track the addition of Hillsboro to the map, which can be found at 45°32'39" N 122°53'22" W

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
