### ISSUE TITLE
Bona tarda

### ISSUE THREAD

**Issue by josugonzalez** [githubschool/open-enrollment-classes-introduction-to-github#10123]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by mberasategi** [comment]
Hi @teacherbot! This user got a unicorn when loading the invitation page, and then it said the invitation was not valid. Any clue on how she should proceed? Thanks!

**Comment by crichID** [comment]
@mberasategi I cancelled the old invitation and created a new one. @josugonzalez can you please try this link: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by mberasategi** [comment]
Kaixo @josugonzalez , han cerrado este issue por falta de actividad. Si terminaste el tutorial introductorio, puedes ignorar este mensaje. Si no, tendrás que empezar de nuevo; es mejor hacerlo seguido para hacerte una idea de cómo es el proceso. Si tienes cualquier problema, no dudes en comentarlo!
