### ISSUE TITLE
Borja Cilveti

### ISSUE THREAD

**Issue by BorjaCilveti** [githubschool/open-enrollment-classes-introduction-to-github#10132]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by mberasategi** [comment]
Kaixo @BorjaCilveti , te falta [rematar los últimos pasos](https://services.github.com/on-demand/intro-to-github/es/merge-pull-request): eliminar tu branch y cerrar este issue. 

- Para eliminar tu branch fácilmente, accede a la página de tu pull request #10146 y haz clic en el botón `Delete branch` que tienes al lado del mensaje de confirmación del merge.
- Si eso no cierra automáticamente este issue (sigue apareciendo `Open` en verde debajo del título del issue en esta página), tendrás que cerrarlo manualmente. Escribe un mensaje y en lugar de presionar el botón verde que dice `Comment`, pulsa `Close and comment`. Eso enviará tu mensaje y cerrará el issue. 

¡Animo!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
