### ISSUE TITLE
DAME UN CAFÉ PWEB

### ISSUE THREAD

**Issue by rofrago** [githubschool/open-enrollment-classes-introduction-to-github#10131]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by mberasategi** [comment]
Hi @teacherbot! This user got a unicorn when loading the invitation page, and then it said the invitation was not valid. Any clue on how she should proceed? Thanks!

**Comment by crichID** [comment]
@mberasategi that is interesting. The system shows she was invited. I cancelled the original invitation and made a new one. @rofrago can you please try this link: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by mberasategi** [comment]
Hola @rofrago , han cerrado este issue por falta de actividad. Si terminaste el tutorial introductorio, puedes ignorar este mensaje. Si no, tendrás que empezar de nuevo; es mejor hacerlo seguido para hacerte una idea de cómo es el proceso. Si tienes cualquier problema, no dudes en comentarlo!
