### ISSUE TITLE
Please add me - nakulkorde

### ISSUE THREAD

**Issue by nakulkorde** [githubschool/open-enrollment-classes-introduction-to-github#10270]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by nakulkorde** [comment]
The page freezes when I try to open the invitation

**Comment by crichID** [comment]
@nakulkorde I just cancelled the original invitation and created a new one. Can you please try again?

**Comment by nakulkorde** [comment]
Yes the new invitation works. Thanks!
