### ISSUE TITLE
Please add me - Gathersburg, MD

### ISSUE THREAD

**Issue by johnnywilkes** [githubschool/open-enrollment-classes-introduction-to-github#10282]
##adding Gaithersburg to the map

Hi everyone! THis issue is to track the addition of Gaithersburg to the map, which can be found at:

-Longitude: 39.1434° N
-Latitude: 77.2014° W

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
