### ISSUE TITLE
Add Delhi

### ISSUE THREAD

**Issue by tonybenoy** [githubschool/open-enrollment-classes-introduction-to-github#103]
## Adding Delhi to the map

Hi everyone! This issue is to track the addition of Delhi to the map, which can be found at:
- Longitude: 77.209021
- Latitude: 28.613939

**Comment by mayank833** [comment]
hi everyone. can someone be more specific about what are issues

**Comment by Ekaparna** [comment]
Hii Everyone add me to the city too.
