### ISSUE TITLE
New Branch issue

### ISSUE THREAD

**Issue by Jkelly65** [githubschool/open-enrollment-classes-introduction-to-github#10300]
Hello, I cannot create a new branch...

@githubteacher

**Comment by brianamarie** [comment]
Hi @Jkelly65! It looks like you are a collaborator, so you should be able to create a branch. Can you please try again and let me know if you are still unable?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
