### ISSUE TITLE
Edit Files on GitHub (tutorial) - build failed

### ISSUE THREAD

**Issue by SheYoe** [githubschool/open-enrollment-classes-introduction-to-github#10319]
Hello! :wave: 
@githubteacher I'm stuck and am unable to move to the next step, Merge Your Pull Requests. I corrected the issue I found with the directory named in the filename, but am still unable to proceed.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
