### ISSUE TITLE
Adding Portland, OR

### ISSUE THREAD

**Issue by WyldPhyr** [githubschool/open-enrollment-classes-introduction-to-github#1037]
## Adding <Portland, OR> to the map

Hi everyone! This issue is to track the addition of Portland to the map, which can be found at:

- Longitude: <122.6765° W>
- Latitude: <45.5231° N>

**Comment by LiPiZi** [comment]
Me too thanks

**Comment by TiltedSlinky** [comment]
Same here!

**Comment by TiltedSlinky** [comment]
Same Here!

**Comment by lucaskaufman** [comment]
Portland!

**Comment by samgavitte** [comment]
me portlando 2

**Comment by meshach5th** [comment]
me too!
