### ISSUE TITLE
Hiya There - New Girl Here - Please Add Me To This Class - Location: Caldwell, KS, USA

### ISSUE THREAD

**Issue by lecrisha82** [githubschool/open-enrollment-classes-introduction-to-github#10480]
Hey, guys and gals! Nice to meet your acquaintance! 🙂 Super excited at the prospect of forming some new friendships, having the opportunity to learn and perhaps even one day work alongside some of you. I look forward to becoming part of the GitHub family and would like to request my addition to this class.

Also, as I'd be incredibly shocked to discover my little town already pinned onto the map, I would like to formally request the addition of my tiny, little town.

If you would please add my location, I'd very much appreciate it.

Please add:  Caldwell, KS, USA
The coordinates are as follows:

LATITUDE:  37.033833198 
LONGITUDE:  -97.605330912

Thank you very much!

**Comment by kiranjd** [comment]
Don't mind me. Getting familiar with the comments :p

**Comment by lecrisha82** [comment]
No worries at all hun.  🙂 Take all the time you need to familiarize yourself, just as we all are I'm sure. Also, it's a pleasure to meet your acquaintance.
