### ISSUE TITLE
I need help, 

### ISSUE THREAD

**Issue by Curioion** [githubschool/open-enrollment-classes-introduction-to-github#10538]
Can you tell me  more about Issue_template.md? how can it pre-populate and help to fix the bug?

**Comment by Curioion** [comment]
ok bot we will wait for pesky human

**Comment by hollenberry** [comment]
👋  @Curioion The issue template isn't used to fix any bugs, but you can create one to auto populate any issues that someone opens in your repository. This is a nice blog resource about it: https://github.com/blog/2111-issue-and-pull-request-templates

Please let me know if you have any other questions! Sorry for the delay in response, sometimes these can get buried in the activity noise.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
