### ISSUE TITLE
Please add me - Nashua, NH

### ISSUE THREAD

**Issue by JohnSantana1** [githubschool/open-enrollment-classes-introduction-to-github#10759]
# # Adding Nashua to the map

Hi Everyone! This issue is to track the addition of <your city> to the map, which can be found at:

- Longitude: -71.4676
- Latitude: 42.7654

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
