### ISSUE TITLE
Please add me : Ghazipur , Uttar Pradesh

### ISSUE THREAD

**Issue by IsAmrish** [githubschool/open-enrollment-classes-introduction-to-github#10787]
Hello! :wave: Please add me as a collaborator to this repo. 
Hi everyone this is request to add ghazipur city on map which can be found at 

-Longitude: 83.5770202
-Lattitude: 25.5840419

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
