### ISSUE TITLE
location Grass Valley CA please add me to the discussion

### ISSUE THREAD

**Issue by CWBETHEL** [githubschool/open-enrollment-classes-introduction-to-github#10905]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by CWBETHEL** [comment]
Thank you. ..I guess?
