### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by sulphy** [githubschool/open-enrollment-classes-introduction-to-github#10933]
I don't think I have collaborator rights.  Although I get an invitation from the teacher bot, after clicking accept I get a notification saying the invitation is invalid.

**Comment by sulphy** [comment]
@githubteacher

**Comment by hollenberry** [comment]
👋  @sulphy 🤔 . I'm not sure why this is happening, but might be due to an automation issue. I've gone ahead and added you manually. Can you check https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations and see if that resolved it?

**Comment by jimlp1** [comment]
Not what I wanted...!

**Comment by sulphy** [comment]
@hollenberry thanks for sorting that ! :)
