### ISSUE TITLE
Hosting pictures in GitHub

### ISSUE THREAD

**Issue by JackSayles** [githubschool/open-enrollment-classes-introduction-to-github#10966]
Hello! :wave: Please add me as a collaborator to this repo. 
I need help figuring out how to host pictures in github. I have uploaded one picture and now I need to figure out how to get it hosted so that I can link to it.
@githubteacher

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by JackSayles** [comment]
Yes, thank you. I did a search and found a video that helped and then discovered my syntax errors in my code, which was making life difficult.
