### ISSUE TITLE
sdfghjkl

### ISSUE THREAD

**Issue by JoaoPLGomes** [githubschool/open-enrollment-classes-introduction-to-github#10992]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by luisbraganca** [comment]
vais chumbar

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by luisbraganca** [comment]
Don't close it :(

**Comment by luisbraganca** [comment]
yes

**Comment by brianamarie** [comment]
@luisbraganca Are you still working on the activity?

**Comment by brianamarie** [comment]
Actually - @luisbraganca it looks like this isn't your issue, but one created by someone else. Why would you like to keep this issue open?
