### ISSUE TITLE
How to Add Special Files to Repository

### ISSUE THREAD

**Issue by rbenenato** [githubschool/open-enrollment-classes-introduction-to-github#11035]
@githubteacher, how do I add files CONTRIBUTING.md and ISSUE_TEMPLATE.md to an existing repository?

**Comment by hollenberry** [comment]
Hey @rbenenato ! You should be able to just add the files to a .git folder, or directly to your repository. Check this out as an extra resource, and let us know if you need any more help! https://github.com/blog/2111-issue-and-pull-request-templates
