### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by alhoun17** [githubschool/open-enrollment-classes-introduction-to-github#11033]
The invites are coming up invalid when I accept the invite.

**Comment by hollenberry** [comment]
> The invites are coming up invalid when I accept the invite.

@alhoun17 It looks like you were ultimately able to open a PR, please let me know if there's anything else I can do to help!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
