### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Zynkah** [githubschool/open-enrollment-classes-introduction-to-github#11042]
hey so i believe i did the assignment correctly yet i do not see my pin. what did i do wrong?

**Comment by hollenberry** [comment]
Hey @Zynkah ! Are you sure that you placed the coordinates in the right place? You can certainly try and go through the workflow again if not.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
