### ISSUE TITLE
Add me [DUPLICATED] [This invitation is invalid]

### ISSUE THREAD

**Issue by alex-bender** [githubschool/open-enrollment-classes-introduction-to-github#11043]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by alex-bender** [comment]
I've got error: `This invitation is invalid.`

**Comment by alex-bender** [comment]
@hollenberry Could you please help me?

**Comment by hollenberry** [comment]
Hey @alex-bender ! Sorry for the delay. I've cancelled the automated add and invited you directly. Can you try again via this link? https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations
