### ISSUE TITLE
Training exercises test

### ISSUE THREAD

**Issue by Blhepp** [githubschool/open-enrollment-classes-introduction-to-github#11059]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by Blhepp** [comment]
I accepted the invitation, but received an error message saying my invite was not valid.

**Comment by Blhepp** [comment]
@githubteacher what is the best way to get added as a collaborator so I can keep moving forward with my training?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
