### ISSUE TITLE
Add me! [Duplicate] Invitation is invalid

### ISSUE THREAD

**Issue by mrugeshtank** [githubschool/open-enrollment-classes-introduction-to-github#11127]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by mrugeshtank** [comment]
This invitation is invalid.

Could you please send another one?

**Comment by brianamarie** [comment]
@mrugeshtank I am seeing the 'contributor' badge next to your name here - were you able to get the invitation problem sorted, or do you still need help?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
