### ISSUE TITLE
Let's try this again. Please add me!

### ISSUE THREAD

**Issue by Excoh** [githubschool/open-enrollment-classes-introduction-to-github#11131]
Hello! :wave: Please add me as a collaborator to this repo. 

## Adding Tempe to the map

Hi everyone! This issue is to track the addition of Tempe to the map. Here are the coordinates:

- Longtiude: [33.417413]
- Langitude: [-111.934511]

**Comment by Excoh** [comment]
It seems that the invitation was invalid, is it possible to send another one without making creating another issue?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
