### ISSUE TITLE
Invalid Invitation

### ISSUE THREAD

**Issue by Excoh** [githubschool/open-enrollment-classes-introduction-to-github#11132]
Hey @githubteacher! The invitation for collaboration after creating a new issue is invalid. I've made a new issue but it still doesn't work for that one so I closed that issue.

**Comment by brianamarie** [comment]
Hi @Excoh! I am seeing here that you have the 'contributor' badge. Were you able to get the collaboration problems sorted out?

**Comment by Excoh** [comment]
@brianamarie Ya it's all good! I just forked the repo and made a pull request from there. Thank you!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
