### ISSUE TITLE
Trial file

### ISSUE THREAD

**Issue by lizaDS2016** [githubschool/open-enrollment-classes-introduction-to-github#1114]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <38.7893 N>
- Latitude: <77.1872 W>

**Comment by TKONTOP** [comment]
what its use for?

**Comment by lizaDS2016** [comment]
Hi everyone! Here is my coordinate location:
Longitude: <38.7893 N>
Latitude: 77.1872 W>
