### ISSUE TITLE
please add me

### ISSUE THREAD

**Issue by chaddha1** [githubschool/open-enrollment-classes-introduction-to-github#11246]
Hello! :wave: Please add me as a collaborator to this repo. 
hi ! everyone.this issue is to add my city to the map which can be bounded at-
-longitude:77.4839613
-latitude:28.6493325

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
