### ISSUE TITLE
why this shows fail?

### ISSUE THREAD

**Issue by Ahmadkhan12345566** [githubschool/open-enrollment-classes-introduction-to-github#11250]
why this showing me fail i follow the same steps in the vedio
![ice_screenshot_20171028-123248](https://user-images.githubusercontent.com/20639894/32137844-7757e056-bbdc-11e7-9351-3d19e58979f2.png)
![ice_screenshot_20171028-123300](https://user-images.githubusercontent.com/20639894/32137845-779944ec-bbdc-11e7-8765-451756836156.png)

**Comment by brianamarie** [comment]
@Ahmadkhan12345566 In your pull request, there should be someone who has stopped by (or will be there soon) to give some answers to this very good question! I am going to close this issue here, but please keep asking in your pull request - it's the right question!

**Comment by Ahmadkhan12345566** [comment]
yup i got the answer thanks
