### ISSUE TITLE
Class goals

### ISSUE THREAD

**Issue by KhanhDangDuy** [githubschool/open-enrollment-classes-introduction-to-github#11291]
# Hello! :wave: Please add me as a collaborator to this repo. 
## Herewith my goals in studying this class:

1. Get familiar with GitHub.
2. _**Join the CNC controller community.**_

Hope we can enjoy during studying!
Thanks!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
