### ISSUE TITLE
Please add me: SFO, CA.

### ISSUE THREAD

**Issue by santoshgodavarthi** [githubschool/open-enrollment-classes-introduction-to-github#11297]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by brianamarie** [comment]
Hi @santoshgodavarthi! Click here to accept your invitation: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
