### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by JosueRodrigu3z** [githubschool/open-enrollment-classes-introduction-to-github#11292]
My invitation is invalid. It does not let me accept it.

**Comment by brianamarie** [comment]
@JosueRodrigu3z Sorry about that - try this link: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
