### ISSUE TITLE
Add me!

### ISSUE THREAD

**Issue by rbearda11** [githubschool/open-enrollment-classes-introduction-to-github#11306]
@rbearda11 Hello! :wave: Please add me as a collaborator to this repo.

**Comment by rbearda11** [comment]
automagic...

**Comment by brianamarie** [comment]
Hi @rbearda11! Our bot is sleeping (and under construction) so I commented with the URL (https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations) in your other issue. Sorry about the inconvenience!
