### ISSUE TITLE
Add me

### ISSUE THREAD

**Issue by deimosmuc** [githubschool/open-enrollment-classes-introduction-to-github#1130]
## Adding Dachau to the map

Hi everyone! This issue is to track the addition of Dachau to the map, which can be found at:
- Longitude: 11,2548
- Latitude: 48,1536

**Comment by Hex7CD** [comment]
## Adding myself to Dachau

Hey, everyone! I'll add myself to Dachau
I also want to fix its position. The actual longitude and latitude according to NASA are:
- Longitude: 11.433902
- Latitude: 48.262998
