### ISSUE TITLE
please add me - Bangalore,India

### ISSUE THREAD

**Issue by danctechi** [githubschool/open-enrollment-classes-introduction-to-github#11313]
##Adding my city Bangalore to map

Hello! :wave: Please add me as a collaborator to this repo. 

-longitude:77.64672
-latitude:12.98986

**Comment by brianamarie** [comment]
Hi @danctechi! Click here to accept your invitation: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
