### ISSUE TITLE
Please Add Me, Mehdi from Iran

### ISSUE THREAD

**Issue by Davoudpur** [githubschool/open-enrollment-classes-introduction-to-github#11314]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by Davoudpur** [comment]
Please Add Me

**Comment by brianamarie** [comment]
Hi @Davoudpur!  Click here to accept your invitation: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
