### ISSUE TITLE
Please add me - Pune,India

### ISSUE THREAD

**Issue by Eladfundo** [githubschool/open-enrollment-classes-introduction-to-github#11323]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by Eladfundo** [comment]
##Adding my city Pune to map

Hello! 👋 Please add me as a collaborator to this repo.

-longitude:73.8567° E
-latitude:18.5204° N

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
