### ISSUE TITLE
First steps with the 101 class

### ISSUE THREAD

**Issue by mrockinger** [githubschool/open-enrollment-classes-introduction-to-github#11359]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by mrockinger** [comment]
the invite does not work

**Comment by mrockinger** [comment]
too bad. disgusting

**Comment by mrockinger** [comment]
grrrr

**Comment by brianamarie** [comment]
Hi @mrockinger! Sorry about the problems before - our bot was having a bit of a bug. Please find your invitation here: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations
