### ISSUE TITLE
I think I found a bug with my first submitted issue

### ISSUE THREAD

**Issue by Groovy92** [githubschool/open-enrollment-classes-introduction-to-github#11391]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by brianamarie** [comment]
Hi @Groovy92!  Is everything OK?

**Comment by Groovy92** [comment]
Hello @brianamarie, after I've submitted my first issue to become a collaborator and complete the first lesson, I've noticed an issue where my invitation wouldn't work. What I mean by that is that I received the link to the invitation tab and accepted the invitation but it wouldn't work. The only thing that worked was to decline it and create a new issue. As a side note I've noticed that the site was loading very slow while in the same time youtube or other sites' loading time were fast as usual.

**Comment by brianamarie** [comment]
Hm, interesting. Thank you for letting me know! It's good to know that if you delete the invite, and re-comment, it did work. I will go ahead and clean up some of the collaborators now in case that is slowing things down. 😄 Thanks for your help!

**Comment by stefannibrasil** [comment]
Hi @brianamarie I am facing the same issue here :(

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
