### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by laer1** [githubschool/open-enrollment-classes-introduction-to-github#11403]
How to close a pull request with the keyword closes?

How to know the issue number?

**Comment by ash-norsidi** [comment]
I believe the keyword `closes` is used to **close an issue** with the pull request, not to close to pull request itself.

You can find the issue number from the `Issues` tab. If you have created an issue, you will usually be able to get the issue number right after you created one. In any case, if you missed it, you can go to the `Issues` tab, and then filter by `Your issues`:
![github - filter issue](https://user-images.githubusercontent.com/19640481/32550757-46c09870-c4c9-11e7-9c86-fcc5ca5c65f7.JPG)

As you can see, you may also filter to your pull request here. 
The issue number may be found on the issue page, or on the filtered list:
![github - issue number 2](https://user-images.githubusercontent.com/19640481/32551060-3aa3ba8a-c4ca-11e7-873c-20ee6897f571.JPG)

Good luck!

**Comment by hectorsector** [comment]
👏 thanks for the ✨ explanation @ash-norsidi.

@laer1 feel free to reopen if there's anything else we can answer.
