### ISSUE TITLE
Orlando

### ISSUE THREAD

**Issue by Hkhan15** [githubschool/open-enrollment-classes-introduction-to-github#1140]
Hi everyone! This issue is to track the addition of Orlando to the map, which can be found at:

- Longitude: -81.3792° W
- Latitude: 28.5383° N

**Comment by Nuridean** [comment]
Adding my name to the city of Orlando

**Comment by StephanNears** [comment]
Adding my Name as well!

**Comment by Snack-Pack** [comment]
Adding my name To Orlando

**Comment by Snack-Pack** [comment]
Adding my name to Orlando

**Comment by mariadodoll** [comment]
Adding my name to Orlando as well

**Comment by jrivera27** [comment]
Adding my name to Orlando!!!
