### ISSUE TITLE
Hi there !

### ISSUE THREAD

**Issue by Dicondur** [githubschool/open-enrollment-classes-introduction-to-github#11429]
Hello! :wave: Please add me as a collaborator to this repo. 

43.448931, -80.481720

**Comment by Dicondur** [comment]
@teacherbot Are you still there?

**Comment by brianamarie** [comment]
Hi @Dicondur! How can I help?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
