### ISSUE TITLE
I don' t know why this not adding me!?

### ISSUE THREAD

**Issue by 3Cement** [githubschool/open-enrollment-classes-introduction-to-github#11452]
## Adding 3Cement-Edinburgh to the map!

- Longitude: 55.953252
- Lattitude: -3.188267

**Comment by brianamarie** [comment]
Hi @3Cement! Sorry about that - this invitation should work now: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
