### ISSUE TITLE
Houston checking in

### ISSUE THREAD

**Issue by taihuynh83** [githubschool/open-enrollment-classes-introduction-to-github#115]
## Adding Houston to the map

Hi everyone! This issue is to track the addition of Houston to the map, which can be found at:

- Longitude: -95.369803
- Latitude: 29.760427

**Comment by taihuynh83** [comment]
cout <<"Hello World"<<endl;

**Comment by tdotcdot88** [comment]
I'll be adding my name to the pin for Houston

**Comment by geckya** [comment]
Adding
