### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by iangpaterson** [githubschool/open-enrollment-classes-introduction-to-github#11508]
When committing my username.json file to the _pins directory, it tried to add 3811 files (presumably everyone elses json files)

**Comment by hectorsector** [comment]
Yikes, that's no good @iangpaterson. I am looking at your pull request https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/11510 and I see only one file. Is the one you were talking about?

Sometimes, when a pull request is opened in reverse, you will see a lot of files ("reverse" means that you're trying to merge from the `master` branch into your branch, ideally you'd want to merge in the other direction). Is it possible that was the case?

**Comment by hectorsector** [comment]
@iangpaterson is there a link to where you see this, or can you show me a screenshot? The only pull request I can find for you is #11510 and that only shows one file modified.

**Comment by iangpaterson** [comment]
@hectorsector, in the on-screen instructions;
<img width="1050" alt="screen shot 2017-11-09 at 20 42 14" src="https://user-images.githubusercontent.com/20770957/32628797-efcea608-c58e-11e7-85b3-493929389dae.png">

In your new branch, add a new file named: _pins/YOUR-USERNAME.json

After creating this folder and file, it added every other .json file to the branch.

Maybe I've misunderstood what was supposed to happen at this point, but I assumed (possibly incorrectly) my .json file would be the only file added to a folder I have just created.

Please explain if I have misunderstood what was supposed to happen or indeed if something did go wrong.

**Comment by hectorsector** [comment]
Ah! Yes, when you create a new commit, it bases it on the most recent commit on the master branch. This means that you'll see all the pins that others have added up until that point.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
