### ISSUE TITLE
I'm Here

### ISSUE THREAD

**Issue by lightcodes** [githubschool/open-enrollment-classes-introduction-to-github#11545]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by lightcodes** [comment]
Please add me to the class.

**Comment by hectorsector** [comment]
@lightcodes just [accept the invitation](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations) and you should be all set!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
