### ISSUE TITLE
Please add me - Freeport, ME

### ISSUE THREAD

**Issue by JaySeiler** [githubschool/open-enrollment-classes-introduction-to-github#11542]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by JaySeiler** [comment]
thanks?

**Comment by hectorsector** [comment]
> thanks?

😸 I think 🤖 would say "you're welcome" if it could

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
