### ISSUE TITLE
Please add me - Anjo, Aichi, Japan

### ISSUE THREAD

**Issue by RuhRuh66** [githubschool/open-enrollment-classes-introduction-to-github#11630]
## Adding Anjo to the map

Hi bro! This issue is to track the addition of Anjo, Aichi, Japan to the map, which can be found at:

-Longitude:137.077703
-Latitude:34.940126

**Comment by RuhRuh66** [comment]
Thanks a lot!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
