### ISSUE TITLE
Please Add me - NWA, AR

### ISSUE THREAD

**Issue by AnilBodapati** [githubschool/open-enrollment-classes-introduction-to-github#11685]
Hello 👋 : Please add me as a collaborator to this repo. 

## Adding NWA to the mpa

Hi Everyone! This is to track the addition of NWA to the map, which can be found at
-Latitude - 36.315975
-Longitude - -94.154618

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
