### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Meagan-Trejo** [githubschool/open-enrollment-classes-introduction-to-github#11719]
I submitted an issue but I don't think I've been added as a collaborator because I can't create a new branch. @githubteacher

**Comment by psansom** [comment]
I think you have to accept the teacherbot's invitation that is sent to your email, in order to be a collaborator

@psansom

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
