### ISSUE TITLE
Please add me - Clinton Township, MI

### ISSUE THREAD

**Issue by arockkk12345** [githubschool/open-enrollment-classes-introduction-to-github#11716]
##Adding Clinton Township to the map

Hi everyone! This issue is to track the addition of Clinton Township, MI to the map, which can be found at:

-Longitude: 42.5869
-Latitude: 82.9196

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
