### ISSUE TITLE
Please add me - Brooklyn, NY

### ISSUE THREAD

**Issue by nrl240** [githubschool/open-enrollment-classes-introduction-to-github#11883]
## Adding Brooklyn to the map

Hi everyone! This issue is to track the addition of Brooklyn to the map, which can be found at:
- Longitude: 40.6782
- Latitude: 73.9442

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
