### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by wahidc7101** [githubschool/open-enrollment-classes-introduction-to-github#120]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by crichID** [comment]
Hey @wahidc7101 it looks like you also opened #121 so is it ok to delete this test issue?

**Comment by yoggychan** [comment]
Hi, Im still new student
