### ISSUE TITLE
Please add me - Bharuch, India

### ISSUE THREAD

**Issue by prerakshah51** [githubschool/open-enrollment-classes-introduction-to-github#12037]
# adding Bharuch to the map

Hi everyone! This issue is to track the addition of Bharuch to the map, which can be found at:

Longitude: 72.998199
Latitude: 21.705723

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
