### ISSUE TITLE
add me ^-^

### ISSUE THREAD

**Issue by yiting-tan** [githubschool/open-enrollment-classes-introduction-to-github#12105]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by crichID** [comment]
@yiting-tan it looks like you still need to accept the invitation we emailed you to become a collaborator on this repository! For a shortcut, you can also click [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations).

Once you have accepted the invitation, you will be ready for the [next steps](https://services.github.com/on-demand/intro-to-github/explore-github-repository)
