### ISSUE TITLE
Please Add me - Mexico City

### ISSUE THREAD

**Issue by leguiart** [githubschool/open-enrollment-classes-introduction-to-github#12144]
Hello! :wave: Please add me as a collaborator to this repo. 
-Longitude: -99.133209
-Latitude: 19.432608

**Comment by jgabrielmiranda** [comment]
Hi,

I'd like do unsubscribe to thjis thread.

Tks

Em dom, 26 de nov de 2017 às 14:53, teacherbot[bot] <
notifications@github.com> escreveu:
