### ISSUE TITLE
Issue: Cant close an issues without 8 failures

### ISSUE THREAD

**Issue by willhaney3** [githubschool/open-enrollment-classes-introduction-to-github#12162]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by crichID** [comment]
@willhaney3 I see that you have opened a few issues to be added as a collaborator. You actually only need to complete this step one time  and I can see from the badge on your original comment that you are already a `collaborator`!  How can I help?

**Comment by willhaney3** [comment]
Hello Cynthia,

I have been following the tutorial: https://services.github.com/on-demand/intro-to-github/work-on-github

At the step “Create a Pull Request<https://services.github.com/on-demand/intro-to-github/create-pull-request>” the pull request fails.

Looking at the “Details<https://travis-ci.org/githubschool/open-enrollment-classes-introduction-to-github/builds/308009635?utm_source=github_status&utm_medium=notification>” it appears to be an SSL issues:

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning
Downloading yamllint-1.10.0-py2.py3-none-any.whl (42kB)
Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from yamllint)
Collecting pathspec>=0.5.3 (from yamllint)
Downloading pathspec-0.5.5.tar.gz
Building wheels for collected packages: pathspec
Running setup.py bdist_wheel for pathspec: started
Running setup.py bdist_wheel for pathspec: finished with status 'done'
Stored in directory: /home/travis/.cache/pip/wheels/21/7b/4d/df92c0e6e329779e98d2b6bfd58cc7ce80d2bfed23660328c6
Successfully built pathspec
Installing collected packages: pathspec, yamllint
Successfully installed pathspec-0.5.5 yamllint-1.10.0
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.

I am not sure how to proceed.

Thanks,
Will

**Comment by crichID** [comment]
@willhaney3 got it! I just added some comments to your pull request over in #12157 to help you fix the build errors. Check out the video for a little step-by-step and let me know if anything doesn't make sense.

**Comment by crichID** [comment]
@willhaney3 it looks like you have merged #12157 so I will go ahead and close this issue! Great work :tada: :sparkles: :tada:
