### ISSUE TITLE
Please add me - Glen Allen VA

### ISSUE THREAD

**Issue by saluchau** [githubschool/open-enrollment-classes-introduction-to-github#12205]
Hello! :wave: Please add me as a collaborator to this repo. 

Glen Allen, VA is located at:
Latitude: 37.665978
Longitude: -77.5063739

**Comment by crichID** [comment]
@saluchau it looks like you still need to accept the invitation we emailed you to become a collaborator on this repository! For a shortcut, you can also click [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations).

Once you have accepted the invitation, you will be ready for the [next steps](https://services.github.com/on-demand/intro-to-github/explore-github-repository)
