### ISSUE TITLE
test issues

### ISSUE THREAD

**Issue by BViki** [githubschool/open-enrollment-classes-introduction-to-github#12222]
Hello! :wave: Please add me as a collaborator to this repo. 
test issues

**Comment by crichID** [comment]
@BViki it looks like you still need to accept the invitation we emailed you to become a collaborator on this repository! For a shortcut, you can also click [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations).

Once you have accepted the invitation, you will be ready for the [next steps](https://services.github.com/on-demand/intro-to-github/explore-github-repository)
