### ISSUE TITLE
Please add me - Shillong,IN

### ISSUE THREAD

**Issue by Sunnypaul393** [githubschool/open-enrollment-classes-introduction-to-github#12298]
##Adding Shillong to the map
Hi everyone!This issue is to track the addition of Shillong to the map, which can be found at:

-Longitude: 91.8933
-Latitude: 25.5788

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
