### ISSUE TITLE
Add Charleston, SC

### ISSUE THREAD

**Issue by humburgc** [githubschool/open-enrollment-classes-introduction-to-github#123]
## Adding Charleston, SC to the map

Hi everyone! This issue is to track the addition of Charleston, SC to the map, which can be found at:

- Longitude: -79.941984
- Latitude: 32.787852

**Comment by crichID** [comment]
@humburgc welcome neighbor! I am in NC. Looking forward to adding your pin to the map!

**Comment by humburgc** [comment]
@crichID Thanks. 
I fell behind in the GitHub for Developers webinar today, so I'm going with some self-guided tutorials. I believe I have a handle on the material in this tutorial, but thought it couldn't hurt before I dive into this one: [http://gitimmersion.com](url). Any suggestions?

**Comment by crichID** [comment]
@humburgc I have not been through the entire git immersion program but it looks pretty good! I would definitely :heart: to hear what you think of it when you are done!
