### ISSUE TITLE
Please add me - Norman, OK

### ISSUE THREAD

**Issue by SlowPick** [githubschool/open-enrollment-classes-introduction-to-github#12309]
## Adding Norman to the map
Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude -97.4482
- Latitude - 35.2248

**Comment by crichID** [comment]
@SlowPick it looks like you still need to accept the invitation we emailed you to become a collaborator on this repository! For a shortcut, you can also click [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations).

Once you have accepted the invitation, you will be ready for the [next steps](https://services.github.com/on-demand/intro-to-github/explore-github-repository)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
