### ISSUE TITLE
Please coun me in too - Nino, Ljubljana - Slovenia

### ISSUE THREAD

**Issue by NinoRode** [githubschool/open-enrollment-classes-introduction-to-github#12305]
Hello! :wave: Please add me as a collaborator to this repo.
I'm from Ljubljana, Slovenia (not Slovakia).

Ljubljana?
Longitude: 14.5144444
Latitude: 46.0552778
Sunny side of the Alps :-)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
