### ISSUE TITLE
Seattle, WA

### ISSUE THREAD

**Issue by meganizr** [githubschool/open-enrollment-classes-introduction-to-github#1234]
## Adding Seattle to the map

Hi everyone! This issue is to track the addition of Seattle to the map, which can be found at:
- Longitude: 47.6
- Latitude: -122.3

**Comment by TaraMeyer** [comment]
Re-opening the issue for training.  Thanks!

**Comment by latentblonde** [comment]
I'm adding my name to Seattle, WA as well.

**Comment by xhw1** [comment]
+1

**Comment by 3xj** [comment]
\m/

**Comment by vortexing** [comment]
Add me on to Seattle as well.

**Comment by vortexing** [comment]
Add me onto Seattle as well.

**Comment by jordanlsmith** [comment]
Another Seattle Add!

**Comment by jordanlsmith** [comment]
re
