### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by jbollman11** [githubschool/open-enrollment-classes-introduction-to-github#12399]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by jbollman11** [comment]
+---
 +githubHandle: jbollman11
 +latitude: 90.0715
 +longitude: 29.9511
 +---

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
