### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by jingxuanlu** [githubschool/open-enrollment-classes-introduction-to-github#12528]
Describe what you need help with here.
After following the tutorial to pin on the map step by step, I couldn't find my icon on the map in the end. Why?

**Comment by victory1355** [comment]
Tell me where are you ? please

**Comment by jingxuanlu** [comment]
New Orleans

**Comment by victory1355** [comment]
oh, you can fix it by refresh the web page , and this   is my way to fix it so it may be unsuitable for you.

**Comment by jingxuanlu** [comment]
It doesn't work for me. Thank you for your reply though!
