### ISSUE TITLE
Please add me as a Collaborator

### ISSUE THREAD

**Issue by markt01** [githubschool/open-enrollment-classes-introduction-to-github#12533]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by markt01** [comment]
Thank you bot
![image](https://user-images.githubusercontent.com/34245943/33809570-137cad20-ddc7-11e7-84cd-255b6e29c8bd.png)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
