### ISSUE TITLE
DixieDanger

### ISSUE THREAD

**Issue by DixieDanger** [githubschool/open-enrollment-classes-introduction-to-github#12537]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by DixieDanger** [comment]
May I get help on how to commit to the repo and write my code? I am very new and very green to this, but I learn quickly!

**Comment by johnandrilla** [comment]
# Take a note
As a *collaborator*, you have permission to commit.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
