### ISSUE TITLE
Class goals

### ISSUE THREAD

**Issue by Mimush** [githubschool/open-enrollment-classes-introduction-to-github#12571]
## My goals
- [ ] Learn how to use issues on GitHub
@githubstudent what other goals should I add here?

![01a0f32f37094325f62aa4e4a1a9903d13c6c84d2b_00001](https://user-images.githubusercontent.com/34467798/33869162-51b08180-df42-11e7-851f-bab2639e4f69.jpg)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
