### ISSUE TITLE
Please add me - Owerri, Nigeria

### ISSUE THREAD

**Issue by fortycoder** [githubschool/open-enrollment-classes-introduction-to-github#12579]
Hello! :wave: Please add me as a collaborator to this repo. 

My coordinates are  5° 28' 34.7160'' N and 7° 1' 33.0708'' E.

Thanks

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
