### ISSUE TITLE
Please add me - Izhevsk, Russian Federation

### ISSUE THREAD

**Issue by JavaHutt** [githubschool/open-enrollment-classes-introduction-to-github#12592]
Hello! :wave: Please add me as a collaborator to this repo. 
Will it be difficult for GitHub gurus to collaborate with me considering my bad english?

**Comment by lololo2** [comment]
PNH

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
