### ISSUE TITLE
Can't create a new branch - I need help

### ISSUE THREAD

**Issue by metacman** [githubschool/open-enrollment-classes-introduction-to-github#12606]
When trying to add a new branch, after typing the branch name, I don't see the blue 'Create' button to click on

**Comment by hectorsector** [comment]
@metacman now that you opened this issue it should've granted you the collaborator access you need. Let me know if that still doesn't work. If it does, feel free to close this issue!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
