### ISSUE TITLE
Please add me - Columbus, OH

### ISSUE THREAD

**Issue by Dobie55** [githubschool/open-enrollment-classes-introduction-to-github#12608]
## Adding Columbus, OH to the map

This issue is to track the addition of Columbus to the map, which can be found at:

= Longitude: -83.0001
- Latitude: 39.9611

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
