### ISSUE TITLE
How do I see the pin I added in the previous step

### ISSUE THREAD

**Issue by metacman** [githubschool/open-enrollment-classes-introduction-to-github#12610]
Please send a link to the pin I added for my lat/long

**Comment by hectorsector** [comment]
@metacman I see it [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/blob/master/_pins/metacman.json).

**Comment by metacman** [comment]
Thanks @hectorsector  I guess I was looking for a link to the page with the actual map, not the code behind the map.
