### ISSUE TITLE
Where Can I Delete a Branch I Created - I need help

### ISSUE THREAD

**Issue by metacman** [githubschool/open-enrollment-classes-introduction-to-github#12612]
what are the steps to delete a branch

**Comment by hectorsector** [comment]
@metacman you can delete branches from the page that shows [your branches](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/branches/yours), or from your pull request or from the Delete button in your [merged pull request](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/12609#issuecomment-351414035). let us know if you still need help, or close the issue out if that answers it!

**Comment by metacman** [comment]
got it Thanks @hectorsector
