### ISSUE TITLE
test2

### ISSUE THREAD

**Issue by garcima3** [githubschool/open-enrollment-classes-introduction-to-github#1272]
## Adding Chicago to the map

Hi everyone! This issue is to track the addition of Chicago to the map, which can be found at:
- Longitude: -87.629798
- Latitude: 41.878114

**Comment by abdulhaleembaram** [comment]
Ok

**Comment by abdulhaleembaram** [comment]
Ok

**Comment by abdulhaleembaram** [comment]
I like.
