### ISSUE TITLE
Please add me - Lincolnshire, IL

### ISSUE THREAD

**Issue by jpalwai** [githubschool/open-enrollment-classes-introduction-to-github#12741]
## Adding Lincolnshire to the map

Hi everyone! This issue is to track the addition of Lincolnshire to the map, which can be found at:

-Longitude 42.1900° N
-Latitude 87.9084° W

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
