### ISSUE TITLE
Please add me- Nashville, TN

### ISSUE THREAD

**Issue by fmendezc98** [githubschool/open-enrollment-classes-introduction-to-github#12755]
## Adding Nashville to the map

Hi everyone! This issue is to track the addition of Nashville to the map, which can be found at:

-Longitude: -86.802142 
-Latitude: 36.144871

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
