### ISSUE TITLE
recieving unwanted emails after adding myself to map

### ISSUE THREAD

**Issue by akashraj98** [githubschool/open-enrollment-classes-introduction-to-github#12760]
Hello! I don't know but after adding myself to map i am getting emails of evey other user that wants to add himself on map and their updates .
I muted the thread but still the problem remains
![screenshot from 2017-12-22 13-34-38](https://user-images.githubusercontent.com/13919140/34290353-e8f69c96-e71c-11e7-96cc-f0ed61b0119d.png)

![screenshot from 2017-12-22 13-31-04](https://user-images.githubusercontent.com/13919140/34290271-7214756c-e71c-11e7-9118-1914538f07a6.png)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
