### ISSUE TITLE
Please add me - Los Teques Venezuela

### ISSUE THREAD

**Issue by cekuran** [githubschool/open-enrollment-classes-introduction-to-github#12767]
## Adding Los Teques to the map

Hi all this the issue to track addition of Los Teques to the map, we can be found at:

Latitude: 10°20′40″ N 
Longitude: 67°02′35″ O

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
