### ISSUE TITLE
Please add me - Ukraine, Kharkov

### ISSUE THREAD

**Issue by sciblo** [githubschool/open-enrollment-classes-introduction-to-github#12807]
## Adding Kharkov to the map

Hi everyone! This issue is to track the eddition of Kharkov to the map, which can be founded:

- Longitude: 36.232845
- Latitude: 49.988358

**Comment by sciblo** [comment]
Please add me on the map

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
