### ISSUE TITLE
Adding Auckland, New Zealand to the Map

### ISSUE THREAD

**Issue by brodyd** [githubschool/open-enrollment-classes-introduction-to-github#1282]
## Adding Auckland, New Zealand to the map

Hi everyone! This issue is to track the addition of Auckland to the map, which can be found at:

- Longitude: -36.848461 (actually 174.763336)
- Latitude: 174.763336 (actually -36.848461)

**Comment by brodyd** [comment]
Got the values reversed

**Comment by emretinaz** [comment]
Hi there :)

**Comment by brodyd** [comment]
Howdy
