### ISSUE TITLE
Please add me - Gainesville, FL

### ISSUE THREAD

**Issue by willHL1004** [githubschool/open-enrollment-classes-introduction-to-github#12839]
Hello! :wave: Please add me as a collaborator to this repo. 

Hello - This issue is to track addition of Gainesville to the map, that can be found at:

Longitude: 82.3248°
Latitude: 29.6516°

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
