### ISSUE TITLE
A hoy hoy

### ISSUE THREAD

**Issue by Nantard** [githubschool/open-enrollment-classes-introduction-to-github#1291]
Nantard Adding Toronto to the map

Hi everyone! This issue is to track the addition of Toronto to the map, which can be found at:
- Longitude: 79.3832° W
- Latitude: 43.6532° N

![prenguintard](https://cloud.githubusercontent.com/assets/22920301/19576278/685c50e0-96e0-11e6-8d10-90c94012033c.jpg)

**Comment by jr-cologne** [comment]
WTF?! Crazy picture! 😆
