### ISSUE TITLE
Please add me - Bangalore, India

### ISSUE THREAD

**Issue by thirugopinath** [githubschool/open-enrollment-classes-introduction-to-github#12912]
Hello! :wave: Please add me as a collaborator to this repo. 

My location details are as follows:
-Longitude: 77.6202300
-Latitude: 13.0456860

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
