### ISSUE TITLE
Please Add My City To Map

### ISSUE THREAD

**Issue by Lkskwlkr** [githubschool/open-enrollment-classes-introduction-to-github#12945]
Hello! :wave: Please add Langwarrin, Australia to the map.

Latitude 38.1510° S
Longditude 145.1810° E

Thank you

@githubteacher

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
