### ISSUE TITLE
Continuous- Integration/Travis-CI

### ISSUE THREAD

**Issue by Saichethan** [githubschool/open-enrollment-classes-introduction-to-github#13022]
Most of people are facing problem with Travis-CI so, any one please improve wiki or documentation or videos regarding this

**Comment by brianamarie** [comment]
Hi @Saichethan! Sorry to hear that there are problems with Travis-CI. Could you help me understand what type of problems were coming up?

**Comment by Saichethan** [comment]
Sure,
Most of issue are based on Continuous-integration/Travis-CI. If there a documentation on that how to use,  how configure it would be helpful

**Comment by Saichethan** [comment]
Most common is
"Travis build failed"
Why it happens ?
What to do?
Documentation on these would be great

**Comment by brianamarie** [comment]
@Saichethan AH, I see. Thank you for expanding. Maybe Teacherbot, the app that already helps for a few tests, would watch for a failing build. If the status is failing, then Teacherbot could post a comment with some basic instructions for how to see and interpret the test results. What do you think?

**Comment by brianamarie** [comment]
@Saichethan I've opened an issue in Teacherbot to improve this. https://github.com/teacher-bot/teacherbot/issues/19

I will close this issue now, but please reopen if there is more to add. We'd also love specific feedback in the [issue in the Teacherbot repository](https://github.com/teacher-bot/teacherbot/issues/19). 😄
