### ISSUE TITLE
Please add me - New Delhi, India

### ISSUE THREAD

**Issue by parram** [githubschool/open-enrollment-classes-introduction-to-github#13044]
Hello! :wave: Please add me as a collaborator to this repo. 
## adding New Delhi to the Map
Hi Everyone this issue is to add New Delhi which can be found at
- Latitude 28.6139
- Longitude 77.2090

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
