### ISSUE TITLE
Travis CI settings

### ISSUE THREAD

**Issue by Saichethan** [githubschool/open-enrollment-classes-introduction-to-github#13218]
Most of the people are getting wrong with Travis settings please help them by automatic response for such problems @githubteacher

*Automatic response can be link of video on how to fix it, or documentation on it or GIF's.

**Comment by hectorsector** [comment]
Thanks for the heads up, @Saichethan! For now, it seems to be a [problem with the Travis CI service](https://www.traviscistatus.com/incidents/lrc4yp46t8wb). I've bene able to resolve some by opening the Travis CI log, and clicking on the button to "Restart build". But as long as the Travis CI service continues to be degraded we'll see some problems.

I'll update this issue when it seems resolved.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
