### ISSUE TITLE
Please Add Me - Moscow, ID

### ISSUE THREAD

**Issue by jjaawbkearns** [githubschool/open-enrollment-classes-introduction-to-github#13230]
## Adding Moscow to the map

Hi all! This issue is to track the addition of Moscow to the map which can be found at:

- Longitude: ‎-116.999939
- Latitude: 46.731705

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
