### ISSUE TITLE
Aamchi Mumbai

### ISSUE THREAD

**Issue by guruapr11** [githubschool/open-enrollment-classes-introduction-to-github#1328]
## Adding <Mumbai> to the map

Hi everyone! This issue is to track the addition of Mumbai to the map, which can be found at:
- Longitude: 19.0760° N
- Latitude: 72.8777° E
  ![gateway](https://cloud.githubusercontent.com/assets/23027649/19640055/b1941f70-99f8-11e6-8624-617210eac372.jpg)
  ![victoria_terminus _mumbai](https://cloud.githubusercontent.com/assets/23027649/19640056/b198f248-99f8-11e6-90af-45fab10bab62.jpg)

**Comment by amitkumarsi** [comment]
Hi! One more Mumbaikar here. Adding my name to this city.

**Comment by shyam-ramakrishnan** [comment]
Hey, I'm adding my name to Aamchi Mumbai!
