### ISSUE TITLE
I need help, Travis is not building.

### ISSUE THREAD

**Issue by CatSchrodinger** [githubschool/open-enrollment-classes-introduction-to-github#13442]
My #13441 is not ready to merge and it's taking a lot to do it. @githubteacher

**Comment by at97** [comment]
I think Travis CI build are stopped
https://www.traviscistatus.com/

**Comment by hectorsector** [comment]
@CatSchrodinger I think @at97 was right, you should now be good to merge. If it does not work still, feel free to reopen this issue!

**Comment by CatSchrodinger** [comment]
@at97 @hectorsector I merged it, thank you so much.
