### ISSUE TITLE
Please add me Ogden, UT

### ISSUE THREAD

**Issue by seanduback** [githubschool/open-enrollment-classes-introduction-to-github#13502]
## Adding Ogden, Utah to the map
This issue is to track the addition of Ogden, Utah to the map, which can be found at:

Longitude: 41.2230° N
Latitude: 111.9738° W

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
