### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by Nag-github** [githubschool/open-enrollment-classes-introduction-to-github#1356]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by Silvia-t** [comment]
Hey @Nag-github I think you should add the longitude and the latitude of the place :) 

(I'm no expert though as I couldn't add my own pin :sob: )
