### ISSUE TITLE
Add Basildon, Essex, UK please :) 

### ISSUE THREAD

**Issue by Silvia-t** [githubschool/open-enrollment-classes-introduction-to-github#1359]
## Adding Basildon to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 51.5761° N
- Latitude: 0.4887° E

**Comment by Silvia-t** [comment]
Let's see if I can do it now

**Comment by hollenberry** [comment]
Hey @Silvia-t !

I had a chance to look into your Pull Request, and it looks like you may have mixed up the Latitude and Longitude (so you should be showing up on the map, just not where you expect! 😄 ). 

<img width="764" alt="screen shot 2016-10-28 at 2 48 26 pm" src="https://cloud.githubusercontent.com/assets/13326548/19823506/ba9e3b64-9d1d-11e6-93ba-e5edc898e7ef.png">

You should be able to resolve this by opening a new PR and modifying the original file that you created.
