### ISSUE TITLE
Please, add me to this repository!

### ISSUE THREAD

**Issue by marlontrujillo1080** [githubschool/open-enrollment-classes-introduction-to-github#1363]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by Silvia-t** [comment]
Hey @marlontrujillo1080, shouldn't you add the coordinates? :)

**Comment by marlontrujillo1080** [comment]
Ups...
Latitude: 10°7'N.
Longitude: 64°41'W. 

Thanks!

**Comment by marlontrujillo1080** [comment]
10°07′00″N 
64°41′00″O
:p
