### ISSUE TITLE
Please add me - Miami, FL

### ISSUE THREAD

**Issue by MarvinTorres** [githubschool/open-enrollment-classes-introduction-to-github#13703]
#Adding Miami to the map

Hi everyone! This issue is to track the addition of Miami to the map, which can be found at:

- Longitude: 25.7616798
- Latitude: -80.19179020000001

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
