### ISSUE TITLE
Chapel Hill

### ISSUE THREAD

**Issue by mike01101101** [githubschool/open-enrollment-classes-introduction-to-github#1375]
## Adding Chapel Hill, NC to the map

Hi everyone! This issue is to track the addition of Chapel Hill, NC to the map, which can be found at:
- Longitude: <-79.055845
- Latitude: 35.913200

**Comment by lebrooks** [comment]
I'm also in Chapel Hill

**Comment by herbderby** [comment]
Also in Chapel Hill
