### ISSUE TITLE
Adding Raleigh

### ISSUE THREAD

**Issue by JuliaMurray** [githubschool/open-enrollment-classes-introduction-to-github#1379]
## Adding <Raleigh> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: <-78.638179>
- Latitude: <35.779590>

**Comment by rlwhitejr** [comment]
I will be adding my name to the city of Raleigh also.

**Comment by Ankit0592** [comment]
I am adding my name to Raleigh.

**Comment by Epgith** [comment]
I will add my name to Raleigh as well!

**Comment by rlgraham92** [comment]
Adding rgraham and aberger to Raleighwood 🌳

**Comment by Chandrasekar-Rajasekar** [comment]
adding Chandrasekar
