### ISSUE TITLE
San Diego, CA

### ISSUE THREAD

**Issue by hollenberry** [githubschool/open-enrollment-classes-introduction-to-github#14]
## Adding San Diego to the map

Hi everyone! This issue is to track the addition of San Diego to the map, which can be found at:

- Longitude: -117.1294°
- Latitude: 32.7456°

**Comment by The01Geek** [comment]
Adding Point Lomca, SD

**Comment by luketrotta** [comment]
add Carlsbad, San Diego, CA USA

**Comment by kerrystanko** [comment]
Adding my pin of North Park to the map!

**Comment by githubstudent** [comment]
test

**Comment by developmentim** [comment]
Adding another pin for North Park
