### ISSUE TITLE
Brooklyn addition

### ISSUE THREAD

**Issue by agoldmedal** [githubschool/open-enrollment-classes-introduction-to-github#141]
## Adding Brooklyn to the map

Hi everyone! This issue is to track the addition of Brooklyn to the map, which can be found at:
- Longitude: -73.944158
- Latitude: 40.678178

**Comment by sallyjiang** [comment]
I will be adding my name to the pin for this city.

**Comment by jthodge** [comment]
I will also be adding my name to the pin for Brooklyn.

**Comment by marynoel** [comment]
I will also add my name to Brooklyn.

**Comment by mrrabbitmessages** [comment]
I will add my name to Brooklyn
