### ISSUE TITLE
adding pin to montreal

### ISSUE THREAD

**Issue by gaimps** [githubschool/open-enrollment-classes-introduction-to-github#1415]
## Adding Montreal to the map

Hi everyone! This issue is to track the addition of Montreal to the map, which can be found at:
- Longitude: -73.567256
- Latitude: 45.501689

**Comment by gaimps** [comment]
yeah baby

**Comment by dodige** [comment]
adding to montreal

**Comment by eprattic** [comment]
Adding Montreal
