### ISSUE TITLE
Please add me to the lesson

### ISSUE THREAD

**Issue by Fabadiculous** [githubschool/open-enrollment-classes-introduction-to-github#14310]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by RandyOaks58** [comment]
Please add me to the lesson....
I had been trying to install OpenCV on my Lenovo G 560 Win 7 laptop and I couldnt get it to work so I tried installing Image Magick on the same machine with no success....I have come to the conclusion that I needed to take the time to do a lot more reading on how to do it before I try again.. 
I also have a PocketChip I had been trying to learn the Linux Terminal command line on and I was having a great time with it till I tripped over the charging cord and ripped the USB housing plug completely off the Chip on  my pocket chip. so now I am waiting for The Next Thing to start selling Chips again so i can get another Chip for my PocketChip.
I also have Damn Small Linux on CD that I play with and run from Oracle VirtualBox on my Win 7 Laptop and have learned to get around on it pretty good and I thought that was going to help me a lot with the terminal commands on the PocketChip OS Jessie but they are a little different.
I also have an Arduino Uno and breadboard with these sensors>>>
16pcs GPIO Kit
Designed for Arduino Raspberry Pi 3/2 Model B
1Pc x DHT11 temperature Humiture Sensor
1pc x HC-SR501 IR Pyroelectric Infrared PIR Motion Sensor Detector Module
1pc x DS1302 Clock Module
1pc x Rain sensor / module rain weather module
1pc x Sound sensor module
1pc x HC-SR04 ultrasonic sensor
1pc x Fire detection of flame sensor module
1pc x Ky-008 Laser Transmitter Module
1pc x Photoelectric sensor module
1pc x Soil humidity sensor
1pc x Black and white line identification for obstacle avoidance sensor
1pc x Vibration sensor module
1pc x MQ-2 gas sensor module
1pc x 315M super regeneration of 315M wireless transceiver module
1pc x Tilt sensor module
1pc x TCRT5000 infrared/optical tracking sensor 
and so I have been setting up a few of these sensors and learning The Arduino IDE coding which looks a lot like Java....I did take Java 101 in college and DOS and Qbasic and Visual Basic, PHP, Html....and probably a few more and I liked programming but Im really liking this learning to code for microcontrollers to control and program these little sensors...
So I had a phone conversation with Maggie from GitHub the other day....I wish i could have told you all that Im a great coder but Im not....yet and that is why Im here ....I want to learn more
