### ISSUE TITLE
Hello from Ottawa

### ISSUE THREAD

**Issue by Wenifred** [githubschool/open-enrollment-classes-introduction-to-github#1456]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of Ottawa to the map, which can be found at:

- Longitude: 45.421530
- Latitude: -75.697193

**Comment by reedkerma** [comment]
ill be will be adding your name to the same city

**Comment by elissaunrau** [comment]
I'm from Ottawa too!
