### ISSUE TITLE
Harvard, IL

### ISSUE THREAD

**Issue by appdev734** [githubschool/open-enrollment-classes-introduction-to-github#1515]
## Adding Harvard to the map

Hi everyone! This issue is to track the addition of Harvard to the map, which can be found at:

- Longitude: -88.6136111
- Latitude: 42.4222222

**Comment by appdev734** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22845374/19984434/4b1f07b4-a1dc-11e6-846c-e2c14389bf6c.jpg)

**Comment by brianamarie** [comment]
Hi @appdev734! Please don't close any issues or pull requests that are not your own.
