### ISSUE TITLE
I am from Guntur Andhra Pradesh

### ISSUE THREAD

**Issue by SureshRaavi** [githubschool/open-enrollment-classes-introduction-to-github#1526]
## Adding Guntur to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 16.3067° N
- Latitude: 80.4365° E

**Comment by Govardhan1991** [comment]
Dragon Booster

**Comment by Govardhan1991** [comment]
Adding my name to the city
