### ISSUE TITLE
Add Bangalore, India

### ISSUE THREAD

**Issue by acnithin** [githubschool/open-enrollment-classes-introduction-to-github#153]
## Adding Bangalore ,India to the map

Hi everyone! This issue is to track the addition of bangalore to the map, which can be found at:
- Longitude: 77.580643
- Latitude: 12.972442

**Comment by AmruthPillai** [comment]
I'm adding my name to the hat as well, another Gitter from Bangalore! :smile:

**Comment by sa3036** [comment]
Hello Everyone

**Comment by vishwasrao** [comment]
Hi All,
Vishwasrao Salunkhe from Bangalore...

**Comment by shwetankverma** [comment]
I'm adding my name to the hat as well, another Gitter from Bangalore!

**Comment by KarthikKadambi** [comment]
I'm adding my name to the hat as well, another Gitter from Bangalore!
