### ISSUE TITLE
Lagos, Nigeria

### ISSUE THREAD

**Issue by adexot** [githubschool/open-enrollment-classes-introduction-to-github#159]
Hi everyone! This issue is to track the addition of Lagos, Nigeria to the map, which can be found at:
- Longitude: 3.379206
- Latitude: 6.524379

**Comment by folagiwa** [comment]
Lagos state is a state located in the southwestern geopolitical zone of Nigeria with the population of 5.195million people. Victoria Island, the financial center of the metropolis, is known for its beach resorts, boutiques and nightlife.
