### ISSUE TITLE
Add Me

### ISSUE THREAD

**Issue by KarthikKadambi** [githubschool/open-enrollment-classes-introduction-to-github#1662]
## Adding Bangalore to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 77.5946° E
- Latitude: 12.9716° N

**Comment by ezeetester** [comment]
I am adding myself to the same city

**Comment by smwq** [comment]
Hi 

I am adding myself to the same city.
