### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by dabhitapan** [githubschool/open-enrollment-classes-introduction-to-github#17137]
Describe what you need help with here.

Some checks were not successful
2 failing and 2 successful checks

continuous-integration/travis-ci/pr — The Travis CI build failed
continuous-integration/travis-ci/push — The Travis CI build failed

**Comment by carlagob** [comment]
Hey @dabhitapan I hope you find help! I'm new too.

**Comment by dabhitapan** [comment]
thanks @carlagob I made few changes which worked for me successfully 
you can check them below 

---
githubHandle: dabhitapan
latitude: 23.022505
longitude: 72.571362
---

**Comment by Edditoria** [comment]
Congratulations!

For your information, you can add the reference number of your pull request when you ask this question. So people can click and find out the problem. It is similar to what you do in tutorial.

Also, you can type `closes #theNumber` when you think this issue is solved.
