### ISSUE TITLE
Culver City, CA

### ISSUE THREAD

**Issue by TedWolfe** [githubschool/open-enrollment-classes-introduction-to-github#177]
## Adding Culver City, CA to the map

Hey there dudes and dudettes...
Culver City is found at -118.396466 longitude and 34.021122 latitude!  Stop by and we'll get a beer.

**Comment by hollenberry** [comment]
Hey @TedWolfe ! We're so excited that you've successfully added your pin to the map and been participating with others on open issues/pull requests. 😄 

One quick note, though, we're hoping to leave PR's open so that people can experience the 🚢 and close their own workflows first-hand. 👍

**Comment by TedWolfe** [comment]
Ah, ok.  Sorry if I overstepped.

**Comment by hollenberry** [comment]
Not a problem! I saw that you went back and adjusted a closing, and we definitely appreciate that you had the best intentions to help 🎉 ✨ 

Thank you so much for contributing to the community. 😄
