### ISSUE TITLE
next r

### ISSUE THREAD

**Issue by vanpnaarp** [githubschool/open-enrollment-classes-introduction-to-github#1777]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by beardofedu** [comment]
@vanpnaarp please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
