### ISSUE TITLE
Add Holly Springs

### ISSUE THREAD

**Issue by shocasey** [githubschool/open-enrollment-classes-introduction-to-github#1783]
## Adding Holly Springs to the map

Hi everyone! This issue is to track the addition of Holly Springs to the map, which can be found at:

- Longitude: -78.833622
- Latitude: 35.651266

**Comment by beardofedu** [comment]
@shocasey please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
