### ISSUE TITLE
San Jose

### ISSUE THREAD

**Issue by pdefordg** [githubschool/open-enrollment-classes-introduction-to-github#1801]
## Adding San Jose to the map

Hi everyone! This issue is to track the addition of San Jose to the map, which can be found at:

- Longitude: 9.935536
- Latitude: -84.069807

**Comment by beardofedu** [comment]
@pdefordg please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927

**Comment by Jupiter-Mars** [comment]
Adding myself to San Jose
