### ISSUE TITLE
Add Raleigh, NC

### ISSUE THREAD

**Issue by casterland** [githubschool/open-enrollment-classes-introduction-to-github#1806]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by sshankjha** [comment]
New to GitHub!

**Comment by sshankjha** [comment]
Latitude: 35.779590
Longitude: -78.638179

**Comment by drazen-j** [comment]
:-)
