### ISSUE TITLE
Kathmandu

### ISSUE THREAD

**Issue by sshankjha** [githubschool/open-enrollment-classes-introduction-to-github#1816]
## Adding Kathmandu to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 85.323960
- Latitude: 27.717245

**Comment by beardofedu** [comment]
@sshankjha please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
