### ISSUE TITLE
Hookerton, North Carolina

### ISSUE THREAD

**Issue by devontedereef** [githubschool/open-enrollment-classes-introduction-to-github#1819]
## Adding <Hookerton> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <-77.594919>
- Latitude: <35.393830>

**Comment by beardofedu** [comment]
@devontedereef please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
