### ISSUE TITLE
new issue for my town/city

### ISSUE THREAD

**Issue by cgransfield** [githubschool/open-enrollment-classes-introduction-to-github#1838]
## Adding <Turangi> to the map

Hi everyone! This issue is to track the addition of <Turangi> to the map, which can be found at:

- Longitude: <175.8087° E>
- Latitude: <38.9899° S>

**Comment by beardofedu** [comment]
@cgransfield please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927

**Comment by cgransfield** [comment]
Add me please,  thanks...

**Comment by beardofedu** [comment]
@cgransfield We have a script setup to automatically add you as a collaborator to the repository if you add a comment to issue #927

**Comment by cgransfield** [comment]
Hi #927 says closed?  am I doing something wrong?  How do I comment? 

Sent from Yahoo Mail on Android 
 
  On Sat, 26 Nov, 2016 at 10:05 am, Matt Desmond<notifications@github.com> wrote:   
@cgransfield We have a script setup to automatically add you as a collaborator to the repository if you add a comment to issue #927

**Comment by amberream** [comment]
@cgransfield It's ok that #927 is closed.  Just scroll to the bottom of the issue (past all the other comments) and there will be a place to enter a new comment.

**Comment by beardofedu** [comment]
@amberream Thanks for providing a response 👍 
@cgransfield I re-opened the issue, but @amberream was right, even if the issue is closed you can still comment on it.
