### ISSUE TITLE
JA - Pennington

### ISSUE THREAD

**Issue by JosephAncil** [githubschool/open-enrollment-classes-introduction-to-github#1850]
## Adding Pennington to the map

Hi everyone! This issue is to track the addition of <Pennington> to the map, which can be found at:

Longitude: -74.759917
Latitude: 40.295127

**Comment by beardofedu** [comment]
@JosephAncil please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927

**Comment by JosephAncil** [comment]
Learning GitHub features by providing the Latitude and Longitude of Pennington.

**Comment by JosephAncil** [comment]
Removed brackets from the Latitude and Longitude
