### ISSUE TITLE
Please Add Me

### ISSUE THREAD

**Issue by JonWaters** [githubschool/open-enrollment-classes-introduction-to-github#1854]
## Adding Leesburg, VA to the map

Hi everyone! This issue is to track the addition of Leesburg, VA to the map, which can be found at:

- Longitude: -77.555574
- Latitude: 39.106506

**Comment by beardofedu** [comment]
@JonWaters please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
