### ISSUE TITLE
Columbia, MO

### ISSUE THREAD

**Issue by zzachzz** [githubschool/open-enrollment-classes-introduction-to-github#1868]
## Adding Columbia, MO to the map

Hi everyone! This issue is to track the addition of Columbia, MO to the map, which can be found at:

- Longitude: <38.951705>
- Latitude: <-92.334072>

**Comment by beardofedu** [comment]
@zzachzz please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
