### ISSUE TITLE
Please add me!

### ISSUE THREAD

**Issue by tlwilliams895** [githubschool/open-enrollment-classes-introduction-to-github#1872]
## Adding Newark to the map

Hi everyone! This issue is to track the addition of Newark to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by beardofedu** [comment]
@tlwilliams895 please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
