### ISSUE TITLE
Pls add me

### ISSUE THREAD

**Issue by allen-chi** [githubschool/open-enrollment-classes-introduction-to-github#1877]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of lagos to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by beardofedu** [comment]
@allen-chi please make a comment on this thread: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
