### ISSUE TITLE
Add me!

### ISSUE THREAD

**Issue by kevinah95** [githubschool/open-enrollment-classes-introduction-to-github#1880]
## Adding Pavas, San José, Costa Rica to the map

Hi everyone! This issue is to track the addition of Pavas, San José, Costa Rica to the map, which can be found at:

- Longitude: -84.155305
- Latitude: 9.953814

**Comment by beardofedu** [comment]
@kevinah95 please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
