### ISSUE TITLE
New:  Add Me

### ISSUE THREAD

**Issue by panemec** [githubschool/open-enrollment-classes-introduction-to-github#1882]
Adding Phoenix to the map

Hi everyone! This issue is to track the addition of Phoenix to the map, which can be found at:

- Longitude: 33.4484° N
- Latitude: 112.0740° W

**Comment by beardofedu** [comment]
@panemec please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927

**Comment by panemec** [comment]
Hey Matt...thanks for the note...I attempted to comments as requested...I'm uncertain whether my comment landed in the correct respo #927...let me know...thanks...Phil

________________________________

**Comment by beardofedu** [comment]
It doesn't look like you commented on the issue. Just add a comment on issue #927 similar to how you are making comments on this issue. 👍

**Comment by panemec** [comment]
Matt,


This is becoming a real hassle.  Ok, I clicked on new issue and it comes back with a #1916...am I clicking on the wrong button?  I don't see anything else to click on...help me out buddy!

________________________________

**Comment by beardofedu** [comment]
@panemec 
Click on this link right here: #927 
That will open up the `Comment here!` issue that you just need to make a comment on.

**Comment by panemec** [comment]
Matt...so when I follow your instructions I land on the page captured in my screen shot attached...where would I click next to meet the requirements?

Thanks...


Phil

________________________________

**Comment by panemec** [comment]
Matt...when I follow your instructions I land the the page in the first screen shot...it looks like I'm in the right place...then when I click the new issue button it takes me to a form to complete...I complete the form and then submit it...once submitted it shows #1937...Can you please tell me what I'm doing wrong?


Thanks


Phil

________________________________

**Comment by jr-cologne** [comment]
@panemec It looks like you are already a collaborator, so you don't need to worry about it anymore.
