### ISSUE TITLE
Setting up Wellington

### ISSUE THREAD

**Issue by VicBoondigga** [githubschool/open-enrollment-classes-introduction-to-github#1884]
## Adding Wellington to the map

Hi everyone! This issue is to track the addition of Wellington to the map, which can be found at:

- Longitude: 174.758062
- Latitude: -41.286672

**Comment by beardofedu** [comment]
@VicBoondigga please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
