### ISSUE TITLE
Please add me. Thanks!!

### ISSUE THREAD

**Issue by pslorda** [githubschool/open-enrollment-classes-introduction-to-github#1885]
## Adding Avilés to the map

Hi everyone! This issue is to track the addition of Avilés to the map, which can be found at:

- Longitude: -5.844758
- Latitude: 43.360259

**Comment by beardofedu** [comment]
@pslorda please add a comment to this thread to be added as a collaborator on this repo: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927

**Comment by felipegonzalezgarcia** [comment]
Añadir avilés al mapa, otra vez
