### ISSUE TITLE
My issue

### ISSUE THREAD

**Issue by holyhellga** [githubschool/open-enrollment-classes-introduction-to-github#1895]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by holyhellga** [comment]
Hi everyone! This issue is to track the addition of to the map, which can be found at:
•Longitude: 48.758339
•Latitude: 8.243008 
:D Sorry now I realize

**Comment by brianamarie** [comment]
Hi @holyhellga! Make sure you comment on [this thread](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927) so you'll be able to continue with the course: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
