### ISSUE TITLE
I am in Wuhu

### ISSUE THREAD

**Issue by hwaphon** [githubschool/open-enrollment-classes-introduction-to-github#1900]
## Adding Wuhu to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hi @hwaphon! Make sure you comment on [this thread](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927) so you'll be able to continue with the course: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
