### ISSUE TITLE
Add me

### ISSUE THREAD

**Issue by panemec** [githubschool/open-enrollment-classes-introduction-to-github#1916]
Please add me

**Comment by brianamarie** [comment]
Hi @panemec! Make sure you comment on [this thread](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927) so you'll be able to continue with the course: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927

**Comment by panemec** [comment]
Briana...I'm at a loss...what do you click to comment? I'm sure its right before me but I cannot see how to comment...sorry...would you help me please?

________________________________

**Comment by brianamarie** [comment]
@panemec Of course! Click the link, then scroll to the bottom. It may be quite a ways to scroll, but once you're at the bottom it should look just like it does when you comment on this page. 😄
