### ISSUE TITLE
Lagos, Nigeria

### ISSUE THREAD

**Issue by anness** [githubschool/open-enrollment-classes-introduction-to-github#1917]
## Adding <Lagos> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <4.1309>
- Latitude: <6.4975>

**Comment by anness** [comment]
what next?

**Comment by jr-cologne** [comment]
1. [Create your branch](https://services.github.com/on-demand/intro-to-github/04/)
2. [Add a new pin to the map](https://services.github.com/on-demand/intro-to-github/05/)
3. [Create a Pull Request](https://services.github.com/on-demand/intro-to-github/06/)
4. [Merge your Pull Request](https://services.github.com/on-demand/intro-to-github/08/)

Click on the links for detailed instructions.

Hope that helps! :)
