### ISSUE TITLE
hi new here and I don't understand what to do

### ISSUE THREAD

**Issue by UncleRaf** [githubschool/open-enrollment-classes-introduction-to-github#1920]
## Adding <port Harcourt> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hi @UncleRaf! Make sure you comment on [this thread](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927) so you'll be able to continue with the course: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
