### ISSUE TITLE
add me

### ISSUE THREAD

**Issue by lorraineliu** [githubschool/open-enrollment-classes-introduction-to-github#1939]
## Adding Shanghai to the map

Hi everyone! This issue is to track the addition of Shanghai to the map, which can be found at:

- Longitude: 121.48
- Latitude: 31.22

**Comment by brianamarie** [comment]
Hi @lorraineliu! Make sure you comment on this thread so you'll be able to continue with the course: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927
