### ISSUE TITLE
my first issues of goals

### ISSUE THREAD

**Issue by yuriypylypchuk** [githubschool/open-enrollment-classes-introduction-to-github#1945]
## Adding <Lviv> to the map

Hi everyone! This issue is to track the addition of <Lviv> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by yuriypylypchuk** [comment]
add my first issue

**Comment by brianamarie** [comment]
Hi @yuriypylypchuk! Make sure you comment on this thread so you'll be able to continue with the course: #927
