### ISSUE TITLE
Please add.

### ISSUE THREAD

**Issue by twopirllc** [githubschool/open-enrollment-classes-introduction-to-github#1947]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by twopirllc** [comment]
Test

**Comment by brianamarie** [comment]
Hi @twopirllc! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927

**Comment by twopirllc** [comment]
Thanks!

**Comment by twopirllc** [comment]
Thanks!
