### ISSUE TITLE
Buena Park, CA

### ISSUE THREAD

**Issue by twopirllc** [githubschool/open-enrollment-classes-introduction-to-github#1953]
## Adding Buena Park, CA to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: -117.998118
- Latitude: 33.867514

**Comment by brianamarie** [comment]
Hi @twopirllc! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
