### ISSUE TITLE
Please add Auchterarder

### ISSUE THREAD

**Issue by theiain143** [githubschool/open-enrollment-classes-introduction-to-github#1958]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: -3.699925
- Latitude:   56.300818

**Comment by SCOTTLB** [comment]
Not a city mate

**Comment by theiain143** [comment]
Give it 5 years, watch this space

**Comment by theiain143** [comment]
Thriving community
