### ISSUE TITLE
Stockholm

### ISSUE THREAD

**Issue by darwonsamal** [githubschool/open-enrollment-classes-introduction-to-github#1965]
## Adding <Stockholm> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Latitude: <59.3293° N>
- Longitude: <18.0686° E>

**Comment by x31xx** [comment]
Adding me  map

**Comment by ewallerman** [comment]
Adding to map

**Comment by aedrane** [comment]
Jag är med!
![30752_djurgardenfarjan](https://cloud.githubusercontent.com/assets/24610433/21307918/e22860b4-c5d7-11e6-9628-1fee48213780.jpg)
