### ISSUE TITLE
Class Goals

### ISSUE THREAD

**Issue by kokoruz** [githubschool/open-enrollment-classes-introduction-to-github#198]
## Adding Chicago to the map

Hi everyone! This issue is to track the addition of Chicago to the map, which can be found at:
- Longitude: 41.8781
- Latitude: 87.6298

**Comment by moravecz** [comment]
I will also be adding my name to the Chicago area.

**Comment by moravecz** [comment]
My specific coordinates in the Chicago area:
41.847489, -88.017314

**Comment by leiguoyang** [comment]
@moravecz 👏, i wonder why you two's coordinates differ so much :)

**Comment by moravecz** [comment]
First, kokuroz left out the minus sign on the Longitude. Chicago from the NASA site should be: 41.878114, -87.629798
Second, the Chicago coordinates (with the minus sign on the Longitude) are a bit to the north and east of my western Chicago suburb coordinates.
So they are similar, but a little difference once the minus sign is included.
