### ISSUE TITLE
Hello everybody!

### ISSUE THREAD

**Issue by AbdullahAlshehri** [githubschool/open-enrollment-classes-introduction-to-github#1988]
## Adding Riyadh to the map

Hi everyone! This issue is to track the addition of Riyadh to the map, which can be found at:

- Longitude: 24.778868
- Latitude: 46.679023

**Comment by brianamarie** [comment]
Hi @AbdullahAlshehri! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
