### ISSUE TITLE
new. Hi

### ISSUE THREAD

**Issue by dhaneshe** [githubschool/open-enrollment-classes-introduction-to-github#1991]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hi @dhaneshe! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
