### ISSUE TITLE
test item

### ISSUE THREAD

**Issue by lonmik1** [githubschool/open-enrollment-classes-introduction-to-github#1992]
## Adding Budapest to the map

Hi everyone! This issue is to track the addition of <Budapest > to the map, which can be found at:

- Longitude: <902134>
- Latitude: <128755
[Csak győzzük.docx](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/files/620332/Csak.gyozzuk.docx)
>

**Comment by brianamarie** [comment]
Hi @lonmik1! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
