### ISSUE TITLE
I need help - it won't let me create a branch

### ISSUE THREAD

**Issue by mindworks99** [githubschool/open-enrollment-classes-introduction-to-github#20063]
When i go to the Branch:master dropdown i then enter my username-city but no option to create the branch appears.  Even hitting enter does not allow the branch to be added to the repo.

**Comment by ne0M-678** [comment]
Try clicking on teacherbot's invitation to gain access as a collaborator. :tada:

**Comment by mindworks99** [comment]
I got it.  thank you :-)
