### ISSUE TITLE
what should I do now

### ISSUE THREAD

**Issue by yuriypylypchuk** [githubschool/open-enrollment-classes-introduction-to-github#2010]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by yuriypylypchuk** [comment]
what should i do now

**Comment by yuriypylypchuk** [comment]
I AM LOST

**Comment by yuriypylypchuk** [comment]
Goals: to map my place
![12734202_1106328976068133_2844558527466188729_n](https://cloud.githubusercontent.com/assets/20984067/20761153/b8b4d106-b72a-11e6-9ec7-30b534db8aae.jpg)

**Comment by hectorsector** [comment]
Hi @yuriypylypchuk if you're following *Intro to GitHub* in our [on-demand training](http://services.github.com/on-demand), the next step should be [here](https://services.github.com/on-demand/intro-to-github/04/). Let us know if there's anything else we can do to help.
