### ISSUE TITLE
Adding  my place to the map

### ISSUE THREAD

**Issue by yuriypylypchuk** [githubschool/open-enrollment-classes-introduction-to-github#2020]
## Adding  Birky,Lviv  to the map

Hi everyone! This issue is to track the addition of  Birky,Lviv to the map, which can be found at:

- Longitude:23.923268
- Latitude: 49.915572

**Comment by brianamarie** [comment]
Hi @yuriypylypchuk! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
