### ISSUE TITLE
Please add me to the class.

### ISSUE THREAD

**Issue by DJBlock19** [githubschool/open-enrollment-classes-introduction-to-github#2027]
## Adding Sunnyvale, CA, USA to the map

Hi everyone! This issue is to track the addition of Sunnyvale, CA, USA to the map, which can be found at:

- Longitude: -122.033174
- Latitude: 37.378416

**Comment by dyhun** [comment]
Hi @DJBlock19 if you want to be a collaborator just comment here: #927

**Comment by DJBlock19** [comment]
Comment :)

**Comment by brianamarie** [comment]
Hi @DJBlock19! Make sure you click the link, you'll need to comment somewhere different. Comment on [this thread](#927) so you'll be able to continue with the course: #927

**Comment by dyhun** [comment]
I'm sorry if I was not clear enough

**Comment by DJBlock19** [comment]
I wondered that as well so I went back and looked. You were very clear. I just missed it (plus I was very busy with other things this morning).

Thank you (and Briana) for the guidance.
