### ISSUE TITLE
Please add me

### ISSUE THREAD

**Issue by fvillaamil** [githubschool/open-enrollment-classes-introduction-to-github#2034]
## Adding Miami to the map

Hi everyone! This issue is to track the addition of Miami to the map, which can be found at:

- Longitude: 25°41'14.8"N 
- Latitude: 80°24'53.9"W

**Comment by brianamarie** [comment]
Hi @fvillaamil! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
