### ISSUE TITLE
Add m eto class

### ISSUE THREAD

**Issue by rmohanavelu** [githubschool/open-enrollment-classes-introduction-to-github#2053]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by hectorsector** [comment]
Hi @rmohanavelu!  Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
