### ISSUE TITLE
add  me

### ISSUE THREAD

**Issue by DetectiveKudo** [githubschool/open-enrollment-classes-introduction-to-github#2055]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by DetectiveKudo** [comment]
add  me

**Comment by hectorsector** [comment]
@DetectiveKudo if you'd like to add yourself as a collaborator just drop a comment in issue #927
