### ISSUE TITLE
Maroochydore Australia

### ISSUE THREAD

**Issue by cadchimp** [githubschool/open-enrollment-classes-introduction-to-github#2065]
## Adding Maroochdore Australia to the map

Hi everyone! This issue is to track the addition of Maroochydore Australia to the map, which can be found at:

- Longitude: 26.6500 S
- Latitude: 153.1000 E

**Comment by cadchimp** [comment]
Hello from sunny Queensland.

**Comment by hectorsector** [comment]
Hi @cadchimp!  Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
