### ISSUE TITLE
Luís from Brazil

### ISSUE THREAD

**Issue by luismendes070** [githubschool/open-enrollment-classes-introduction-to-github#2069]
## Adding <Orizona> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <‎-49.286041>
- Latitude: < ‎-16.665136>

**Comment by hectorsector** [comment]
Hi @luismendes070! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
