### ISSUE TITLE
Adding Guangdong,Jiangmen to the map

### ISSUE THREAD

**Issue by caichangzhan** [githubschool/open-enrollment-classes-introduction-to-github#2076]
## Adding <Guangdong,Jiangmen> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <22.579117>
- Latitude: <113.081508>

**Comment by hectorsector** [comment]
Hi @caichangzhan! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927

**Comment by caichangzhan** [comment]
THX bro.@hectorsector
