### ISSUE TITLE
Just learning

### ISSUE THREAD

**Issue by KarenLe** [githubschool/open-enrollment-classes-introduction-to-github#2090]
## Adding Tulsa to the map

Hi everyone! This issue is to track the addition of Tulsa to the map, which can be found at:

- Longitude: <36.1540° N> 
-Latitude;  <95.9928° W>

**Comment by hectorsector** [comment]
Hi @KarenLe! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
