### ISSUE TITLE
Best regadrs from Krakow

### ISSUE THREAD

**Issue by Tomi79** [githubschool/open-enrollment-classes-introduction-to-github#2091]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by Tomi79** [comment]
some github exercises

**Comment by hectorsector** [comment]
Hi @Tomi79! Make sure you comment on [this thread](#927) so you'll be able to continue with the course: #927
