### ISSUE TITLE
Please remove me!!!!!!

### ISSUE THREAD

**Issue by kevinah95** [githubschool/open-enrollment-classes-introduction-to-github#2116]
I don't want to receive more notifications. I don't want to be a collaborator anymore

**Comment by crichID** [comment]
@kevinah95 you can stop getting notifications by changing your `Watching` settings at the top of the repository to `Not Watching` or `Ignoring`!

**Comment by kevinah95** [comment]
![2017-01-10 16_45_20-github](https://cloud.githubusercontent.com/assets/7193395/21828101/4f169f64-d754-11e6-83fc-407c7e44cdfb.png)

Thank you, @crichID but when I remove this repository from my account @githubteacher add me again and I don't want to ignore it, I want to delete it from my repositories, please help me!

**Comment by crichID** [comment]
@kevinah95 did you try setting it to `Not Watching`?

**Comment by kevinah95** [comment]
Yes, I tried but I want to remove this repo of my account :cry:
