### ISSUE TITLE
Adding Brisbane, Australia

### ISSUE THREAD

**Issue by brightlightapps** [githubschool/open-enrollment-classes-introduction-to-github#224]
## Adding Brisbane, Australia to the map

Hi everyone! This issue is to track the addition of Brisbane, Australia to the map, which can be found at:
- Longitude:  153.025124
- Latitude: -27.469771

**Comment by vesuccio** [comment]
## I will be adding my name to the same city

**Comment by juliankelly24** [comment]
I will be adding my name to Brisbane City
