### ISSUE TITLE
Miami

### ISSUE THREAD

**Issue by ace55** [githubschool/open-enrollment-classes-introduction-to-github#231]
## Adding Miami to the map

Hi everyone! This issue is to track the addition of Miami to the map, which can be found at:
- Longitude: -80.156250
- Latitude: 25.681137

**Comment by dannymayorga** [comment]
Hi Everyone, this is to add me (update) for Miami, FL

**Latitude:** 25.761680
**Longitude:** -80.19179

Thanks

**Comment by fvillaamil** [comment]
I'm going to be adding my name to Miami as well
