### ISSUE TITLE
Where am I?

### ISSUE THREAD

**Issue by twgood** [githubschool/open-enrollment-classes-introduction-to-github#2329]
## Adding <great bend, ks> to the map

Hi everyone! This issue is to track the addition of <great bend kansas> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by twgood** [comment]
Looks like fun.

**Comment by brianamarie** [comment]
Hi @twgood! Make sure you comment on #927 to be added as a collaborator. 😄
