### ISSUE TITLE
Hello GitHub~

### ISSUE THREAD

**Issue by Xdudu** [githubschool/open-enrollment-classes-introduction-to-github#2368]
## Adding Beijing to the map

Hi everyone! This issue is to track the addition of Beijing to the map, which can be found at:

- Longitude: 39.9042° N
- Latitude: 116.4074° E

**Comment by yuanjinghua** [comment]
An astronomer from Beijing

**Comment by TineeOne** [comment]
A person living, studying and working in Beijing
