### ISSUE TITLE
Adding Córdoba 

### ISSUE THREAD

**Issue by Mzibecchi** [githubschool/open-enrollment-classes-introduction-to-github#2393]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hello again @Mzibecchi! I'm going to close this issue for now, but please feel free to re-open if you come back to complete the course. 😄
