### ISSUE TITLE
Please Add Me!

### ISSUE THREAD

**Issue by YizB** [githubschool/open-enrollment-classes-introduction-to-github#2394]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hi @YizB! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by brianamarie** [comment]
Hello again @YizB! I'm going to close this issue out for now, but please feel free to re-open when you come back to work on the course. 😄
