### ISSUE TITLE
Hello Github

### ISSUE THREAD

**Issue by asesham** [githubschool/open-enrollment-classes-introduction-to-github#2395]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of Raleigh to the map, which can be found at:

- Longitude: 78.6382° W
- Latitude: 35.7796° N

**Comment by brianamarie** [comment]
Hi @asesham! I'm going to close out this issue since it's been over a week and you are already a collaborator, but please feel free to re-open if needed. 😄
