### ISSUE TITLE
Hello Github

### ISSUE THREAD

**Issue by cchadha** [githubschool/open-enrollment-classes-introduction-to-github#2396]
#2396 Adding <New Brunswick> to the map

Hi everyone! This issue is to track the addition of <New Brunswick> to the map, which can be found at:

- Longitude: <74.4518>
- Latitude: <40.4862>

**Comment by brianamarie** [comment]
Hi @cchadha! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by brianamarie** [comment]
Hello again @cchadha! I'm going to close this issue, but please feel free to reopen when you come back to complete the course. 😄
