### ISSUE TITLE
Hi, please add me. Tx.

### ISSUE THREAD

**Issue by muralidavenport** [githubschool/open-enrollment-classes-introduction-to-github#2403]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hello @muralidavenport! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by brianamarie** [comment]
Hello again @muralidavenport! I'm going to close this issue for now, but please feel free to reopen if needed. 😄
