### ISSUE TITLE
Adding Arlington to the map

### ISSUE THREAD

**Issue by jessmc** [githubschool/open-enrollment-classes-introduction-to-github#241]
Hi everyone! This issue is to track the addition of Arlington, VA to the map, which can be found at:

- Longitude: -77.106770
- Latitude: 38.879970

**Comment by CodeCrafter1** [comment]
How do I stop seeing everyone that is being added...I have tried mute thread

**Comment by jessmc** [comment]
Hi @CodeCrafter1,
I just watched this Github video explaining how to manage your notification settings.
https://youtu.be/ocQldxF7fMY
I think if you change the settings under Watch to 'Not Watching' you will only receive notifications if you are specifically mentioned. Hope this helps.

**Comment by emrichard** [comment]
I will be adding my pin for this city!
