### ISSUE TITLE
add

### ISSUE THREAD

**Issue by LandEarthMonkey** [githubschool/open-enrollment-classes-introduction-to-github#2417]
## Adding <Houston> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 29.872349
- Latitude: -95.453336

**Comment by LandEarthMonkey** [comment]
Hope i did this correctly

**Comment by pruthiviraj71** [comment]
Remove <> these and you are good to go 👍

**Comment by githubteacher** [comment]
:tada: @LandEarthMonkey you are now a repository collaborator. :balloon:
