### ISSUE TITLE
add me!

### ISSUE THREAD

**Issue by jbrow78** [githubschool/open-enrollment-classes-introduction-to-github#2419]
## Adding albany to the map

Hi everyone! This issue is to track the addition of albany to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hi @jbrow78! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by githubteacher** [comment]
:tada: @jbrow78 you are now a repository collaborator. :balloon:
