### ISSUE TITLE
Add me and chicago! 

### ISSUE THREAD

**Issue by JackHowa** [githubschool/open-enrollment-classes-introduction-to-github#2423]
Adding Chicago to the map! 

Hi everyone! This issue is to track the addition of Chicago to the map, which can be found at:

- Longitude: 41.8781
- Latitude: 87.6298

41.8781° N, 87.6298° W

**Comment by brianamarie** [comment]
Hi @JackHowa! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by githubteacher** [comment]
:tada: @JackHowa you are now a repository collaborator. :balloon:
