### ISSUE TITLE
London

### ISSUE THREAD

**Issue by Dave66allen66** [githubschool/open-enrollment-classes-introduction-to-github#2432]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of London to the map, which can be found at:

-Longtitude: 51.507905, 
-Latitude: -0.127886

**Comment by Dave66allen66** [comment]
First time ever that i have been here. exploring. :)

**Comment by brianamarie** [comment]
Hi @Dave66allen66! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by Dave66allen66** [comment]
Hi @brianamarie. Nice one for the tip. I will be with you soon. Just getting my head around it all just now :-)
