### ISSUE TITLE
Hey friends...i am here.

### ISSUE THREAD

**Issue by ddepablos** [githubschool/open-enrollment-classes-introduction-to-github#2436]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by ddepablos** [comment]
Add me.

**Comment by brianamarie** [comment]
Hi @ddepablos! Make sure you comment on #927 to be added as a collaborator.

**Comment by githubteacher** [comment]
:tada: @ddepablos you are now a repository collaborator. :balloon:
