### ISSUE TITLE
tnemmoC

### ISSUE THREAD

**Issue by nmohrlock** [githubschool/open-enrollment-classes-introduction-to-github#2453]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 32
- Latitude: 117

**Comment by brianamarie** [comment]
Hi @nmohrlock! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by githubteacher** [comment]
:tada: @nmohrlock you are now a repository collaborator. :balloon:
