### ISSUE TITLE
NOVICE LEARNING

### ISSUE THREAD

**Issue by georgegabbert** [githubschool/open-enrollment-classes-introduction-to-github#2462]
George Gabbert, Pueblo West, CO  81007

WOW - this is truly rocket science!!!

**Comment by brianamarie** [comment]
Hi @georgegabbert! Make sure you comment on issue #927 so you'll be added as a collaborator!  😄

**Comment by githubteacher** [comment]
:tada: @georgegabbert you are now a repository collaborator. :balloon:
