### ISSUE TITLE
I love gitHub <3

### ISSUE THREAD

**Issue by Golden-Shadow** [githubschool/open-enrollment-classes-introduction-to-github#2467]
## Adding Cairo to the map

Hi everyone! This issue is to track the addition of cairo to the map, which can be found at:

- Longitude: 30.0444° N
- Latitude: 31.2357° E

**Comment by brianamarie** [comment]
Hi @Golden-Shadow!  Make sure you comment on issue #927 so you'll be added as a collaborator! 😄

**Comment by Golden-Shadow** [comment]
Thank you 😄
