### ISSUE TITLE
Adding Lima (Perú) to the map

### ISSUE THREAD

**Issue by FernandoGV667** [githubschool/open-enrollment-classes-introduction-to-github#250]
## Adding Lima to the map

Hi everyone! This issue is to track the addition of Lima (Peru) to the map, which can be found at:
- Longitude: -77.031235
- Latitude: -12.045415
  ![plaza-mayro620_1853121b](https://cloud.githubusercontent.com/assets/18159869/17639507/8b533a9a-60b8-11e6-9eea-a619390ffcf7.jpg)

**Comment by daleonpz** [comment]
I will add my name also
