### ISSUE TITLE
Iowa City

### ISSUE THREAD

**Issue by Landenyr** [githubschool/open-enrollment-classes-introduction-to-github#254]
## Adding Iowa City to the map

Hi everyone! This issue is to track the addition of Iowa City to the map, which can be found at:

- Longitude: -91.530168
- Latitude: 41.661128

**Comment by Amitabh-12** [comment]
{ "type": "Feature", "geometry": {"type": "Point", "coordinates": [-91.530168, 41.661128]}, "properties": {"username": "Amitabh-12"} }
