### ISSUE TITLE
Noida(India)

### ISSUE THREAD

**Issue by Amitabh-12** [githubschool/open-enrollment-classes-introduction-to-github#256]
## Adding Noida to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: 77° 19.2'
- Latitude: 28° 34.2'

**Comment by mirage2012** [comment]
Adding Mirage into this.

**Comment by dg256** [comment]
## I will be adding my name to this city

**Comment by sumitvgithub** [comment]
I'll be adding my name too!
