### ISSUE TITLE
add me

### ISSUE THREAD

**Issue by baidaadarsh** [githubschool/open-enrollment-classes-introduction-to-github#2576]
Please add me as a collaborator

**Comment by brianamarie** [comment]
Hi @baidaadarsh! Make sure you comment on #927 to be added as a collaborator. 😄

**Comment by brianamarie** [comment]
Hi @baidaadarsh - I closed this issue since you have opened a new one. You will need to click on [this link](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/927) and scroll all the way to the bottom and comment there.
