### ISSUE TITLE
Adding Greensboro, NC

### ISSUE THREAD

**Issue by marcf08** [githubschool/open-enrollment-classes-introduction-to-github#261]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 79.7920° W
- Latitude: 36.0726° N

**Comment by crichID** [comment]
@marcf08 it is exciting to see another NC-ian in this repo. :wave: welcome! Let me know if you need any assistance but it looks like you have this under control!
