### ISSUE TITLE
Add me 

### ISSUE THREAD

**Issue by msharsha555** [githubschool/open-enrollment-classes-introduction-to-github#2640]
## Adding Roorkee to the map

Hi everyone! This issue is to track the addition of Roorkee to the map, which can be found at:

- Longitude: 77.888000
- Latitude: 29.854263

**Comment by brianamarie** [comment]
Hi @msharsha555!  Make sure you comment on #927 so that you can be added as a collaborator! 😄

**Comment by githubteacher** [comment]
:tada: @msharsha555 you are now a repository collaborator. :balloon:
