### ISSUE TITLE
Washington D.C.

### ISSUE THREAD

**Issue by MelodiesAboutMe** [githubschool/open-enrollment-classes-introduction-to-github#266]
## Adding DC to the map

Hi everyone! This issue is to track the addition of DC to the map, which can be found at:
- Longitude [-77.036871]
- Latitude [38.907192]

**Comment by steve-12XU** [comment]
Hi, I'll be adding my name to the pin for this city.

**Comment by itestinproduction** [comment]
Hi, I'll be adding my name to the pin for this city.

**Comment by kjkholman** [comment]
Adding my name to the pin for DC!
