### ISSUE TITLE
Adding Portland, OR to the map

### ISSUE THREAD

**Issue by patriciaa** [githubschool/open-enrollment-classes-introduction-to-github#27]
## Adding Portland to the map

Hi everyone! This issue is to track the addition of Portland to the map, which can be found at:

- Longitude: 122.6765° W
- Latitude: 45.5231° N

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new pull request. 😄 Thank you and happy coding! :octocat:
