### ISSUE TITLE
Adding Austin, Tx to the map

### ISSUE THREAD

**Issue by bazfire** [githubschool/open-enrollment-classes-introduction-to-github#273]
## Adding Austin to the map

Hi everyone! This issue is to track the addition of Austin to the map, which can be found at:
- Longitude: -97.743061 
- Latitude: 30.267153

**Comment by GusCastellanos** [comment]
Adding my name (Gus) to the Austin pin.

**Comment by GusCastellanos** [comment]
Closing after completing pull request #589

**Comment by brickjones** [comment]
adding to pin

**Comment by lizcobbe** [comment]
Adding to pin.

**Comment by rareed0219** [comment]
Adding to pin

**Comment by enxcreative** [comment]
Adding to pin
