### ISSUE TITLE
Adding Toronto

### ISSUE THREAD

**Issue by harrisonkimca** [githubschool/open-enrollment-classes-introduction-to-github#274]
## Adding Toronto to the map

Hi everyone! This issue is to track the addition of Toronto to the map, which can be found at:
- Longitude: 43.6532 N
- Latitude: 79.3832 W

**Comment by aristiz6** [comment]
Hello!
I'll be adding my name to this location.

**Comment by MTaylr** [comment]
I will add my name too.

**Comment by samkh918** [comment]
I am adding my name to this issue.

**Comment by Nantard** [comment]
i've added my name as well.

**Comment by Nasreen123** [comment]
Hello!
