### ISSUE TITLE
Add me

### ISSUE THREAD

**Issue by Shafiehashi** [githubschool/open-enrollment-classes-introduction-to-github#2779]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

test

**Comment by brianamarie** [comment]
Hi @Shafiehashi!  Make sure you comment on #927 so that you can be added as a collaborator! 😄

**Comment by githubteacher** [comment]
:tada: @Shafiehashi you are now a repository collaborator. :balloon:
