### ISSUE TITLE
Start Here

### ISSUE THREAD

**Issue by salimdeveloper** [githubschool/open-enrollment-classes-introduction-to-github#2815]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by Muhayshi** [comment]
..

**Comment by xGriffx** [comment]
Hello!

**Comment by brianamarie** [comment]
Hi @salimdeveloper!  Make sure you comment on #927 so that you can be added as a collaborator! 😄

**Comment by githubteacher** [comment]
:tada: @salimdeveloper you are now a repository collaborator. :balloon:

**Comment by alandr0id** [comment]
...

**Comment by NasserDos** [comment]
...
