### ISSUE TITLE
Start-here 2

### ISSUE THREAD

**Issue by mingtam** [githubschool/open-enrollment-classes-introduction-to-github#2890]
##` Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by brianamarie** [comment]
Hi @mingtam!  Make sure you comment on #927 so that you can be added as a collaborator! 😄

**Comment by mingtam** [comment]
Thanks! It is okay now ☺️
