### ISSUE TITLE
Adding Boston to the map 

### ISSUE THREAD

**Issue by KristinaMarie** [githubschool/open-enrollment-classes-introduction-to-github#29]
## Adding Boston to the map

Hi everyone! This issue is to track the addition of Boston to the map, which can be found at:

- Longitude: -71.054485
- Latitude: 42.364680

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new pull request. 😄 Thank you and happy coding! :octocat:

**Comment by susannahfisher** [comment]
I'm adding my name to the pin for this city. 👍

**Comment by ladymoxie** [comment]
I will be adding my name to the pin for this city.

**Comment by raunaqmitra** [comment]
I'll be adding my name to the pin for this city as well!

**Comment by raunaqmitra** [comment]
#787

**Comment by raunaqmitra** [comment]
#787,  I'd like to add my name to the pin for Boston as well!
