### ISSUE TITLE
Add Bury to the map

### ISSUE THREAD

**Issue by TannyWeb** [githubschool/open-enrollment-classes-introduction-to-github#2914]
## Adding Bury to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: -2.292061
- Latitude: 53.593342

**Comment by brianamarie** [comment]
Hi @TannyWeb!  Make sure you comment on #927 so that you can be added as a collaborator! 😄

**Comment by githubteacher** [comment]
:tada: @TannyWeb you are now a repository collaborator. :balloon:
