### ISSUE TITLE
New York City, NY

### ISSUE THREAD

**Issue by Purphict** [githubschool/open-enrollment-classes-introduction-to-github#293]
## Adding New York to the map

Hi everyone! This issue is to track the addition of New York to the map, which can be found at:
- Longitude: 74.005941
- Latitude: 40.712784

**Comment by Jasonramirez00** [comment]
I will be adding jasonramirez00 to this pin

**Comment by Juanita563** [comment]
I will be adding Juanita563 to the NYC pin!

**Comment by xynazog** [comment]
I will be adding @xynazog to the NYC pin!

**Comment by tani11** [comment]
I will be adding @tani11 to the NYC pin! 
![e517c2cf-fa50-4be3-a9ed-866cc874c211](https://cloud.githubusercontent.com/assets/22061690/18763173/2a28a196-80da-11e6-8cb5-4246e99a8c5a.jpg)

**Comment by JD5623** [comment]
I'll add JD5623 to the NYC pin

**Comment by zhen-meister** [comment]
Adding zhen-meister to the NYC pin.

**Comment by cixtor** [comment]
[]()
