### ISSUE TITLE
Error Travis Build

### ISSUE THREAD

**Issue by LivingProgram** [githubschool/open-enrollment-classes-introduction-to-github#2945]
@githubteacher 
I found out there are typically 2 errors for the travis build (where your checks fail).
1. There are leading spaces in all the lines of your file, because when you copy it from the tutorial you get something like this:
```
 ---
 githubHandle: YOUR-USERNAME
 latitude: YOUR_LATITUDE
 longitude: YOUR_LONGITUDE
 ---
```
notice the leading spaces? It should be something like this:
```
---
githubHandle: YOUR-USERNAME
latitude: YOUR_LATITUDE
longitude: YOUR_LONGITUDE
---
```
2. Another error is having spaces after your lines, something that would error would be something like this:
```
---
githubHandle: YOUR-USERNAME
latitude: YOUR_LATITUDE 
longitude: YOUR_LONGITUDE
---
```

**Comment by LivingProgram** [comment]
@githubteacher 
So it would be best if the tutorial included some sort of debugging section with the most common errors people have, this way people following the tutorial can move through it easily and bug free!

**Comment by brianamarie** [comment]
Thank you @LivingProgram! I agree completely. 

cc @beardofedu

**Comment by LivingProgram** [comment]
@brianamarie @beardofedu 
Great, thanks for the amazing tutorial, I'm looking forward to future ones, **Go Github**!

(thank you for the fast feedback as well!)

**Comment by LivingProgram** [comment]
If you are interested here are two examples of the type of error i was referring to:
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2970
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/2948

**Comment by crichID** [comment]
@LivingProgram thank you so much for taking the time to open an issue and provide detailed troubleshooting steps. This issue has been fixed in: https://github.com/github/training-kit/pull/451 so I am going to go ahead and close this issue! :sparkles: :heart: :sparkles:

**Comment by lydita** [comment]
agree totaly
