### ISSUE TITLE
Kyle

### ISSUE THREAD

**Issue by kmanoleff** [githubschool/open-enrollment-classes-introduction-to-github#2950]
## Adding Hampton to the map

Hi everyone! This issue is to track the addition of Hampton to the map

**Comment by brianamarie** [comment]
Hi @kmanoleff!  Make sure you comment on #927 so that you can be added as a collaborator! 😄

**Comment by dania-mohammedelhassan** [comment]
what to do ?

**Comment by githubteacher** [comment]
:tada: @kmanoleff you are now a repository collaborator. :balloon:
