### ISSUE TITLE
Melbourne

### ISSUE THREAD

**Issue by raish22** [githubschool/open-enrollment-classes-introduction-to-github#299]
## Adding Melbourne to the map

Hi everyone! This issue is to track the addition of Melbourne to the map, which can be found at:

- Longitude: 144.963058
- Latitude: -37.813628

**Comment by mardi-BOM** [comment]
Hi, I'm in Melbourne (Australia) so opening this issue.
Longitude: 144.963058
Latitude: -37.813628
