### ISSUE TITLE
Adding Waseem

### ISSUE THREAD

**Issue by alphawaseem** [githubschool/open-enrollment-classes-introduction-to-github#2990]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by Draco-D-Dragonslayer** [comment]
which location you want to track
you can use this site to find your location
https://mynasadata.larc.nasa.gov/latitudelongitude-finder/

**Comment by Draco-D-Dragonslayer** [comment]
Youth4workHi ,Aman Bhashkar, your contact & who has this profileSuggests you to try a quick, 5 min, Online Skill test to know your own skillshttps://www.youth4work.com/onlinetalenttestIt’s a fun test that helps you know where you stand for your skills across the globe. It also helps you get professional opportunities.Regards,Youth4workUnsubscribe
