### ISSUE TITLE
Adding Exeter to the map

### ISSUE THREAD

**Issue by NickTikhonov** [githubschool/open-enrollment-classes-introduction-to-github#30]
## Adding Exeter to the map

Hi everyone! This issue is to track the addition of Exeter to the map, which can be found at:

- Longitude: -3.533899
- Latitude: 50.718412

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new pull request. 😄 Thank you and happy coding! :octocat:
