### ISSUE TITLE
Minsk, Belarus to the map

### ISSUE THREAD

**Issue by tyzia** [githubschool/open-enrollment-classes-introduction-to-github#302]
## Let's add Minsk, Belarus to the map

Hi everyone! This issue is to track the addition of **MINSK** to the map, details are as follows:

- Longitude: 27.561524
- Latitude: 53.904540

Any Minskers are welcome to comment!

**Comment by pkviatko** [comment]
Hi!
I'm going to add my name to Minsk as well, so I'll reopen it.
