### ISSUE TITLE
trying to enroll

### ISSUE THREAD

**Issue by JHerrickII** [githubschool/open-enrollment-classes-introduction-to-github#3037]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by hectorsector** [comment]
👋 @JHerrickII you should be added now

**Comment by githubteacher** [comment]
:tada: @JHerrickII you are now a repository collaborator. :balloon:
