### ISSUE TITLE
Adding San Jose to the map

### ISSUE THREAD

**Issue by brentjo** [githubschool/open-enrollment-classes-introduction-to-github#32]
## Adding San Jose to the map

Hi everyone! This issue is to track the addition of San Jose to the map, which can be found at:

- Longitude: -121.886329
- Latitude: 37.338208

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:

**Comment by nancytt** [comment]
@brianamarie 

Whoops! Should I have not reopened this issue? Just wanted to re-add San Jose to the map. 

[-121.919338, 37.317863]
