### ISSUE TITLE
please add me -Sylhet, Bangladesh

### ISSUE THREAD

**Issue by Afzal92** [githubschool/open-enrollment-classes-introduction-to-github#3244]
Hello :wave:! Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Afzal92 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
