### ISSUE TITLE
Please add me - Hong Kong HKG

### ISSUE THREAD

**Issue by yogimahtani** [githubschool/open-enrollment-classes-introduction-to-github#3290]
Hello :wave:! Please add me as a collaborator to this repo. 

##Adding Hong Kong to the map.  

Hi Everyone! This issue is to track Hong Kong to the map, which can be found at:

- Longitude: 22.3964° N . 
- Latitude:  114.1095° E

**Comment by githubteacher** [comment]
:tada: @yogimahtani you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
