### ISSUE TITLE
please add me - Calgary,Canada

### ISSUE THREAD

**Issue by RobinxiangbinNie** [githubschool/open-enrollment-classes-introduction-to-github#3292]
Hello :wave:! Please add me as a collaborator to this repo. 
Please add me to the map with the following coordinates
Latitude: 51.124823
Longitude: -114.156383

**Comment by githubteacher** [comment]
:tada: @RobinxiangbinNie you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
