### ISSUE TITLE
Please add me -Lausanne, Switzerland

### ISSUE THREAD

**Issue by khoramshahi** [githubschool/open-enrollment-classes-introduction-to-github#3297]
Hello :wave:! Please add me as a collaborator to this repo. 

- longitude: 46.5207596
- latitude: 6.5669867

**Comment by githubteacher** [comment]
:tada: @khoramshahi you are now a repository collaborator. :balloon:

**Comment by jrkwon** [comment]
:octocat:

**Comment by MOHMMEDASIF** [comment]
hello add me as a collaborator to this repository

**Comment by MOHMMEDASIF** [comment]
Hello!  Please add me as a collaborator to this repo.


Latitude:-13.038278
Longitude:-77.607823

**Comment by Geetus** [comment]
Hi, can i join as collaborator, many thanks

**Comment by Mentoronto** [comment]
Hello there

**Comment by wadelittleton** [comment]
Test

**Comment by alkeshab** [comment]
add me

**Comment by zalew16** [comment]
Test

**Comment by apoorvcode** [comment]
test

**Comment by azvenigo** [comment]
ditto

**Comment by hectorsector** [comment]
@T4selogistics Please refrain from closing issues and Pull Requests owned by someone else. We'd like to ensure every student has the satisfaction of merging their own branch, or closing it themselves.

@azvenigo @wadelittleton @Mentoronto @jrkwon if you're still looking to be added as your own collaborator, just open up a new issue and @githubteacher will add you!
