### ISSUE TITLE
Please add me - Klaeng, Rayong

### ISSUE THREAD

**Issue by awr-reb** [githubschool/open-enrollment-classes-introduction-to-github#3329]
Hello! :wave: Please add me as a collaborator to this repo. 

## Adding Klaeng to the map.

- Longitude:  101.649096
- Latitude:  12.779740

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by awr-reb** [comment]
Thank you! _________________________
Mobile 085-436-4077
+66 85-436-4077
