### ISSUE TITLE
Please add me - Singapore

### ISSUE THREAD

**Issue by vanessangwl** [githubschool/open-enrollment-classes-introduction-to-github#3339]
Hello! :wave: Please add me as a collaborator to this repo. 

This issue is to track Singapore on the map, which can be found at:

Longitude: 103.8364239
Latitude: 1.274029

**Comment by githubteacher** [comment]
:tada: @vanessangwl you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
