### ISSUE TITLE
add west palm beach to map

### ISSUE THREAD

**Issue by alexaheart** [githubschool/open-enrollment-classes-introduction-to-github#334]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by alexaheart** [comment]
Longitude:-80.053374600
Latitude:26.715342400

**Comment by stlpatd** [comment]
:+1:

**Comment by Mikedaris94** [comment]
!!

**Comment by Mikedaris94** [comment]
i'm mike i will be adding my name to the pin
