### ISSUE TITLE
Please add me - Champaign

### ISSUE THREAD

**Issue by chezel** [githubschool/open-enrollment-classes-introduction-to-github#3343]
Hello! :wave: Please add me as a collaborator to this repo. 

Longitude: -88.2433333
Latitude: 40.1163889

**Comment by githubteacher** [comment]
:tada: @chezel you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
