### ISSUE TITLE
Please add me-Placerville CA

### ISSUE THREAD

**Issue by heidi20** [githubschool/open-enrollment-classes-introduction-to-github#3345]
Hello! :wave: Please add me as a collaborator to this repo. 
I am in Placerville California

longitude:-120.744546
latitude:38.805216

**Comment by githubteacher** [comment]
:tada: @heidi20 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
