### ISSUE TITLE
Please add me to the project.

### ISSUE THREAD

**Issue by Daniel54** [githubschool/open-enrollment-classes-introduction-to-github#3369]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Daniel54 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
