### ISSUE TITLE
Hello, please add me - Qro, Mexico

### ISSUE THREAD

**Issue by joesuaperz** [githubschool/open-enrollment-classes-introduction-to-github#3380]
Hello! :wave: Please add me as a collaborator to this repo. 

## Adding Queretaro, QRO, Mexico to the map

Hi everyone, this issue is to track the addition of Queretaro, Mexico, to the map which can be found at:

Longitude >-100.389888
Latitude   > 20.588793

**Comment by githubteacher** [comment]
:tada: @joesuaperz you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
