### ISSUE TITLE
Please add me - Roy, UT

### ISSUE THREAD

**Issue by Blue-Petrichor** [githubschool/open-enrollment-classes-introduction-to-github#3382]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Roy to the map

Hi everyone! This issue is to track the addition of Roy to the map, which can be found at:

- Longitude: 41.1616° N
- Latitude: 112.0263° W

**Comment by githubteacher** [comment]
:tada: @Blue-Petrichor you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
