### ISSUE TITLE
Please add me - Stuttgart, Germany

### ISSUE THREAD

**Issue by yganzel** [githubschool/open-enrollment-classes-introduction-to-github#3390]
Hello! :wave: Please add me as a collaborator to this repo. 

Adding Stuttgart, Germany to the map

Hi everyone, this issue is to track the addition of Stuttgart, Germany, to the map which can be found at:

-Longitude: 48.775846°
-Latitude: 9.182932°

**Comment by githubteacher** [comment]
:tada: @yganzel you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
