### ISSUE TITLE
Subscribe

### ISSUE THREAD

**Issue by awr-reb** [githubschool/open-enrollment-classes-introduction-to-github#3391]
Hello! :wave: Please add me as a collaborator to this repo. 

Adding Klaeng, Rayong (Thailand) to the map

Hi everyone, this issue is to track the addition of Klaeng, Rayong, to the map which can be found at:

-Longitude: 101.649096
-Latitude: 12.779740

**Comment by awr-reb** [comment]
Subscribe and add to the map.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
