### ISSUE TITLE
please add me - wwx

### ISSUE THREAD

**Issue by wenxingwang** [githubschool/open-enrollment-classes-introduction-to-github#3399]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @wenxingwang you are now a repository collaborator. :balloon:

**Comment by wenxingwang** [comment]
thank you!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
