### ISSUE TITLE
Adding London to the map 🇬🇧

### ISSUE THREAD

**Issue by FemiAw** [githubschool/open-enrollment-classes-introduction-to-github#34]
## Adding London to the map

Hi everyone! This issue is to track the addition of London to the map, which can be found at:

- Longitude: -0.127758
- Latitude: 51.507351

**Comment by SimonLarkin1** [comment]
Hi,  Will be checking the co-ordinates for city of London

**Comment by 12345swo** [comment]
Hi.  I'll be adding my name to the pin for **London**.

**Comment by 12345swo** [comment]
Correcting an issue with 12345swo pin
