### ISSUE TITLE
enrolling

### ISSUE THREAD

**Issue by NeuroApper** [githubschool/open-enrollment-classes-introduction-to-github#3403]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @NeuroApper you are now a repository collaborator. :balloon:

**Comment by NeuroApper** [comment]
Great! Where do I go now?? :)

**Comment by crichID** [comment]
@NeuroApper just keep going through the steps in the course! If you get stuck, there is also a quick video that shows all of the steps: https://youtu.be/kocHKaHtZCc

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
