### ISSUE TITLE
Please Add Me -- Fayetteville, NC

### ISSUE THREAD

**Issue by prollycause** [githubschool/open-enrollment-classes-introduction-to-github#3428]
Hello! :wave: Please add me as a collaborator to this repo. 

## Adding Grays Creek NC to the map.

- Longitude: 34.861187
- Latitude:  -78.849751

**Comment by githubteacher** [comment]
:tada: @prollycause you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
