### ISSUE TITLE
Please add me - Ogden, UT

### ISSUE THREAD

**Issue by raulriverapuig** [githubschool/open-enrollment-classes-introduction-to-github#3431]
## Adding Ogden to them map
Hi everyone! 
-Longitude:-112.1316
-Latitude:41.2471

**Comment by githubteacher** [comment]
:tada: @raulriverapuig you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
