### ISSUE TITLE
Please Add Me!

### ISSUE THREAD

**Issue by Flinoge** [githubschool/open-enrollment-classes-introduction-to-github#3437]
Hello! Please add me!
Latitude: 41.192628
Longitude -111.944901

**Comment by githubteacher** [comment]
:tada: @Flinoge you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
