### ISSUE TITLE
Add STL pin

### ISSUE THREAD

**Issue by stlpatd** [githubschool/open-enrollment-classes-introduction-to-github#344]
## Adding St Louis, MO to the map

Hi everyone! This issue is to track the addition of St Louis MO to the map, which can be found at:
- Longitude: -90.347905
- Latitude: 38.562697
  ![image](https://cloud.githubusercontent.com/assets/19420494/17819669/a411922e-660e-11e6-87f6-bd6a393edd50.png)

**Comment by stlpatd** [comment]
:ship:

**Comment by militoj** [comment]
Hello! I'm going to add my name to the pin for St. Louis!

**Comment by BrianCarlin** [comment]
I'm going to add my name to St. Louis, too!

**Comment by reykgue** [comment]
I'm going to add my name to the pin for St. Louis =)
