### ISSUE TITLE
Please add me - China Shi

### ISSUE THREAD

**Issue by MrBearWithHisSword** [githubschool/open-enrollment-classes-introduction-to-github#3461]
Hello! :wave: Please add me as a collaborator to this repo. 
I'm new to this. Hope everyone happy and i could learn from all of u.

**Comment by githubteacher** [comment]
:tada: @MrBearWithHisSword you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
