### ISSUE TITLE
Please add me - Leeuwarden, Netherlands

### ISSUE THREAD

**Issue by ReneVader** [githubschool/open-enrollment-classes-introduction-to-github#3472]
## Adding Leeuwarden to the map

- latitude: 53.201233
- longitude: 5.799913

**Comment by githubteacher** [comment]
:tada: @ReneVader you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
