### ISSUE TITLE
Please add me - Washington, DC

### ISSUE THREAD

**Issue by semperstew** [githubschool/open-enrollment-classes-introduction-to-github#3490]
Hello! :wave: Please add me as a collaborator to this repo. 
Lat: 38.907671
Lon: -77.071575

**Comment by githubteacher** [comment]
:tada: @semperstew you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
