### ISSUE TITLE
Please add me in - Hong Kong, HK

### ISSUE THREAD

**Issue by ryancheng** [githubschool/open-enrollment-classes-introduction-to-github#3495]
Hello! :wave: Please add me as a collaborator to this repo. 

You're in Hong Kong
Your Latitude: 22.3333
Your Longitude: 114.25

**Comment by githubteacher** [comment]
:tada: @ryancheng you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
