### ISSUE TITLE
Please add me - Winnipeg, MB

### ISSUE THREAD

**Issue by buihh** [githubschool/open-enrollment-classes-introduction-to-github#3508]
## Adding Winnipeg to the map

Hello! :wave: Please add me as a collaborator to this repo. 

- Longtitude: -97.138374
- Latitude: 49.895136

**Comment by githubteacher** [comment]
:tada: @buihh you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
