### ISSUE TITLE
add-me-virginia,manassas

### ISSUE THREAD

**Issue by youngcoder101** [githubschool/open-enrollment-classes-introduction-to-github#3509]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @youngcoder101 you are now a repository collaborator. :balloon:

**Comment by youngcoder101** [comment]
@githubteacher  thanks

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
