### ISSUE TITLE
Please add me (Bangkok, Thailand)

### ISSUE THREAD

**Issue by Artavans** [githubschool/open-enrollment-classes-introduction-to-github#3533]
Please add me to the map

- Latitude - 13.756331
- Longitude -100.501765

**Comment by githubteacher** [comment]
:tada: @Artavans you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
