### ISSUE TITLE
Please add me: Switzerland

### ISSUE THREAD

**Issue by JulesLD** [githubschool/open-enrollment-classes-introduction-to-github#3537]
Hello! :wave: Please add me as a collaborator to this repo. 

Long: no idea 
Lat: no idea

**Comment by githubteacher** [comment]
:tada: @JulesLD you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
