### ISSUE TITLE
Please add me: Madrid, Madrid

### ISSUE THREAD

**Issue by andsb** [githubschool/open-enrollment-classes-introduction-to-github#3538]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Madrid to the map
Latitude: 40.404101
Longitude: -3.693541

**Comment by githubteacher** [comment]
:tada: @andsb you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
