### ISSUE TITLE
Please add me - Lagos, Nigeria

### ISSUE THREAD

**Issue by xabury** [githubschool/open-enrollment-classes-introduction-to-github#3539]
Hello! :wave: Please add me as a collaborator to this repo. 

This issue is to add Lagos, Nigeria to the map

**Comment by githubteacher** [comment]
:tada: @xabury you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
