### ISSUE TITLE
Please add me, Almere  Netherlands

### ISSUE THREAD

**Issue by ytra** [githubschool/open-enrollment-classes-introduction-to-github#3545]
Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude: 52.395
- Latitude: 5.276

**Comment by githubteacher** [comment]
:tada: @ytra you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
