### ISSUE TITLE
Please add me- Abilene, Tx

### ISSUE THREAD

**Issue by hermosilloem** [githubschool/open-enrollment-classes-introduction-to-github#3552]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @hermosilloem you are now a repository collaborator. :balloon:

**Comment by hermosilloem** [comment]
Thank you but I have a question what is this for?

**Comment by crichID** [comment]
@hermosilloem this process is used to add you as a collaborator to this issue. When you are a collaborator, you have the ability to create branches and make changes to the repository. Before you are a collaborator, you can only view the files and create issues or comment on issues and pull requests!
