### ISSUE TITLE
Please add me - Cambridge, UK

### ISSUE THREAD

**Issue by mrzecz823** [githubschool/open-enrollment-classes-introduction-to-github#3557]
## Adding Cambridge to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 0.121817
- Latitude: 52.205337

**Comment by githubteacher** [comment]
:tada: @mrzecz823 you are now a repository collaborator. :balloon:

**Comment by mrzecz823** [comment]
:octocat :
