### ISSUE TITLE
Please add me - Dublin, Irl

### ISSUE THREAD

**Issue by SgtCompile** [githubschool/open-enrollment-classes-introduction-to-github#3562]
Hello! :wave: Please add me as a collaborator to this repo. 

-Longitude: 53.2910580
-Latitude: -6.3629940

**Comment by githubteacher** [comment]
:tada: @SgtCompile you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
