### ISSUE TITLE
Add me to the Map!

### ISSUE THREAD

**Issue by robertlux** [githubschool/open-enrollment-classes-introduction-to-github#3565]
Hello! :wave: Please add me as a collaborator to this repo. 

Longitude: 8.403653
Latitude: 49.006890

**Comment by githubteacher** [comment]
:tada: @robertlux you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
