### ISSUE TITLE
ScanPark - Webbasierte Datenbankanwendung

### ISSUE THREAD

**Issue by AmazingSP** [githubschool/open-enrollment-classes-introduction-to-github#3573]
Hier ist das Repository der Gruppe 4 

Mitglieder: 

Julian Hügel
Arthur Böhm
Michael Keller

**Comment by githubteacher** [comment]
:tada: @AmazingSP you are now a repository collaborator. :balloon:

**Comment by AmazingSP** [comment]
Hier unser erstes Dokument. Es beinhaltet das Thema, die Mitglieder der Gruppe und eine Kurzbeschreibung des Projektes.

[Thema_Kurzbeschreibung.docx](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/files/758240/Thema_Kurzbeschreibung.docx)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
