### ISSUE TITLE
Please add me - Vilnius

### ISSUE THREAD

**Issue by ieva-meskene** [githubschool/open-enrollment-classes-introduction-to-github#3580]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @ieva-meskene you are now a repository collaborator. :balloon:

**Comment by ieva-meskene** [comment]
Test learning

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
