### ISSUE TITLE
Please add me - PDX

### ISSUE THREAD

**Issue by johncooperpdx** [githubschool/open-enrollment-classes-introduction-to-github#3585]
## Adding Portland, OR (aka PDX) to the map.

Hi, everyone. This issue is to add PDX to the map, which can be found at:

- Longitude: -122.676482
- Latitude: 45.523062

**Comment by githubteacher** [comment]
:tada: @johncooperpdx you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
