### ISSUE TITLE
we dont have enough space in room

### ISSUE THREAD

**Issue by saligramdalchand** [githubschool/open-enrollment-classes-introduction-to-github#3613]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @saligramdalchand you are now a repository collaborator. :balloon:

**Comment by saligramdalchand** [comment]
is it possible for the new space to use as space

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
