### ISSUE TITLE
Please add me - Banglore

### ISSUE THREAD

**Issue by Deep2322** [githubschool/open-enrollment-classes-introduction-to-github#3622]
## Adding Banglore to Map

-Longitude: 77.594563
-Latitude: 12.971599

**Comment by githubteacher** [comment]
:tada: @Deep2322 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
