### ISSUE TITLE
Collaborator

### ISSUE THREAD

**Issue by stanley-godfrey** [githubschool/open-enrollment-classes-introduction-to-github#3625]
Hi, please could I be removed as a collaborator from the repository?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
