### ISSUE TITLE
Hello! Please add me, too!

### ISSUE THREAD

**Issue by hellocam** [githubschool/open-enrollment-classes-introduction-to-github#3648]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @hellocam you are now a repository collaborator. :balloon:

**Comment by hellocam** [comment]
#Adding Toronto on the map

Hi everyone, this is to track the addition of Toronto to the map, which can be found at: 

Longitude: -79.179947
Latitude: 43.820028
