### ISSUE TITLE
Please add me - New Plymouth

### ISSUE THREAD

**Issue by Geetus** [githubschool/open-enrollment-classes-introduction-to-github#3653]
Latitude: -39.055625
Longitude: 174.075228

**Comment by githubteacher** [comment]
:tada: @Geetus you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
