### ISSUE TITLE
Please add me - Porto, PT

### ISSUE THREAD

**Issue by azarew** [githubschool/open-enrollment-classes-introduction-to-github#3656]
Hello! :wave: Please add me as a collaborator to this repo. 

Porto

Latitude
41.186024
Longitude
-8.636886

**Comment by githubteacher** [comment]
:tada: @azarew you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
