### ISSUE TITLE
please add me ogden ut

### ISSUE THREAD

**Issue by christopherbowen** [githubschool/open-enrollment-classes-introduction-to-github#3670]
Hello! this is to add ogden to the map 
longitude:  41.2230°
latitude: 111.9738°

**Comment by githubteacher** [comment]
:tada: @christopherbowen you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
