### ISSUE TITLE
Hi, please add me on - Oak Park, IL

### ISSUE THREAD

**Issue by abwst12** [githubschool/open-enrollment-classes-introduction-to-github#3676]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @abwst12 you are now a repository collaborator. :balloon:

**Comment by abwst12** [comment]
So, this is an actual class on how to use GitHub, right, or am I in the wrong place for that?

**Comment by Geoxy94** [comment]
@abwst12 You are not in wrong place. 👍

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
