### ISSUE TITLE
Request for addition

### ISSUE THREAD

**Issue by gcs1usa** [githubschool/open-enrollment-classes-introduction-to-github#3677]
Hello! :wave: Please add me as a collaborator to this repo. 

Just learning the ropes. 
![rope-clipart-seil](https://cloud.githubusercontent.com/assets/13384498/22852793/23fe53fe-f012-11e6-831d-7904aad640b4.png)

**Comment by githubteacher** [comment]
:tada: @gcs1usa you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
