### ISSUE TITLE
Please add me - Ghent, BE

### ISSUE THREAD

**Issue by TeamleaderSecondline** [githubschool/open-enrollment-classes-introduction-to-github#3689]
## Adding Ghent to the map

Hi everyone, this issue is to track the addition of Ghent to the map, which can be found at:

- Latitude: 51.054342
- Longitude: 3.717424

**Comment by githubteacher** [comment]
:tada: @TeamleaderSecondline you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
