### ISSUE TITLE
Please add me - Leduc AB Canada

### ISSUE THREAD

**Issue by yfCanada** [githubschool/open-enrollment-classes-introduction-to-github#3707]
Hello! :wave: Please add me as a collaborator to this repo. 

Longitude:  -113.550222
Latitude: 53.258013

**Comment by githubteacher** [comment]
:tada: @yfCanada you are now a repository collaborator. :balloon:

**Comment by yfCanada** [comment]
Make a comment to get enrolled as a collaborator!
