### ISSUE TITLE
Please add me - Bogotá, Colombia

### ISSUE THREAD

**Issue by JulianGarzon509** [githubschool/open-enrollment-classes-introduction-to-github#3712]
## Adding Bogotá to the map

-Latitude: 4.541923
-Longitude: -74.104784

**Comment by githubteacher** [comment]
:tada: @JulianGarzon509 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
