### ISSUE TITLE
Please add me - Gaithersburg, MD

### ISSUE THREAD

**Issue by SHANTH2013** [githubschool/open-enrollment-classes-introduction-to-github#3713]
## Adding Gaithersburg to the map

Hi everyone! This issue is to track the additiona of Gaithersburg to the map, which can be found at:

- Longitude: -77.201371
- Latitude: 39.143441

**Comment by githubteacher** [comment]
:tada: @SHANTH2013 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
