### ISSUE TITLE
start-here?

### ISSUE THREAD

**Issue by seemarrs** [githubschool/open-enrollment-classes-introduction-to-github#3730]
https://www.youtube.com/watch?v=kocHKaHtZCc

this video request you go to issue>label drop down>start-here

but start here does not exist

**Comment by ValiantBuaquen** [comment]
https://www.youtube.com/watch?v=kocHKaHtZCc
I was on the on-demand tutorial at GitHub on youtube, specific instructions go to issue>label drop down>start-here(green label) Links break so, will try to follow along tutorial, cheerio!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
