### ISSUE TITLE
Please add me - Atlanta, GA

### ISSUE THREAD

**Issue by leonidas243** [githubschool/open-enrollment-classes-introduction-to-github#3768]
Hello! :wave: Please add me as a collaborator to this repo. 

## Atlanta here
Hello this issue is to track the addition to Atlanta to the map. Which can be found at 
Longitude: 33.7490° N
Latitude: 84.3880° W

**Comment by githubteacher** [comment]
:tada: @leonidas243 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
