### ISSUE TITLE
Please add me to this project  - Colorado Springs, CO

### ISSUE THREAD

**Issue by bdoenges** [githubschool/open-enrollment-classes-introduction-to-github#3792]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Colorado Springs, CO to the map

- Longitude: -104.821
- Latitude:  38.833

**Comment by githubteacher** [comment]
:tada: @bdoenges you are now a repository collaborator. :balloon:

**Comment by bdoenges** [comment]
New to GitHub.
