### ISSUE TITLE
Please add me to a new collab!

### ISSUE THREAD

**Issue by Anjanette-09** [githubschool/open-enrollment-classes-introduction-to-github#3793]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Anjanette-09 you are now a repository collaborator. :balloon:

**Comment by xyhesummer** [comment]
@Anjanette-09 well done!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
