### ISSUE TITLE
Please add me - Spokane Valley, WA

### ISSUE THREAD

**Issue by jripke74** [githubschool/open-enrollment-classes-introduction-to-github#3794]
## Adding Spokane Valley to the map

Hi everyone! This issue is to track the addition of Spokane Valley to the map, which can be found at: 

- Logitude: -117.426048
- Latitude: 47.658779

**Comment by githubteacher** [comment]
:tada: @jripke74 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
