### ISSUE TITLE
Adding San Pablo to the map

### ISSUE THREAD

**Issue by teflonbeltran** [githubschool/open-enrollment-classes-introduction-to-github#38]
## Adding San Pablo to the map

Hi everyone! This issue is to track the addition of San Pablo to the map, which can be found at:

- Longitude: -122.345526
- Latitude: 37.962146

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:
