### ISSUE TITLE
Please add me - Chennai, India

### ISSUE THREAD

**Issue by vinpk** [githubschool/open-enrollment-classes-introduction-to-github#3806]
#Adding Chennai to the map

Hi Guys, This is to add Chennai in map. Cheers

- Longitude: 13.054434
- Latitude: 80.282991

**Comment by githubteacher** [comment]
:tada: @vinpk you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
