### ISSUE TITLE
Collab Add?

### ISSUE THREAD

**Issue by infectedspawn** [githubschool/open-enrollment-classes-introduction-to-github#3828]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @infectedspawn you are now a repository collaborator. :balloon:

**Comment by MrWang229** [comment]
#3826 ？？

**Comment by mariaclaudia** [comment]
Hi! I didn't understand where this number should come from...

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
