### ISSUE TITLE
Please add me - Cranleigh, United Kingdom

### ISSUE THREAD

**Issue by Sounderme** [githubschool/open-enrollment-classes-introduction-to-github#3868]
Hello! :wave: Please add me as a collaborator to this repo. 

## Adding Cranleigh to the map

This is an issue to track the addition of Cranleigh, UK to the map

51.1411° N, 
0.4840° W

**Comment by githubteacher** [comment]
:tada: @Sounderme you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
