### ISSUE TITLE
Please add me Croydon, UK

### ISSUE THREAD

**Issue by gawdeamol** [githubschool/open-enrollment-classes-introduction-to-github#3869]
Hello! :wave: Please add me as a collaborator to this repo.
Adding Croydon to the map

This is an issue to track the addition of Croydon, UK to the map

51.3762° N
0.0982° W

**Comment by githubteacher** [comment]
:tada: @gawdeamol you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
