### ISSUE TITLE
Please add me - Derby, UK

### ISSUE THREAD

**Issue by matthewpoll** [githubschool/open-enrollment-classes-introduction-to-github#3887]
## Adding Derby to the map

Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude: 53.118755
- Latitude:  -1.448822

**Comment by githubteacher** [comment]
:tada: @matthewpoll you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
