### ISSUE TITLE
open

### ISSUE THREAD

**Issue by zalew16** [githubschool/open-enrollment-classes-introduction-to-github#3920]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @zalew16 you are now a repository collaborator. :balloon:

**Comment by zalew16** [comment]
@zalew16

**Comment by hectorsector** [comment]
@T4selogistics Please refrain from closing issues and Pull Requests owned by someone else. We'd like to ensure every student has the satisfaction of merging their own branch, or closing it themselves.
