### ISSUE TITLE
Adding my city of Raleigh

### ISSUE THREAD

**Issue by kimholmes** [githubschool/open-enrollment-classes-introduction-to-github#393]
## Adding <Raleigh> to the map

Hi everyone! This issue is to track the addition of <Raleigh> to the map, which can be found at:
- Longitude: <-78.638179>
- Latitude: <35.779590>

**Comment by kimholmes** [comment]
I'm practicing some more and going to add my name again.

**Comment by ygoldberg** [comment]
Adding my name here

**Comment by pluton3215** [comment]
adding my name here

**Comment by debosmitadas28** [comment]
adding my name here
