### ISSUE TITLE
Please add me - Parma IT

### ISSUE THREAD

**Issue by savicarlo** [githubschool/open-enrollment-classes-introduction-to-github#3937]
## adding Parma to the map

hi everyone! this issue is to track the addition of Parma (IT) to the map.

latitude: 44.796869
longitude:10.342936

**Comment by githubteacher** [comment]
:tada: @savicarlo you are now a repository collaborator. :balloon:

**Comment by savicarlo** [comment]
@githubteacher . Thank you.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
