### ISSUE TITLE
Please Remove Me

### ISSUE THREAD

**Issue by SeanCarrick** [githubschool/open-enrollment-classes-introduction-to-github#3961]
Please remove me as a collaborator on this repository. Thanks!

**Comment by brianamarie** [comment]
@SeanCarrick I will remove you as a collaborator, but if you're getting a lot of notifications, the best thing to do would probably be to 'ignore' this repository.  [Here are some directions](https://help.github.com/articles/unwatching-repositories/).

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
