### ISSUE TITLE
Please add me - Olathe, KS

### ISSUE THREAD

**Issue by OldHWGuy** [githubschool/open-enrollment-classes-introduction-to-github#3973]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Olathe to the map
 Hi everyone, this issue is to track the addition of Olathe Kansas to the map, which can be found at:

-Latitude:38.908304
-Longitude: -94.821049

**Comment by githubteacher** [comment]
:tada: @OldHWGuy you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
