### ISSUE TITLE
Please add me - cgsprite

### ISSUE THREAD

**Issue by cgsprite** [githubschool/open-enrollment-classes-introduction-to-github#3982]
Hello! :wave: Please add me as a collaborator to this repo. 
Thank you!

**Comment by githubteacher** [comment]
:tada: @cgsprite you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
