### ISSUE TITLE
Please add me - Belgrade Arena, SERBIA

### ISSUE THREAD

**Issue by nekac** [githubschool/open-enrollment-classes-introduction-to-github#3986]
## Adding Belgrade Arena on map

Hello! This issue is to track the addition of Belgrade Arena to the map, which can be found at:
Latitude: 44.814395
Longitude: 20.421588

**Comment by githubteacher** [comment]
:tada: @nekac you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
