### ISSUE TITLE
Please add me

### ISSUE THREAD

**Issue by daveplunkett** [githubschool/open-enrollment-classes-introduction-to-github#3991]
Hello! :wave: Please add me as a collaborator to this repo. 

## City - Boulder, CO
Longitude - 40.0150° N
Latitude - 105.2705° W

**Comment by githubteacher** [comment]
:tada: @daveplunkett you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
