### ISSUE TITLE
Adding San Francisco to the Map

### ISSUE THREAD

**Issue by jgovea25** [githubschool/open-enrollment-classes-introduction-to-github#4]
## Adding San Francisco to the map

Hi everyone! This issue is to track the addition of San Francisco to the map, which can be found at:

- Longitude: -122.421242
- Latitude: 37.778687

**Comment by svtruong** [comment]
Hi all - I'll be adding my pin for this city.

- Longitude: -122.421876
- Latitude: 37.768293

**Comment by BonnieC** [comment]
Hello! I will be adding my name to the pin for this city.

- Longitude: -122.421876
- Latitude: 37.768293

**Comment by seanlee14** [comment]
Third! Adding myself to the SF pin!

**Comment by KeepItCooley** [comment]
I am also adding a pin to San Francisco!

**Comment by alexandrakelly** [comment]
I am adding a pin to SF!

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new pull request. 😄 Thank you and happy coding! :octocat:

**Comment by doctorwholock** [comment]
I'll be adding a pin to SF as well!

**Comment by doctorwholock** [comment]
## Adding San Francisco to the map

Hi everyone! This issue is to track the addition of San Francisco to the map, which can be found at:

- Longitude: -122.419416
- Latitude: 37.774929

**Comment by nayafia** [comment]
I am also adding a pin to SF!

**Comment by corywilkerson** [comment]
Hi there! Adding a pin to SF!
