### ISSUE TITLE
DanK.Issue

### ISSUE THREAD

**Issue by dusan-kenic** [githubschool/open-enrollment-classes-introduction-to-github#4003]
Hello! I just start github training

**Comment by githubteacher** [comment]
:tada: @dusan-kenic you are now a repository collaborator. :balloon:

**Comment by dusan-kenic** [comment]
thanks!!!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
