### ISSUE TITLE
GitHub student too

### ISSUE THREAD

**Issue by T4selogistics** [githubschool/open-enrollment-classes-introduction-to-github#4006]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @T4selogistics you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
