### ISSUE TITLE
Add as collaborator

### ISSUE THREAD

**Issue by jameshenrylittle** [githubschool/open-enrollment-classes-introduction-to-github#4009]
Apparently I can't create my own branch without being a collaborator and I want to complete the tutorial and get my little city on the map.

Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @jameshenrylittle you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
