### ISSUE TITLE
Sleepy

### ISSUE THREAD

**Issue by cumthlq** [githubschool/open-enrollment-classes-introduction-to-github#4017]
Hello! :wave: Please add me as a collaborator to this repo. I am sleepy.

**Comment by githubteacher** [comment]
:tada: @cumthlq you are now a repository collaborator. :balloon:

**Comment by cumthlq** [comment]
Thankx a lot

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
