### ISSUE TITLE
Hey guys :)

### ISSUE THREAD

**Issue by jacobsalzberg** [githubschool/open-enrollment-classes-introduction-to-github#4021]
Hello! :wave: Please add me as a collaborator to this repo. 

Getting started here! Have a nice day everyone.

**Comment by githubteacher** [comment]
:tada: @jacobsalzberg you are now a repository collaborator. :balloon:

**Comment by jacobsalzberg** [comment]
Thanks boss

**Comment by ValiantBuaquen** [comment]
Greetings! 👋  Pretty please add me as a collaborator to this repository. May the force be with y'al.
