### ISSUE TITLE
Please add me-PUNE, IND

### ISSUE THREAD

**Issue by shaiLENDRA-d** [githubschool/open-enrollment-classes-introduction-to-github#4026]
Hello! :+1: wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @shaiLENDRA-d you are now a repository collaborator. :balloon:

**Comment by shaiLENDRA-d** [comment]
Thanks

**Comment by hectorsector** [comment]
@T4selogistics Please refrain from closing issues and Pull Requests owned by someone else. We'd like to ensure every student has the satisfaction of merging their own branch, or closing it themselves.
