### ISSUE TITLE
USF - Tampa, florida

### ISSUE THREAD

**Issue by cgado12** [githubschool/open-enrollment-classes-introduction-to-github#405]
## Adding Tampa to the map

Hi everyone! This issue is to track the addition of Tampa to the map, which can be found at:

- Longitude: 28.139937
- Latitude: -82.488716

**Comment by aperez36** [comment]
Hey Chris, Its Carlos !

**Comment by dhamone** [comment]
What's good Tampa.. Thanks GitHub and Women In Linux :)

**Comment by meggerc** [comment]
Great training class here at the wave!

**Comment by jedfarm** [comment]
Cool GitHub learning session!
