### ISSUE TITLE
Ocoee Florida

### ISSUE THREAD

**Issue by dhamone** [githubschool/open-enrollment-classes-introduction-to-github#406]
## Adding Ocoee to the map

Hi everyone! This issue is to track the addition of Ocoee to the map, which can be found at:

- Longitude: <28.574167>
- Latitude: <-81.530556>

[https://tools.wmflabs.org/geohack/geohack.php?pagename=Ocoee%2C_Florida&params=28_34_27_N_81_31_50_W_type:city(35579)_region:US-FL](url)

![unixlogo](https://cloud.githubusercontent.com/assets/12648177/18111096/de895132-6eea-11e6-9800-676c08e9c1c4.gif)

**Comment by JBrady22** [comment]
Hello i live here too!
