### ISSUE TITLE
True Pioneers

### ISSUE THREAD

**Issue by MommyMisty1** [githubschool/open-enrollment-classes-introduction-to-github#4111]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @MommyMisty1 you are now a repository collaborator. :balloon:

**Comment by MommyMisty1** [comment]
A true pioneer ; my grandmother Maxine Kennedy . One of thirteen , the last of her peers alive , as she passed , at the age of ninety . I love you , Granny ! M.A.M.
