### ISSUE TITLE
New issue 453

### ISSUE THREAD

**Issue by pogorek** [githubschool/open-enrollment-classes-introduction-to-github#4152]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @pogorek you are now a repository collaborator. :balloon:

**Comment by pogorek** [comment]
## Adding Chorzów to the map.

Hi everyone! This issue is to track the addition of Chorzów to the map, which can be found at:

- Longitude: 18.937089
- Latitude: 50.266417
