### ISSUE TITLE
Comment Here

### ISSUE THREAD

**Issue by smuhuri** [githubschool/open-enrollment-classes-introduction-to-github#4157]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @smuhuri you are now a repository collaborator. :balloon:

**Comment by CurtGreen** [comment]
Hello GitHub World! I am learning how to leverage the tool for collaborative purposes!

**Comment by chumaumenze** [comment]
Hello! 👋 Please add me as a collaborator to this repo.

**Comment by ken111989** [comment]
Hello! Please add me as a collaborator to this repository.

**Comment by oddrunes** [comment]
oddrunes-Stavanger

**Comment by oddrunes** [comment]
Hello

**Comment by sethamundsen** [comment]
Hi!
