### ISSUE TITLE
Please add me - Monrovia, Liberia

### ISSUE THREAD

**Issue by mysterioux** [githubschool/open-enrollment-classes-introduction-to-github#4175]
Hello! :wave: Please add me as a collaborator to this repo. 

## Adding Monrovia to the map

Hi  everyone! This issue is to track the addition of Liberia to the map, which can be found at:

-latitude: 6.290743
-longitude: -10.760524

**Comment by githubteacher** [comment]
:tada: @mysterioux you are now a repository collaborator. :balloon:

**Comment by mysterioux** [comment]
Good to be here
