### ISSUE TITLE
Dallas, TX

### ISSUE THREAD

**Issue by canreo** [githubschool/open-enrollment-classes-introduction-to-github#419]
## Adding Dallas, TX to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: -96.796988
- Latitude: 32.776664

**Comment by rham805** [comment]
Hello, I like that you want to add Dallas,TX to the map.

**Comment by aamir-syed-m** [comment]
Learning GitHub

**Comment by sunjolia** [comment]
Adding my name

**Comment by sunjolia** [comment]
Adding my name
