### ISSUE TITLE
Adding Taipei

### ISSUE THREAD

**Issue by grapes323** [githubschool/open-enrollment-classes-introduction-to-github#420]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of Taipei to the map, which can be found at:

- Longitude: 25.0330° N
- Latitude: 96.7970° W

**Comment by grapes323** [comment]
@HelloChloe HEY

**Comment by HelloChloe** [comment]
Hello
@grapes323

**Comment by jameshuang304** [comment]
Hi~~ @HelloChloe @grapes323

**Comment by Peterlin0629** [comment]
Hi nice to meet u guys
I am also from Taipei, Taiwan
@grapes323 @HelloChloe @jameshuang304

**Comment by ringline910** [comment]
Hi , 
I am from Taipei, Taiwan, too.

**Comment by billhung56** [comment]
Hello, guys!

**Comment by JiaPing1019** [comment]
Hello :)
