### ISSUE TITLE
Please add me - Amsterdam, The Netherlands

### ISSUE THREAD

**Issue by BernouWagenaar** [githubschool/open-enrollment-classes-introduction-to-github#4255]
## Adding Amsterdam to the map

Hello! :wave: Please add me as a collaborator to this repo. 

This issue is to track the addition of Amsterdam to the map, which can be found at:

- Longitude: 52.370216
- Latitude: 4.895168

**Comment by githubteacher** [comment]
:tada: @BernouWagenaar you are now a repository collaborator. :balloon:
