### ISSUE TITLE
Adding Kiev to the map

### ISSUE THREAD

**Issue by Kladproraba** [githubschool/open-enrollment-classes-introduction-to-github#4263]
Hello! :wave: Please add me as a collaborator to this repo. 
This issue is to track the addition of Kiev to the map, which can be found at:
•	Longitude: 30.5238
•	Latitude: 50.45466

**Comment by githubteacher** [comment]
:tada: @Kladproraba you are now a repository collaborator. :balloon:

**Comment by Kladproraba** [comment]
Thank you :-)
