### ISSUE TITLE
Please add Tim - Aussie living in Tübingen Germany

### ISSUE THREAD

**Issue by TimmDay** [githubschool/open-enrollment-classes-introduction-to-github#4292]
##Adding Tübingen to the map

Hallo! :wave:!  Please add me as a collaborator to this repo. 
This issue is to track the addition of Tübingen, Germany to the map. It can be found at:

Latitude: 48.5333333
Longitude: 9.05

**Comment by githubteacher** [comment]
:tada: @TimmDay you are now a repository collaborator. :balloon:
