### ISSUE TITLE
 Los Angeles 

### ISSUE THREAD

**Issue by tstone92** [githubschool/open-enrollment-classes-introduction-to-github#43]
## Adding Los Angeles  to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <-118.410468>
- Latitude: <34.103003>

**Comment by Raulv81** [comment]
I will be adding my name to the pin

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:

**Comment by liemdoan** [comment]
I will be adding my name to Los Angeles
