### ISSUE TITLE
Can't open a new branch

### ISSUE THREAD

**Issue by ikukuvision** [githubschool/open-enrollment-classes-introduction-to-github#4346]
Hello there. This is ikukuvision from London. Trying to get to grips with your incredible tool. I am following your youTube Video, but i am not able to create a new branch with my unique handle. 

When i try to create one, it filters and says the "the branch does not exist", but it doesn't give me the option to create a new one.

I apologize if its really obvious :), but i can't seem to get past this. Appreciate your help. Thanks

**Comment by githubteacher** [comment]
:tada: @ikukuvision you are now a repository collaborator. :balloon:

**Comment by brianamarie** [comment]
Hi! Try again now,  you should be good to go!

**Comment by orwa1902** [comment]
how did you create a new branch? maybe the syntax isn't good
