### ISSUE TITLE
Can we open github 'html' file in the web browser ? 

### ISSUE THREAD

**Issue by Dil2000** [githubschool/open-enrollment-classes-introduction-to-github#4354]
Can we open github 'html' file in the web browser ?

**Comment by brianamarie** [comment]
Hi @Dil2000! I'm not sure I understand what you mean. Is there a specific HTML file you'd like to look at?

**Comment by Dil2000** [comment]
I just took part of the lessons and i thought whether i could open a html file directly from github(not github in my desktop) in the browser to view - not to edit. Like a normal webpage ?

**Comment by Dil2000** [comment]
Thank you for the reply :) sorry forgot to mention that earlier :)

**Comment by brianamarie** [comment]
Ah, I see. You can view it as raw text, or as text to edit, but if you're looking to view it as a rendered HTML page you might need to use another tool, like this: http://htmlpreview.github.io/

**Comment by Dil2000** [comment]
Oh thank you so much. That was my problem :)

**Comment by MarkMGill** [comment]
This allows you to see just the raw html file.  Is there somewhere you can view the  html file rendered along with CSS and JS files?
