### ISSUE TITLE
Pin removed?

### ISSUE THREAD

**Issue by jr-cologne** [githubschool/open-enrollment-classes-introduction-to-github#436]
Hello,

@hectorsector, @brianamarie 

I think my Pin for the city Cologne has been removed by PR #360.

Should I create the Pin again or what else?

Thanks for your help!

Best regards,
JR Cologne

**Comment by brianamarie** [comment]
@jr-cologne You are right! This is a clerical error that I will take responsibility for - thank you so much for bringing it to our attention. 😄 

This all happened during a transition to different syntax for the pins. I'm happy to recreate your pin in our new syntax if you'd like, or you can do so yourself if you'd prefer. Just let me know. 👍 

New syntax, for reference: 
filename: `/_pins/jr-cologne.json`
content:
```
---
githubHandle: jr-cologne
latitude: 50.937531
longitude: 6.960279
---
```

**Comment by jr-cologne** [comment]
No problem!

I can do it myself.

**Comment by brianamarie** [comment]
Fantastic, @jr-cologne! ✨  Thanks for noticing and taking care of it. Let us know if we can help any more along the way.
