### ISSUE TITLE
A learner with no knowledgecannot even pin 3889 onto Country Map but is very loyal

### ISSUE THREAD

**Issue by 3889** [githubschool/open-enrollment-classes-introduction-to-github#4362]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @3889 you are now a repository collaborator. :balloon:

**Comment by 3889** [comment]
Oh Thank You githubteacher you have made my day
Thank You
Ace 888

**Comment by 3889** [comment]
Dear githubteacher how do I place myself on the map.  Thank You 
I noted Projects No 1
Regards 3889
