### ISSUE TITLE
Please Add Me - Setubal - Portugal

### ISSUE THREAD

**Issue by aferreira-pt** [githubschool/open-enrollment-classes-introduction-to-github#4384]
Hello! :wave: Please add me as a collaborator to this repo. 

This issue is to track the city of Setubal from Portugal to the map, which can be found at:

- Longitude: -8.891067982112872 
- Latitude: 38.523001876042805

**Comment by githubteacher** [comment]
:tada: @aferreira-pt you are now a repository collaborator. :balloon:
