### ISSUE TITLE
San Antonio, TX

### ISSUE THREAD

**Issue by vmramirez** [githubschool/open-enrollment-classes-introduction-to-github#44]
## Adding <San Antonio> to the map

Hi everyone! This issue is to track the addition of <San Antonio> to the map, which can be found at:

- Longitude: <29.424122>
- Latitude: <-98.493628>

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:

**Comment by SPCOxion** [comment]
I'll be adding my name to the pin for the city.
