### ISSUE TITLE
Orlando, FL

### ISSUE THREAD

**Issue by emerced2** [githubschool/open-enrollment-classes-introduction-to-github#444]
## Adding Orlando, FL to the map

Hi everyone! This issue is to track the addition of Orlando, FL to the map, which can be found at:

- Longitude: -81.502007
- Latitude: 28.696490

**Comment by jmasterson5** [comment]
I will be adding my name to the pin for the city

**Comment by AntoineDS** [comment]
I will be adding my name to this for this city

**Comment by ifresh102** [comment]
I will be adding my name to this for this city

**Comment by rbowser5** [comment]
Adding my name to this pin!

**Comment by anajera** [comment]
Adding my name to this pin for Orlando

**Comment by DhvaniP** [comment]
I will be adding my name to this pin

**Comment by mdean19** [comment]
I will be adding my name to this pin

**Comment by aalevane** [comment]
Adding my name to this pin!

**Comment by mirenagreen** [comment]
Adding my name to this pin!

**Comment by lminks** [comment]
Adding my name to the pin.

**Comment by orlandogivens** [comment]
I will be adding my name to this pin

**Comment by ZPeterson2** [comment]
Adding my name to the pin

**Comment by jenny0325** [comment]
I will be adding my name to this pin

**Comment by jenny0325** [comment]
I will be adding my name to this pin

**Comment by KaidyCEThomas** [comment]
I will be adding my name to the pin for the city
