### ISSUE TITLE
Denver

### ISSUE THREAD

**Issue by ArcticLlama** [githubschool/open-enrollment-classes-introduction-to-github#446]
## Adding Denver to the map

Hi everyone! This issue is to track the addition of Denver to the map, which can be found at:
- Longitude: 104.9903 W
- Latitude: 39.7392 N

**Comment by tnordloh** [comment]
Howdy!  I'll be adding my name to the pin for Denver

**Comment by sallarak** [comment]
Adding my name to the pin for Denver

**Comment by AdrienneChristy** [comment]
Hi @tnordloh and @sallarak, I'll be adding my name too.

**Comment by iamstevevan** [comment]
Mile High!

**Comment by elvman12** [comment]
I am in Denver as well... woohoooo.

**Comment by sbs205c5** [comment]
Also in Denver!

**Comment by gllisch** [comment]
Denver!
