### ISSUE TITLE
Using git hub for the first time

### ISSUE THREAD

**Issue by AbdelhamidBouchibane** [githubschool/open-enrollment-classes-introduction-to-github#4463]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @AbdelhamidBouchibane you are now a repository collaborator. :balloon:

**Comment by shajanjp** [comment]
@AbdelhamidBouchibane Nice. There's always a first time. Hope you will enjoy using Github.
