### ISSUE TITLE
Please add me- New Delhi

### ISSUE THREAD

**Issue by theHummer07** [githubschool/open-enrollment-classes-introduction-to-github#4465]
##Adding New Delhi to the map

Hi everyone!this issue to track the addition of New Delhi to the map which can be found at : 
 Longitude: 77.209021
Latitude: 28.613939

**Comment by githubteacher** [comment]
:tada: @theHummer07 you are now a repository collaborator. :balloon:

**Comment by shajanjp** [comment]
Hello @theHummer07, this is how you can add your location to the map.
* Clone this repository
* Add a json file to `_pins` directory that contains your geo-location and username.
* Commit
* Do a pull request.

If you get stuck somewhere, let us know. We are always here to help.
