### ISSUE TITLE
Patchwork Class- Boulder

### ISSUE THREAD

**Issue by hmorgan88** [githubschool/open-enrollment-classes-introduction-to-github#447]
## Adding Boulder to the map

Hi everyone! This issue is to track the addition of Boulder to the map, which can be found at:
- Longitude: <-105.270546>
- Latitude: <461857730>

**Comment by megan-mcgoodwin** [comment]
I will be adding my name to the pin for our city!

**Comment by bruja-local** [comment]
Also adding my name!

**Comment by JimArnow** [comment]
I will be adding my name.
