### ISSUE TITLE
Please add me - Hyderabad, India

### ISSUE THREAD

**Issue by ssharma156** [githubschool/open-enrollment-classes-introduction-to-github#4480]
Hello! :wave: Please add me as a collaborator to this repo. 

Longitude: 78.4667
Latitude: 17.3833

**Comment by githubteacher** [comment]
:tada: @ssharma156 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
