### ISSUE TITLE
Add Me to Class

### ISSUE THREAD

**Issue by djhobbs** [githubschool/open-enrollment-classes-introduction-to-github#4482]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @djhobbs you are now a repository collaborator. :balloon:

**Comment by djhobbs** [comment]
thanks

**Comment by djhobbs** [comment]
Please at Auburn to the map

- Longitude 47.3073° N
- Latitude 122.2285° W

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
