### ISSUE TITLE
Please add me - Vancouver, BC

### ISSUE THREAD

**Issue by hellofisher** [githubschool/open-enrollment-classes-introduction-to-github#4500]
## Adding Vancouver to the map

Hi everyone! This iss is to track the addition of Vancouver to the map, which can be found at:

- Longitude: 49.246292
- Latitude: -123.116226

**Comment by githubteacher** [comment]
:tada: @hellofisher you are now a repository collaborator. :balloon:

**Comment by kenschlenker** [comment]
Please detach me from this thread
On Mar 11, 2017, at 16:44, hellofisher <notifications@github.com<mailto:notifications@github.com>> wrote:

Adding Vancouver to the map

Hi everyone! This iss is to track the addition of Vancouver to the map, which can be found at:

  *   Longitude: 49.246292
  *   Latitude: -123.116226
