### ISSUE TITLE
app for engineering college

### ISSUE THREAD

**Issue by pdjambhale777** [githubschool/open-enrollment-classes-introduction-to-github#4523]
Hello! :wave: Please add me as a collaborator to this repo. 
i am in engineering college where i want to build software for students daily assignments, notes and photo sharing and there feedback about teachers

**Comment by githubteacher** [comment]
:tada: @pdjambhale777 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
