### ISSUE TITLE
Please add me - Fr

### ISSUE THREAD

**Issue by calvinette** [githubschool/open-enrollment-classes-introduction-to-github#4527]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @calvinette you are now a repository collaborator. :balloon:

**Comment by calvinette** [comment]
thank you 😄

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
