### ISSUE TITLE
Please add me - Córdoba, ARG

### ISSUE THREAD

**Issue by mmodenesi** [githubschool/open-enrollment-classes-introduction-to-github#4528]
Hello! :wave:

This issue is to add Córdoba to the map

**Comment by githubteacher** [comment]
:tada: @mmodenesi you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
