### ISSUE TITLE
Please add me

### ISSUE THREAD

**Issue by qewry** [githubschool/open-enrollment-classes-introduction-to-github#4564]
Hello! 🌘 Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @qewry you are now a repository collaborator. :balloon:

**Comment by qewry** [comment]
Greetings! :)
How can i find my issue on my profile? (if i go to the top bar: issues while viewing my profile i can see the issue. But it still under githubschool.
Yours is under your own profile (githubteacher), not under githubschool.
![question](https://cloud.githubusercontent.com/assets/23262839/23925427/c6fc0448-0917-11e7-90c2-a87aeb3771e6.PNG)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by Personallyon** [comment]
Ready to pull
