### ISSUE TITLE
please add me

### ISSUE THREAD

**Issue by tstalin22** [githubschool/open-enrollment-classes-introduction-to-github#4567]
Hello! :wave: Please add me as a collaborator to this repo. 

Seattle

**Comment by githubteacher** [comment]
:tada: @tstalin22 you are now a repository collaborator. :balloon:

**Comment by tstalin22** [comment]
Hi everyone! This issue is to track the addition of Seattle to the map, which can be found at:

Longitude: -122.336600
Latitude: 47.601338

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
