### ISSUE TITLE
ADD ME - INDIA01

### ISSUE THREAD

**Issue by venedara** [githubschool/open-enrollment-classes-introduction-to-github#4572]
Hello Please add me to this repository

**Comment by githubteacher** [comment]
:tada: @venedara you are now a repository collaborator. :balloon:

**Comment by venedara** [comment]
Hello

@evramesh969@gmail.com

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
