### ISSUE TITLE
Please Add Me - Aurora, ON

### ISSUE THREAD

**Issue by mh198012** [githubschool/open-enrollment-classes-introduction-to-github#4582]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Aurora, ON to the map

Hi everyone,
this issue it to track Aurora, ON to the map, which can be found at

44.0065° N, 79.4504° W

**Comment by githubteacher** [comment]
:tada: @mh198012 you are now a repository collaborator. :balloon:

**Comment by shajanjp** [comment]
Welcome @mh198012 :relaxed: Do Aurora has a github handle ?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
