### ISSUE TITLE
Ad Me Please

### ISSUE THREAD

**Issue by dachisolm** [githubschool/open-enrollment-classes-introduction-to-github#4583]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @dachisolm you are now a repository collaborator. :balloon:

**Comment by dachisolm** [comment]
thx

**Comment by dachisolm** [comment]
oops! Pleas add my Pin
Lon: -84.391
Lat: 33.755

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
