### ISSUE TITLE
Please add me - Brunswick, MD

### ISSUE THREAD

**Issue by autocloudarc** [githubschool/open-enrollment-classes-introduction-to-github#4597]
Hello! :wave: Please add me as a collaborator to this repo. 
Latitude: 39.314268
Longtitude: -77.627768

**Comment by githubteacher** [comment]
:tada: @autocloudarc you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
