### ISSUE TITLE
Please add me - Tustin, Ca

### ISSUE THREAD

**Issue by M-W-C** [githubschool/open-enrollment-classes-introduction-to-github#4600]
Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude: -117.8261660
- Latitude: 33.7458510

**Comment by githubteacher** [comment]
:tada: @M-W-C you are now a repository collaborator. :balloon:

**Comment by M-W-C** [comment]
**# Purpose**
I am reopening this issue due to mistakenly closing it previously.

Will close issue once completely resolved.
