### ISSUE TITLE
Add Södertälje

### ISSUE THREAD

**Issue by osundblad** [githubschool/open-enrollment-classes-introduction-to-github#466]
## Adding Södertälje to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: 59°11′45″N
- Latitude: 17°37′41″E

**Comment by 522870** [comment]
Hello I am Timothy cunningham and I'll be adding my name to the issue.

**Comment by Milliye** [comment]
I'll be adding myself
