### ISSUE TITLE
Newbie learning the ropes

### ISSUE THREAD

**Issue by Lauriekr** [githubschool/open-enrollment-classes-introduction-to-github#4677]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Lauriekr you are now a repository collaborator. :balloon:

**Comment by Lauriekr** [comment]
OK, so now I can collaborate with other Git users

**Comment by Lauriekr** [comment]
I',m just loading the Git command line to be able to commit from the cmd

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
