### ISSUE TITLE
Please add me to your project

### ISSUE THREAD

**Issue by ghrirwin** [githubschool/open-enrollment-classes-introduction-to-github#4678]
Hello! :wave: Please add me as a collaborator to this repo. 
This is my position on the planet <Redditch>

Latitude: 52.304735
Longitude: -1.913309

**Comment by githubteacher** [comment]
:tada: @ghrirwin you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
