### ISSUE TITLE
Adding Glendale to the Map

### ISSUE THREAD

**Issue by dolcetta** [githubschool/open-enrollment-classes-introduction-to-github#47]
## Adding <Glendale> to the map

Hi everyone! This issue is to track the addition of <Glendale> to the map, which can be found at:

- Longitude: <34.142508>
- Latitude: <-118.255075>

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:
