### ISSUE TITLE
Please add me - Seattle, WA

### ISSUE THREAD

**Issue by 7720njames** [githubschool/open-enrollment-classes-introduction-to-github#4703]
## Adding Seattle to the map

Hi everyone!  This issue is to track the addition of Seattle to the map, which can be found at:

- Longitude: 47.6062° N
 Latitude:  122.3321° W

**Comment by githubteacher** [comment]
:tada: @7720njames you are now a repository collaborator. :balloon:

**Comment by 7720njames** [comment]
Thank you.
