### ISSUE TITLE
Please add me - Buenos Aires, Argentina

### ISSUE THREAD

**Issue by MaiaEspinosa** [githubschool/open-enrollment-classes-introduction-to-github#4708]
Hello! :wave: Please add me as a collaborator to this repo. 

##Adding Buenos Aires, Argentina to the map

Can be found at:
-Longitude:  -58.3772300° or 58°22.6338′ O
-Latitude:  -34.6131500°	or 34°36′47″ S

**Comment by githubteacher** [comment]
:tada: @MaiaEspinosa you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
