### ISSUE TITLE
Add me please, Stockton California 

### ISSUE THREAD

**Issue by codezillastevie** [githubschool/open-enrollment-classes-introduction-to-github#4714]
Hello! :wave: Please add me as a collaborator to this repo. 
Longitude:37.9577 N
Latitude: 121.2908 W

**Comment by githubteacher** [comment]
:tada: @codezillastevie you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
