### ISSUE TITLE
Wade world testing

### ISSUE THREAD

**Issue by wmanis** [githubschool/open-enrollment-classes-introduction-to-github#4724]
##Adding Auburndale, Fl to the Map

Hello! :wave: Please add me as a collaborator to this repo. 

-Longitude:  -81.78888 
-Latitude:  28.065588

**Comment by githubteacher** [comment]
:tada: @wmanis you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
