### ISSUE TITLE
Add Me-here in Orlando FL

### ISSUE THREAD

**Issue by rwozniakClarityInsights** [githubschool/open-enrollment-classes-introduction-to-github#4760]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @rwozniakClarityInsights you are now a repository collaborator. :balloon:

**Comment by rwozniakClarityInsights** [comment]
Thank you!

**Comment by rwozniakClarityInsights** [comment]
I think I need to specify latitude and longitude, correct?

Latitude: 28.5383
Longitude: 81.3792

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
