### ISSUE TITLE
Please add me - Noida, IND

### ISSUE THREAD

**Issue by ghost** [githubschool/open-enrollment-classes-introduction-to-github#4761]
# Adding Noida to the map
Hi everyone! This issue is to track the addition of Noida to the map, which can be found at:
- Longitude: 77.1912
- Latitude: 28.3412

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
