### ISSUE TITLE
please add me - Flypercom - London,UK

### ISSUE THREAD

**Issue by Flypercom** [githubschool/open-enrollment-classes-introduction-to-github#4762]
Adding Flypercom to the map

Hi everyone! 
This issue is to track the addition of Flypercom to the map, which can be found at:

Longitude: -0.1180
Latitude: 51.5098

**Comment by githubteacher** [comment]
:tada: @Flypercom you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
