### ISSUE TITLE
Adding Kissimmee FL

### ISSUE THREAD

**Issue by MCastro46** [githubschool/open-enrollment-classes-introduction-to-github#479]
## Adding <Kissimmee> to the map

Hi everyone! This issue is to track the addition of <Kissimmee> to the map, which can be found at:

- Longitude: <28.291956>
- Latitude: <-81.407571>

**Comment by Lolivo** [comment]
I'm here too!

**Comment by radicalpharaoh** [comment]
Same over here.

**Comment by paintstone** [comment]
Remove me from your list
