### ISSUE TITLE
Adding Seattle to the map

### ISSUE THREAD

**Issue by kemjo** [githubschool/open-enrollment-classes-introduction-to-github#48]
## Adding Seattle to the map

Hi everyone! This issue is to track the addition of Seattle, WA to the map, which can be found at:

- Longitude: -122.335167
- Latitude: 47.608013

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:

**Comment by camicano** [comment]
Hello! I will be adding my name to the Seattle Area :)

**Comment by berdie** [comment]
Hi! i'm adding my name to the Seattle pin as well.

**Comment by lvelez** [comment]
Adding myself to Seattle :)

**Comment by minjie128** [comment]
Adding my name to the Seattle pin ;)
