### ISSUE TITLE
New Orleans, LA

### ISSUE THREAD

**Issue by AshTemp** [githubschool/open-enrollment-classes-introduction-to-github#488]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of New Orleans to the map, which can be found at:

- Longitude: -90.071532
- Latitude: 29.951066

**Comment by amarquette** [comment]
I will be adding my name to this pin!
![wp_000589](https://cloud.githubusercontent.com/assets/11246587/18290419/faa7da92-7448-11e6-9d2c-e40a74300176.jpg)
