### ISSUE TITLE
Get error on pull request

### ISSUE THREAD

**Issue by JoelGodin** [githubschool/open-enrollment-classes-introduction-to-github#4899]
Must be typo in file.  How to edit one's branch?

**Comment by sskaysi56** [comment]
Hello, 
go to Code and 
type your BRANCH NAME (where it says BRANCH:Master)
you see your profile name or branch name will appear with a green colour, on the same line says update or rename, click on it. It will direct you to a page where it says "View" at the right hand side. click on "View". 

There you will see it says "tree:somenumbers" this is where you can type your branch name, type it and click on it. Then the "edit" sign will be activated to edit. click edit and change the branch name.  

hope that helps.

**Comment by JoelGodin** [comment]
Thank you.

**Comment by JoelGodin** [comment]
Still not able to get branch accepted.
I don't see any typos.
