### ISSUE TITLE
Open source and share knowledge

### ISSUE THREAD

**Issue by MyAngelQian** [githubschool/open-enrollment-classes-introduction-to-github#4925]
Hello! I'm Andrew Jiang from China,Nanjing

**Comment by githubteacher** [comment]
:tada: @MyAngelQian you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
