### ISSUE TITLE
Please Add me - Mumbai,India

### ISSUE THREAD

**Issue by virus-begin** [githubschool/open-enrollment-classes-introduction-to-github#4930]
Hello! :wave: 
# # Adding Mumbai to map
longitude and latitude of Mumbai : 19.0760° N, 72.8777° E

**Comment by githubteacher** [comment]
:tada: @virus-begin you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
