### ISSUE TITLE
Please add me- Los Angeles, CA

### ISSUE THREAD

**Issue by tigresa77** [githubschool/open-enrollment-classes-introduction-to-github#4936]
Hello! :wave: Please add me as a collaborator to this repo. 
Longitude & Latitude: 34.1064° N, 117.5931° W

**Comment by githubteacher** [comment]
:tada: @tigresa77 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
