### ISSUE TITLE
Wazzup?

### ISSUE THREAD

**Issue by robwm** [githubschool/open-enrollment-classes-introduction-to-github#4943]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @robwm you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by robwm** [comment]
Thank you! I did eventually figure it out with everyone's advice.
