### ISSUE TITLE
Please add me Allentown PA

### ISSUE THREAD

**Issue by vprewitt** [githubschool/open-enrollment-classes-introduction-to-github#4979]
## Adding Allentown PA to the Map

Just a test

-Longitude 40.6084
-Latitude 75.4902

**Comment by githubteacher** [comment]
:tada: @vprewitt you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
