### ISSUE TITLE
Please add me. This is so exciting!

### ISSUE THREAD

**Issue by nigelchike** [githubschool/open-enrollment-classes-introduction-to-github#4981]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @nigelchike you are now a repository collaborator. :balloon:

**Comment by nigelchike** [comment]
Thanks!

**Comment by nigelchike** [comment]
Leave a comment

**Comment by nigelchike** [comment]
I didn't do that right

**Comment by nigelchike** [comment]
Leave a comment

**Comment by nigelchike** [comment]
## Add Odenton, MD to map

-Longitude: 76.7002 W
-Latitude: 39.0840 N

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
