### ISSUE TITLE
Dog

### ISSUE THREAD

**Issue by admjgptw1357** [githubschool/open-enrollment-classes-introduction-to-github#4987]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @admjgptw1357 you are now a repository collaborator. :balloon:

**Comment by pianomar** [comment]
Was the name of this issue a reply to mine? loool 😆 @admjgptw1357

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
