### ISSUE TITLE
Class Goals

### ISSUE THREAD

**Issue by gittwit** [githubschool/open-enrollment-classes-introduction-to-github#499]
## Adding Montreal to the map

Hi everyone! This issue is to track the addition of Montreal to the map, which can be found at:

- Longitude: -73.5673° W
- Latitude: 45.5017° N

**Comment by Serious-Rage** [comment]
Awsome Dog

**Comment by rsaa** [comment]
Hey - here's a new student from Montreal.

**Comment by jboisjo** [comment]
Hi everyone, another student from Montreal here :)

**Comment by cbcdiver** [comment]
Hello - I am from Montreal!

**Comment by kim-codes** [comment]
I will be adding my name to this city 👍
