### ISSUE TITLE
github_harshvardhan

### ISSUE THREAD

**Issue by Harshvardhanvipat** [githubschool/open-enrollment-classes-introduction-to-github#5006]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Harshvardhanvipat you are now a repository collaborator. :balloon:

**Comment by Harshvardhanvipat** [comment]
add  me to the project

**Comment by Harshvardhanvipat** [comment]
Latitude:37.8136° S, 
Longitude: 144.9631° E

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
