### ISSUE TITLE
Add Lovettsville to the map.

### ISSUE THREAD

**Issue by AFMcGphGL** [githubschool/open-enrollment-classes-introduction-to-github#5022]
Hello! :wave: Please add me as a collaborator to this repo. 

Lattitude: 39.2369541
Longitude: -77.6614231

Thanks!

**Comment by githubteacher** [comment]
:tada: @AFMcGphGL you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
