### ISSUE TITLE
Please Add Me - Salt Lake City, UT

### ISSUE THREAD

**Issue by brentmayberry** [githubschool/open-enrollment-classes-introduction-to-github#5085]
## Adding Salt Lake City to the map

Hello! :wave: Please add me as a collaborator to this repo. 

-Latitude: 40.77852
-Longitude: -111.931414

Thanks!

**Comment by githubteacher** [comment]
:tada: @brentmayberry you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
