### ISSUE TITLE
Adding Pismo Beach, CA to the map

### ISSUE THREAD

**Issue by JodiDelman** [githubschool/open-enrollment-classes-introduction-to-github#51]
## Adding Pismo Beach, CA to the map

Hi everyone! This issue is to track the addition of Pismo Beach to the map, which can be found at:

- Longitude: 35.142753
- Latitude: 35.142753

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:
