### ISSUE TITLE
Please add me - Durban, South Africa

### ISSUE THREAD

**Issue by kieronpeter** [githubschool/open-enrollment-classes-introduction-to-github#5111]
Hello! :wave: Please add me as a collaborator to this repo. 

Longitude: 31.05
Latitude: -29.883333

**Comment by githubteacher** [comment]
:tada: @kieronpeter you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
