### ISSUE TITLE
Wisps' simple add me request.

### ISSUE THREAD

**Issue by Wispring** [githubschool/open-enrollment-classes-introduction-to-github#5116]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Wispring you are now a repository collaborator. :balloon:

**Comment by Wispring** [comment]
Thank you, however, i do not have a very clear idea at this point what is entailed in being a repository collaborator here.

**Comment by Wispring** [comment]
I am trying to follow and complete the introduction to github 101 introduction to github lesson at the moment. Am i chatting with a person or an automated responder of some kind now?

**Comment by Wispring** [comment]
@githubteacher . Hi, just trying to ascertain if you are a programmed helper bot of some sort or a human like me.

**Comment by Wispring** [comment]
pretty sure you are a helper bot. If not i apologize. namaste. sincerely, Wispring.
