### ISSUE TITLE
Adding Orlando, FL

### ISSUE THREAD

**Issue by aalevane** [githubschool/open-enrollment-classes-introduction-to-github#525]
## Adding Orlando to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 81° 22' 45.2424'' W
- Latitude: 28° 32' 18.0096'' N

**Comment by nshort1** [comment]
Hi! Looks like I'll be joining in on the pin for Orlando!

**Comment by SalvadorRuizIII** [comment]
Hey all, looks like i'll be joining this pin for orlando as well!
