### ISSUE TITLE
Hi, i would to take part of this project. thanks 

### ISSUE THREAD

**Issue by newordn** [githubschool/open-enrollment-classes-introduction-to-github#5252]
Hello! my name is Neword. Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @newordn you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
