### ISSUE TITLE
Please add me - Bratislava

### ISSUE THREAD

**Issue by saiapinartem** [githubschool/open-enrollment-classes-introduction-to-github#5263]
## Adding Bratislava to the map

Hi everyone! This issue is to track the addition of Bratislava to the map, which can be found at:
- Longitude: 48.1486
- Latitude: 17.1077

**Comment by githubteacher** [comment]
:tada: @saiapinartem you are now a repository collaborator. :balloon:

**Comment by prokonekt** [comment]
i concur
