### ISSUE TITLE
Cary, NC

### ISSUE THREAD

**Issue by melscoop** [githubschool/open-enrollment-classes-introduction-to-github#54]
## Adding Cary, NC to the map

Hi everyone! This issue is to track the addition of Cary, NC to the map, which can be found at:

- Longitude: 78.7811° W
- Latitude:  35.7915° N

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat:

**Comment by melscoop** [comment]
NP, Thanks! 😸
