### ISSUE TITLE
Adding Orlando to the map

### ISSUE THREAD

**Issue by dmattingley1** [githubschool/open-enrollment-classes-introduction-to-github#540]
## Adding <Orlando> to the map

Hi everyone! This issue is to track the addition of <Orlando> to the map, which can be found at:

- Longitude: <28.5383°>
- Latitude: <81.3792°>

**Comment by lazybray** [comment]
I will be adding my name to the pin for the city

**Comment by orlandogivens** [comment]
I will be adding my name to the pin
