### ISSUE TITLE
Hello! :wave Please add me as a collborator 

### ISSUE THREAD

**Issue by Tracker619** [githubschool/open-enrollment-classes-introduction-to-github#5424]
Hello! :wave: Please add me as a collaborator to this repo.   @dunbam01

**Comment by githubteacher** [comment]
:tada: @Tracker619 you are now a repository collaborator. :balloon:

**Comment by dunbam01** [comment]
I believe I did…  it didn’t give me a real positive confirmation though.

It did let me copy this link:

https://github.com/dunbam01/MikeFirstRepo/invitations

**Comment by Tracker619** [comment]
Worked just now.
