### ISSUE TITLE
Please add me 

### ISSUE THREAD

**Issue by thomasleung** [githubschool/open-enrollment-classes-introduction-to-github#5448]
Hello! :wave: Please add me as a collaborator to this repo. 

##Adding Niskayuna NY to the map

Hi Everyone! this issue is to track addition of Niskayuna NY to the map

- Longitude: -73.891441
= Latitude: 42.800005

**Comment by githubteacher** [comment]
:tada: @thomasleung you are now a repository collaborator. :balloon:
