### ISSUE TITLE
Adding Champaign, IL to the map

### ISSUE THREAD

**Issue by freakingid** [githubschool/open-enrollment-classes-introduction-to-github#55]
## Adding Champaign to the map

Hi everyone! This issue is to track the addition of Champaign, IL to the map, which can be found at:
-88.243385, 40.116421
- Longitude: -88.243385
- Latitude: 40.116421

**Comment by brianamarie** [comment]
There are changes coming to this project and repository. To help get it ready, we are hoping to clean up some outstanding issues and pull requests. If you need any additional help, please feel free to open a new issue. 😄 Thank you and happy coding! :octocat: 

P.S. @freakingid I live in Urbana! Glad to see some more central IL on the map. 😄
