### ISSUE TITLE
Ruston, LA

### ISSUE THREAD

**Issue by branhoward** [githubschool/open-enrollment-classes-introduction-to-github#550]
## Adding Ruston to the map

Hi everyone! This issue is to track the addition of Ruston to the map, which can be found at:

- Longitude:  -92.637924
- Latitude:  32.523205

**Comment by cesargafer** [comment]
Good job dude 👍 

![captura de pantalla 2016-09-07 a las 10 58 43 a m](https://cloud.githubusercontent.com/assets/8219546/18319134/14b0b7b4-74ea-11e6-89ff-d81b300cd336.png)
