### ISSUE TITLE
Please Add me - Shanghai CN

### ISSUE THREAD

**Issue by airscofield** [githubschool/open-enrollment-classes-introduction-to-github#5545]
# Adding Shanghai to the map

Hello! :wave: Please add the city of Shanghai to the map, whose coordinate can be found at:

Latitude: 31.2304° N
Longtitude: 121.4737° E

**Comment by githubteacher** [comment]
:tada: @airscofield you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
