### ISSUE TITLE
Please add me - Huntsville, AL

### ISSUE THREAD

**Issue by jhornbuc** [githubschool/open-enrollment-classes-introduction-to-github#5548]
## Adding Huntsville to the map

Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude: -86.5851° E
- Latitude: 34.72929° N

**Comment by githubteacher** [comment]
:tada: @jhornbuc you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
