### ISSUE TITLE
Adding new user from Spokane, WA 15APR2017

### ISSUE THREAD

**Issue by red2kerr** [githubschool/open-enrollment-classes-introduction-to-github#5578]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @red2kerr you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
