### ISSUE TITLE
just learning

### ISSUE THREAD

**Issue by lashbrook71** [githubschool/open-enrollment-classes-introduction-to-github#5596]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @lashbrook71 you are now a repository collaborator. :balloon:

**Comment by lashbrook71** [comment]
create coordinates for Duncan bc

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
