### ISSUE TITLE
Adding Orlando

### ISSUE THREAD

**Issue by orlandogivens** [githubschool/open-enrollment-classes-introduction-to-github#560]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of Orlando to the map, which can be found at:

- Longitude: -81.379236
- Latitude: 28.538336

**Comment by robpb24** [comment]
Adding my name to the pin for Orlando

**Comment by orlandogivens** [comment]
@githubteacher

**Comment by schell10** [comment]
@schell10 | I live in Orlando

**Comment by schell10** [comment]
I live in Orlando as well.  Thank You.

•Longitude: -81.379236
•Latitude: 28.538336

**Comment by Hkhan15** [comment]
I am adding my name to the same city (Orlando)

**Comment by AGuerraDumas** [comment]
I live in Orlando as well.
•Longitude: -81.379236
•Latitude: 28.538336

**Comment by Dukeiv** [comment]
Adding my name to Orlando.
