### ISSUE TITLE
Please add me - Chicago, IL

### ISSUE THREAD

**Issue by berkdiler** [githubschool/open-enrollment-classes-introduction-to-github#5615]
## Adding Chicago to the map

Hi everyone! This issue is to track the addition of Chicago to the map, which can be found at:

- Longitude: 51.5033640
- Latitude: -0.1276250

**Comment by githubteacher** [comment]
:tada: @berkdiler you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
