### ISSUE TITLE
Please add me St. Paul, MN

### ISSUE THREAD

**Issue by irdara** [githubschool/open-enrollment-classes-introduction-to-github#5619]
Hello! :wave: Please add me as a collaborator to this repo. 
St. Paul, MN USA
Longitude	-93.091301
Latitude	        44.954445

**Comment by githubteacher** [comment]
:tada: @irdara you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
