### ISSUE TITLE
Add My Nash Loc

### ISSUE THREAD

**Issue by ldill** [githubschool/open-enrollment-classes-introduction-to-github#5633]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @ldill you are now a repository collaborator. :balloon:

**Comment by ldill** [comment]
First test issue, to add pin to location map.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
