### ISSUE TITLE
Free cookies!!!

### ISSUE THREAD

**Issue by ben8432** [githubschool/open-enrollment-classes-introduction-to-github#5664]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @ben8432 you are now a repository collaborator. :balloon:

**Comment by ben8432** [comment]
thank you githubteacher x

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
