### ISSUE TITLE
Adding me

### ISSUE THREAD

**Issue by Micander-MS** [githubschool/open-enrollment-classes-introduction-to-github#5673]
Hello! :wave: Please add me as a collaborator to this repo. 
## adding my location (Redmond, WA) to the mix

Hello, this issue is to track adding in my location here in Redmond WA. 

-Latitude: 47.644287
-Longitude:-122.14883

**Comment by githubteacher** [comment]
:tada: @Micander-MS you are now a repository collaborator. :balloon:
