### ISSUE TITLE
please add me - Hampton, NH

### ISSUE THREAD

**Issue by mikecico** [githubschool/open-enrollment-classes-introduction-to-github#5687]
## Adding Hampton, NH to the map

Hi everyone! This issue is to track the addition of Hampton, NH to the map, which can be found at: 

- Latitude:  42.9327793
- Longitude: -70.8143146

**Comment by githubteacher** [comment]
:tada: @mikecico you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
