### ISSUE TITLE
Trying to learn.

### ISSUE THREAD

**Issue by jvjishnu** [githubschool/open-enrollment-classes-introduction-to-github#5731]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @jvjishnu you are now a repository collaborator. :balloon:

**Comment by vkgupta857** [comment]
**Please add me as a collaborator.**

**Comment by crichID** [comment]
@vkgupta857 You will need to create your own issue in order to be added as a collaborator. We are using a webhook that is looking for the issue open event, so commenting on an issue doesn't have the same effect.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
