### ISSUE TITLE
Need to add a pin to the map/

### ISSUE THREAD

**Issue by lenardosmani** [githubschool/open-enrollment-classes-introduction-to-github#5741]
:+1: First for Albania :1st_place_medal:

**Comment by githubteacher** [comment]
:tada: @lenardos you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
