### ISSUE TITLE
Please add me -Hisar,India

### ISSUE THREAD

**Issue by Ishikahooda** [githubschool/open-enrollment-classes-introduction-to-github#5760]
Hello! :wave: Please add me as a collaborator to this repo. 
Longitude : 75.7216527
Latitude : 29.1491875

**Comment by githubteacher** [comment]
:tada: @Ishikahooda you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
