### ISSUE TITLE
please  add me -FOSHAN

### ISSUE THREAD

**Issue by liudengfeng** [githubschool/open-enrollment-classes-introduction-to-github#5762]
Hello! :wave: Please add me as a collaborator to this repo. 
Hello! 👋 Please add me as a collaborator to this repo.
Longitude : 113.11
Latitude : 23.05

**Comment by githubteacher** [comment]
:tada: @liudengfeng you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
