### ISSUE TITLE
Adding Stockholm, Sweden

### ISSUE THREAD

**Issue by davidsvson** [githubschool/open-enrollment-classes-introduction-to-github#577]
## Adding Stockholm to the map

Hi everyone! This issue is to track the addition of Stockholm to the map, which can be found at:

- Longitude: 59.329323
- Latitude: 18.068581

**Comment by erikScania** [comment]
Erik

**Comment by hakanfremin** [comment]
hej hej

**Comment by BeyondEvil** [comment]
Adding me to Stockholm

**Comment by jennifrae** [comment]
Hej!
