### ISSUE TITLE
Take Me OFF plz

### ISSUE THREAD

**Issue by reno777** [githubschool/open-enrollment-classes-introduction-to-github#5786]
Hello! :wave: Please delete me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @reno777 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
