### ISSUE TITLE
Please add me - Germany, Düsseldorf

### ISSUE THREAD

**Issue by taptso** [githubschool/open-enrollment-classes-introduction-to-github#5815]
##Adding Düsseldorf to the map 
Hi everyone ! This issue is to track the addition of Düsseldorf (Germany) to the map, which can be found at:
- Longitude: 51.22172
- Latitude: 6.77616

**Comment by githubteacher** [comment]
:tada: @taptso you are now a repository collaborator. :balloon:

**Comment by taptso** [comment]
Thank you
