### ISSUE TITLE
Shanghai

### ISSUE THREAD

**Issue by pigeonn** [githubschool/open-enrollment-classes-introduction-to-github#585]
## Adding Shanghai to the map

Hi everyone! This issue is to track the addition of Shanghai to the map, which can be found at:

- Longitude: 121.4747° E
- Latitude: 31.25516° N

**Comment by bbkxm** [comment]
hi

**Comment by xiutingmi** [comment]
Hello

**Comment by lorraineliu** [comment]
hello
