### ISSUE TITLE
please add me - toronto, ON

### ISSUE THREAD

**Issue by KatCodeland** [githubschool/open-enrollment-classes-introduction-to-github#5882]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Toronto to the map

This issue is to track the addition of Toronto to the map, which can be found at:

Attitude: 43.7615
Longitude: -79.4111

**Comment by githubteacher** [comment]
:tada: @KatCodeland you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
