### ISSUE TITLE
Please add me - New York, NY

### ISSUE THREAD

**Issue by swagharris21** [githubschool/open-enrollment-classes-introduction-to-github#5885]
## Adding New York to the map

Hi everyone! This issue is to track the addition of New York to the map, which can be found at:

-Longitude: 40.730263
-Latitude: -73.982404

**Comment by githubteacher** [comment]
:tada: @swagharris21 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
