### ISSUE TITLE
Please add me - Minsk, BY

### ISSUE THREAD

**Issue by augine** [githubschool/open-enrollment-classes-introduction-to-github#5917]
## Adding Minsk to the map

Hi everyone! This issue is to track the addition of Minsk to the map, which can be found at:

- Longitude: 27.561524
- Latitude: 53.904540

**Comment by githubteacher** [comment]
:tada: @augine you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
