### ISSUE TITLE
Please add me - Bigorio, Switzerland

### ISSUE THREAD

**Issue by Bongulielmi** [githubschool/open-enrollment-classes-introduction-to-github#5929]
## Adding Bigorio to the map

Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude: 8.9548
- Latitude: 46.0725

**Comment by githubteacher** [comment]
:tada: @Bongulielmi you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
