### ISSUE TITLE
Adding Chicago to the map

### ISSUE THREAD

**Issue by svcastaneda** [githubschool/open-enrollment-classes-introduction-to-github#6]
## Adding Chicago to the map

Hi everyone! This issue is to track the addition of Chicago to the map, which can be found at:
- Longitude: -87.629798
- Latitude: 41.878114

**Comment by michelleling225** [comment]
Also from here, so I'm just gonna add myself.

**Comment by bakerfranke** [comment]
Adding Chicago again for practice.

**Comment by brittbolen** [comment]
reopening this issue... to add chicago again
