### ISSUE TITLE
Please add me, Orlando, FL

### ISSUE THREAD

**Issue by wfrank1155** [githubschool/open-enrollment-classes-introduction-to-github#6002]
Hello! :wave: Please add me as a collaborator to this repo. 

28.5383° N, 81.3792° W

**Comment by githubteacher** [comment]
:tada: @wfrank1155 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
