### ISSUE TITLE
Please add me - São José dos Campos - BR

### ISSUE THREAD

**Issue by Emerick94** [githubschool/open-enrollment-classes-introduction-to-github#6031]
Hello! :wave: Please add me as a collaborator to this repo. 

my city is at:
- Longitutde: -45.900907
- Latitude: -23.223701

**Comment by githubteacher** [comment]
:tada: @Emerick94 you are now a repository collaborator. :balloon:

**Comment by eszini** [comment]
hello ... see if I can close this request ....

**Comment by eszini** [comment]
ok. that´s it.
