### ISSUE TITLE
Please add me - Shanghai, China

### ISSUE THREAD

**Issue by ElaCai** [githubschool/open-enrollment-classes-introduction-to-github#6054]
Hello! :wave: Please add me as a collaborator to this repo. 
Adding Shanghai to the map.
Your Latitude: 31.0456
Your Longitude: 121.3997

**Comment by githubteacher** [comment]
:tada: @ElaCai you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
