### ISSUE TITLE
Howdy!

### ISSUE THREAD

**Issue by Oystermudd** [githubschool/open-enrollment-classes-introduction-to-github#6109]
Hello! :wave: May I be added to this collaboration? Please and thank you!

**Comment by githubteacher** [comment]
:tada: @Oystermudd you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
