### ISSUE TITLE
Please add me -Gujarat,India

### ISSUE THREAD

**Issue by karanchapaneri** [githubschool/open-enrollment-classes-introduction-to-github#6118]
Hello! :wave: Please add me as a collaborator to this repo. 
Adding Gujarat to map

Hello everyone, this issue is to track addition of Gujarat to the map
Lat: 20.389315
Long: 72.910620

**Comment by githubteacher** [comment]
:tada: @karanchapaneri you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
