### ISSUE TITLE
Please Add Me - Mumbai, India

### ISSUE THREAD

**Issue by RishuGoenka** [githubschool/open-enrollment-classes-introduction-to-github#6129]
Hello! :wave: Please add me as a collaborator to this repo. 

-Latitude : 19.0760° N
-Longitude : 72.8777° E

**Comment by githubteacher** [comment]
:tada: @RishuGoenka you are now a repository collaborator. :balloon:

**Comment by RishuGoenka** [comment]
Thank you so much.
Can you help me how i can earn GitHub stickers

**Comment by brianamarie** [comment]
Hi @RishuGoenka! You can buy stickers here: https://github.myshopify.com/
