### ISSUE TITLE
Please add me - Maroua, extreme nord

### ISSUE THREAD

**Issue by Hicks7** [githubschool/open-enrollment-classes-introduction-to-github#6130]
#adding maroua to the map

Hi everyone ! This issue is to track addiction of maroua to the map, which can be found at : 

-Latitude = 10.604644
-longitude = 14.354539

**Comment by githubteacher** [comment]
:tada: @Hicks7 you are now a repository collaborator. :balloon:

**Comment by Hicks7** [comment]
thank's...
