### ISSUE TITLE
Please Add San Francisco State University

### ISSUE THREAD

**Issue by thou000** [githubschool/open-enrollment-classes-introduction-to-github#6138]
## Adding San Francisco State University to the map

-Longitude 37.721178
-Latitude -122.476962

**Comment by githubteacher** [comment]
:tada: @thou000 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
