### ISSUE TITLE
Newbie to Git

### ISSUE THREAD

**Issue by aljoyner4** [githubschool/open-enrollment-classes-introduction-to-github#6146]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @aljoyner4 you are now a repository collaborator. :balloon:

**Comment by aljoyner4** [comment]
Great! now I feel like I'm learning something...

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by aljoyner4** [comment]
I'm still not sure whether I'm doing this correctly....
