### ISSUE TITLE
Please add me -- Scottsdale, AZ

### ISSUE THREAD

**Issue by lhsuandy** [githubschool/open-enrollment-classes-introduction-to-github#6177]
Hello! :wave: Please add me as a collaborator to this repo. 
## adding Scottsdale to map

- lat: 33.494170
- long: -111.926052

**Comment by githubteacher** [comment]
:tada: @lhsuandy you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
