### ISSUE TITLE
Please add me - Bangalore, INDIA

### ISSUE THREAD

**Issue by tarunvikash** [githubschool/open-enrollment-classes-introduction-to-github#6185]
##Adding INDIA to the map
Hello! :wave: Please add me as a collaborator to this repo. 

Latitude: 12.9716° N
Longitude: 77.5946° E

**Comment by githubteacher** [comment]
:tada: @tarunvikash you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
