### ISSUE TITLE
Please add me - Pinto, Spain

### ISSUE THREAD

**Issue by alvarocaceresm** [githubschool/open-enrollment-classes-introduction-to-github#6201]
## Adding Pinto to the map

Hi everyone! This issue is to track the addition of Pinto to the map, which can be found at:

- Longitude: -3.697551
- Latitude: 40.239511

**Comment by githubteacher** [comment]
:tada: @alvarocaceresm you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
