### ISSUE TITLE
New learner!

### ISSUE THREAD

**Issue by williamblakemusic** [githubschool/open-enrollment-classes-introduction-to-github#6222]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @williamblakemusic you are now a repository collaborator. :balloon:

**Comment by williamblakemusic** [comment]
what all do i need to download?

**Comment by williamblakemusic** [comment]
i have github and many ide programs, as well as a handful of different program language resources.

**Comment by williamblakemusic** [comment]
Or how about the best resource for absolute beginners in programming? there seems to be so much to learn

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by williamblakemusic** [comment]
oh no! well, if you must, i will return to continue this monday evening
 Thank you!
