### ISSUE TITLE
oh herro

### ISSUE THREAD

**Issue by android-dep** [githubschool/open-enrollment-classes-introduction-to-github#6224]
Hello! :wave: Please add me as a collaborator to this repo. 
![tvp62ew5lowu](https://cloud.githubusercontent.com/assets/1931139/25778516/f4c4acba-32cd-11e7-93e4-977d4a7bfd61.gif)
starting to get a hang of this github thing

**Comment by githubteacher** [comment]
:tada: @android-dep you are now a repository collaborator. :balloon:

**Comment by android-dep** [comment]
![fk-yeah](https://cloud.githubusercontent.com/assets/1931139/25778540/df1f7e0c-32ce-11e7-9dbc-7d24a62b9744.jpg)

oh yea, feelin like a boss, thank you

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
