### ISSUE TITLE
add me please atlanta ga

### ISSUE THREAD

**Issue by johikingeorgoa** [githubschool/open-enrollment-classes-introduction-to-github#6225]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @johikingeorgoa you are now a repository collaborator. :balloon:

**Comment by johikingeorgoa** [comment]
[hello-world-5e6685d1b48c372169f62de5df201f626772077e.zip](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/files/981358/hello-world-5e6685d1b48c372169f62de5df201f626772077e.zip)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
