### ISSUE TITLE
Hello, Please Add Me, Mannheim, Germany

### ISSUE THREAD

**Issue by eilarraza** [githubschool/open-enrollment-classes-introduction-to-github#6234]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @eilarraza you are now a repository collaborator. :balloon:

**Comment by eilarraza** [comment]
## Adding Mannheim to the map

Hallo!! This issue is to track the addition of Mannheim to the map, which can be found at:

- Longitude:  8.476
- Latitude: 49.483
