### ISSUE TITLE
zzbarra Recommenattions

### ISSUE THREAD

**Issue by zzbarrao** [githubschool/open-enrollment-classes-introduction-to-github#6570]
zzbarrao will add recommendations for the things to do in **Chicago**.
- [ ] create a branch
- [ ] add the file
- [ ] commit
- [ ] pull request
- [ ] request a review
- [ ] make more changes
- [ ] get approval
- [ ] merge the pull request

**Comment by githubteacher** [comment]
:tada: @zzbarrao you are now a repository collaborator. :balloon:
