### ISSUE TITLE
Toronto

### ISSUE THREAD

**Issue by jenniferw3000** [githubschool/open-enrollment-classes-introduction-to-github#665]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by jenniferw3000** [comment]
Test close issue.

**Comment by MTaylr** [comment]
I will be adding my name to the city.

**Comment by rsparkman** [comment]
Add. Maybe.
