### ISSUE TITLE
Add Me PLease!

### ISSUE THREAD

**Issue by NinaMarie6462** [githubschool/open-enrollment-classes-introduction-to-github#6656]
Hello! :wave: Please add me as a collaborator to this repo. 
I Need to add my pin at San Antonio Texas. but i dont know where to find the longitude and latitude. @githubteacher

**Comment by githubteacher** [comment]
:tada: @NinaMarie6462 you are now a repository collaborator. :balloon:

**Comment by NinaMarie6462** [comment]
Just Learning

**Comment by Abhishekkorgaonkar92** [comment]
@NinaMarie6462 Link>>https://mynasadata.larc.nasa.gov/latitudelongitude-finder/
search for your location here,will get you latitude & longitude.
