### ISSUE TITLE
Madrid

### ISSUE THREAD

**Issue by nitben** [githubschool/open-enrollment-classes-introduction-to-github#667]
## Adding Madrid to the map

Hi everyone! This issue is to track the addition of Madrid to the map, which can be found at:
- Longitude: 3°41′31″O
- Latitude: 40°25′08″N

**Comment by iordic** [comment]
I'm going to add my name to the same city.

**Comment by albagcs** [comment]
Hi, I'm going to add my name too to Madrid city

**Comment by veotos** [comment]
## Hello here
Let's call Madrid my home too...
