### ISSUE TITLE
Please add me- Bhubaneswar, IL

### ISSUE THREAD

**Issue by krishvalentine06** [githubschool/open-enrollment-classes-introduction-to-github#6763]
##adding Bhubaneswar to the map

Hi, everyone! This issue to track the addition of Bhubaneswar to the map, which can be found at:

-Longitude: 85.8245
-Latitude: 20.2961

**Comment by githubteacher** [comment]
:tada: @krishvalentine06 you are now a repository collaborator. :balloon:

**Comment by krishvalentine06** [comment]
Thank You
