### ISSUE TITLE
open-enrollment-introduction-to-github

### ISSUE THREAD

**Issue by RuslanPartsey** [githubschool/open-enrollment-classes-introduction-to-github#6764]
Hello! :wave: Please add me as a collaborator to this report.

**Comment by githubteacher** [comment]
:tada: @RuslanPartsey you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
