### ISSUE TITLE
Please add me - Aracaju, SE

### ISSUE THREAD

**Issue by NGeraldo** [githubschool/open-enrollment-classes-introduction-to-github#6771]
Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude:  -37.0730823
- Latitude: -10.9472468

**Comment by githubteacher** [comment]
:tada: @NGeraldo you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
