### ISSUE TITLE
Add me again

### ISSUE THREAD

**Issue by forkush** [githubschool/open-enrollment-classes-introduction-to-github#6802]
Hello! :wave: Please add me as a collaborator to this repo. 

Adding Henderson, Nevada to the map

- Lattitude: 36.0395° N
- Longitude: 114.9817° W

**Comment by githubteacher** [comment]
:tada: @forkush you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
