### ISSUE TITLE
Please add me as a collaborator

### ISSUE THREAD

**Issue by kawayikp** [githubschool/open-enrollment-classes-introduction-to-github#6812]
## Add San Jose to the map

Longitude: 37.3382
Lantitude: 121.8863

**Comment by githubteacher** [comment]
:tada: @kawayikp you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
