### ISSUE TITLE
Please add me 

### ISSUE THREAD

**Issue by arvinscorpio** [githubschool/open-enrollment-classes-introduction-to-github#6815]
Hello! :wave: Please add me as a collaborator to this repo. 

Latitude: 13.0827° N,
Longitude:  80.2707° E

**Comment by githubteacher** [comment]
:tada: @arvinscorpio you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
