### ISSUE TITLE
Adding Chandigarh, India to map

### ISSUE THREAD

**Issue by nvnkumar93** [githubschool/open-enrollment-classes-introduction-to-github#683]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of Chandigarh to the map, which can be found at:
- Longitude: <76.779418
- Latitude: 30.733315

**Comment by syed156** [comment]
The syntax for longitude is incorrect. Please re-check your coordinates.

**Comment by nvnkumar93** [comment]
Hi everyone! This issue is to track the addition of Chandigarh to the map, which can be found at:

Longitude: 76.779418
Latitude: 30.733315

**Comment by sdsahib** [comment]
hello everyone adding my name to the city ...LOL

**Comment by vak101995** [comment]
Hello everyone, adding my name as well

**Comment by the-cybersapien** [comment]
Hi everyone!
Joining here from Chandigarh!
