### ISSUE TITLE
Add me as collab! :D

### ISSUE THREAD

**Issue by arm-morin** [githubschool/open-enrollment-classes-introduction-to-github#6830]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @arm-morin you are now a repository collaborator. :balloon:

**Comment by vinayakkgarg** [comment]
Hello! Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
