### ISSUE TITLE
Puede alguien agregarme

### ISSUE THREAD

**Issue by Marin56** [githubschool/open-enrollment-classes-introduction-to-github#6863]
Hello! :wave: Please add me as a collaborator to this repo. 
Hola!  por favor puede alguien agregarme como colaborador.

**Comment by githubteacher** [comment]
:tada: @Marin56 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
