### ISSUE TITLE
Please add me - Hong Kong

### ISSUE THREAD

**Issue by zhihhuang** [githubschool/open-enrollment-classes-introduction-to-github#6881]
Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude: 114.200563
- Latitude: 22.289337

**Comment by githubteacher** [comment]
:tada: @zhihhuang you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
