### ISSUE TITLE
Please add me - Houston, TX

### ISSUE THREAD

**Issue by AAP777** [githubschool/open-enrollment-classes-introduction-to-github#6898]
Hello! :wave: Please add me as a collaborator to this repo. 

Longitude: -95.6627
Latitude: 29.8327

**Comment by githubteacher** [comment]
:tada: @AAP777 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
