### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kesavakadiyala** [githubschool/open-enrollment-classes-introduction-to-github#6919]
I didn't understand how to create html file in this demo.plzz hlp me @githubteacher
https://services.github.com/on-demand/github-desktop/make-changes-github-desktop

**Comment by crichID** [comment]
@kesavakadiyala you will create the file on your local machine using any program you would like to use. We recommend you use a text editor like atom. You simply create the file and then save it in your repository with the name index.html. Does that help?

**Comment by kesavakadiyala** [comment]
yaa,I did it.
I did same as in demo,But I coulnt get this step.
In new pull request we should select compare master as add-index-pages but it is not showing there.
https://services.github.com/on-demand/github-desktop/pull-request-github-desktop
![screenshot 707](https://cloud.githubusercontent.com/assets/28837244/26517150/46c307cc-42b0-11e7-998d-7ed3d51a73f0.png)
![screenshot 708](https://cloud.githubusercontent.com/assets/28837244/26517152/47cc8440-42b0-11e7-806f-ea782104d631.png)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
