### ISSUE TITLE
Please add me - Paderborn

### ISSUE THREAD

**Issue by DASILVP** [githubschool/open-enrollment-classes-introduction-to-github#6920]
## Adding Paderborn to the map

Hi everyone! This issue is to track the addition of <Paderborn> to the map, which can be found at:

- Longitude: <8.7575093>
- Latitude: <51.7189205>

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
