### ISSUE TITLE
Please add me-FuZhou,JL

### ISSUE THREAD

**Issue by LianJilu** [githubschool/open-enrollment-classes-introduction-to-github#6930]
## Add FuZhou to the map

Hi everyone ! This issue is to track the addition of <your-city> to the map, which can be found at 

-Longitude: 29.210
-Latitude: 109.481

**Comment by Abkhenaten** [comment]
Please add me Abkhenaten 
-Longitude: 26.7153 
-Latitude: 80.0534

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
