### ISSUE TITLE
Abkhenaten

### ISSUE THREAD

**Issue by Abkhenaten** [githubschool/open-enrollment-classes-introduction-to-github#6931]
Hello! :wave: Please add me as a collaborator to this repo. 
longitude: 26.7153
latitude: 80.0534

**Comment by githubteacher** [comment]
:tada: @Abkhenaten you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
