### ISSUE TITLE
Please add me - Grand Rapids, MI

### ISSUE THREAD

**Issue by pmishra9** [githubschool/open-enrollment-classes-introduction-to-github#6934]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @pmishra9 you are now a repository collaborator. :balloon:

**Comment by pmishra9** [comment]
That was fast. Thank you!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
