### ISSUE TITLE
Please add me - Cork, Ireland

### ISSUE THREAD

**Issue by octaviodegodoy** [githubschool/open-enrollment-classes-introduction-to-github#6948]
Please add me to the map

Latitude:51.893
Longitude:-8.481

**Comment by githubteacher** [comment]
:tada: @octaviodegodoy you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
