### ISSUE TITLE
Please add db in Tampa, FL

### ISSUE THREAD

**Issue by dbgitter** [githubschool/open-enrollment-classes-introduction-to-github#6981]
Hello! :wave: Please add me as a collaborator to this repo. 
Tampa location
- Longitude: -82.5
- Latitude: 27.5

**Comment by githubteacher** [comment]
:tada: @dbgitter you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
