### ISSUE TITLE
Add me - somewhere on earth

### ISSUE THREAD

**Issue by ybudiadi** [githubschool/open-enrollment-classes-introduction-to-github#7001]
Hello! Adding somewhere on earth to the map. 

- Longitude: -30.000
- Latitude: 25.000

**Comment by githubteacher** [comment]
:tada: @ybudiadi you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
