### ISSUE TITLE
Adding Amstelveen, The Netherlands, to the map

### ISSUE THREAD

**Issue by dbwarner** [githubschool/open-enrollment-classes-introduction-to-github#702]
## Adding Amstelveen, The Netherlands to the map

Hi everyone! This issue is to track the addition of Amstelveen to the map, which can be found at:
- Longitude: 4.870087
- Latitude: 52.311421

**Comment by PMcComas15** [comment]
Nice work! 👍

**Comment by PaulHoving** [comment]
I changed longitude for lattitude. :-(
Now let's try to change that without the training instructions! :-)

**Comment by PaulHoving** [comment]
Nope I did it right. Strange that my pin is not showing up yet.
