### ISSUE TITLE
Create Front Page

### ISSUE THREAD

**Issue by dronetur** [githubschool/open-enrollment-classes-introduction-to-github#7037]
Need to add an issue (sample) from a Project Workflow.

This is that issue.

**Comment by dronetur** [comment]
# Issue
## Need to learn how to write in Markdown
@dronetur
This issue is not *well* documented, so 
>it is in the weeds

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
