### ISSUE TITLE
Adding Johannesburg, South Africa to the map

### ISSUE THREAD

**Issue by JarrydLong** [githubschool/open-enrollment-classes-introduction-to-github#704]
## Adding Johannesburg, South Africa to the map

Hi everyone! This issue is to track the addition of Johannesburg, South Africa to the map, which can be found at:
- Longitude: -26.204103
- Latitude: 28.047305

**Comment by Kgotso-Koete** [comment]
Hey Folks

I am just reopening the issue regarding the addition of Johannesburg to the map.

Regards
