### ISSUE TITLE
Please add me - Chigao, IL

### ISSUE THREAD

**Issue by youngsam-byun** [githubschool/open-enrollment-classes-introduction-to-github#7048]
Hello! :wave: Please add me as a collaborator to this repo. 

- Longitude : -53.4223
- Latitude : 25.999

**Comment by githubteacher** [comment]
:tada: @youngsam-byun you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
