### ISSUE TITLE
Respectfully Request Collaboration and Learning

### ISSUE THREAD

**Issue by flutterbird** [githubschool/open-enrollment-classes-introduction-to-github#7088]
Hello! :wave: Please add me as a collaborator to this repo. 

Gratefully,

~ Chrissi

**Comment by githubteacher** [comment]
:tada: @flutterbird you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
