### ISSUE TITLE
Add Dublin, Ireland to the map

### ISSUE THREAD

**Issue by canuckjacq** [githubschool/open-enrollment-classes-introduction-to-github#71]
## Adding Dublin, Ireland to the map

Hi everyone! This issue is to track the addition of Dublin, Ireland to the map, which can be found at:

- Longitude: -6.260310
- Latitude: 53.349805

**Comment by micmaher** [comment]
Adding my name to the pin for Dublin

**Comment by micmaher** [comment]
Fixes #653

**Comment by lucabeee** [comment]
Adding Name and pin to the Map

**Comment by ynnekkram** [comment]
Great to see this on the map.
