### ISSUE TITLE
Please add me - Earthling on Earth

### ISSUE THREAD

**Issue by CrustyBarnacle** [githubschool/open-enrollment-classes-introduction-to-github#7140]
Hello! :wave: Please add me as a collaborator to this repo.
[Located on Earth](https://en.wikipedia.org/wiki/Earth%27s_location_in_the_Universe)

**Comment by githubteacher** [comment]
:tada: @CrustyBarnacle you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
