### ISSUE TITLE
getting ready to add me..

### ISSUE THREAD

**Issue by PavlosKodikos** [githubschool/open-enrollment-classes-introduction-to-github#7199]
Hello! :wave: I'm getting ready to add myself on as a collaborator to this repo. But will rewriting this sentence screw things up (will the addition of an apostrophe, commas, parentheses, and a question mark, plus a a longer description matter?)

**Comment by githubteacher** [comment]
:tada: @PavlosKodikos you are now a repository collaborator. :balloon:

**Comment by PavlosKodikos** [comment]
I'm not seeing myself on the map, but I had a successful merge. 
Is there a time lapse between the merge of the code and the appearance on the map of the user?
