### ISSUE TITLE
ghg

### ISSUE THREAD

**Issue by prasanthJi** [githubschool/open-enrollment-classes-introduction-to-github#7225]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by hectorsector** [comment]
@prasanthJi apologies about the delay! Please make sure you've clicked on the verification email you received. Once you've done that, you can accept the [invitation I just sent](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations).

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
