### ISSUE TITLE
Please add me. Thanks.

### ISSUE THREAD

**Issue by suzannelock** [githubschool/open-enrollment-classes-introduction-to-github#7320]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @suzannelock you are now a repository collaborator. :balloon:

**Comment by shooter001** [comment]
please add me as a collaborator

**Comment by hectorsector** [comment]
@shooter001 please open up a new issue and you'll be granted collaborator access

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
