### ISSUE TITLE
Please add me - Nagpur

### ISSUE THREAD

**Issue by kaushikvyas** [githubschool/open-enrollment-classes-introduction-to-github#7324]
Latitude : 21.1458
Longitude : 79.0882

**Comment by githubteacher** [comment]
:tada: @kaushikvyas you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
