### ISSUE TITLE
Please add me - Cleveland, OH

### ISSUE THREAD

**Issue by shbenner** [githubschool/open-enrollment-classes-introduction-to-github#7325]
## Adding Clevelnad to the map

Hi everyone! This issue is to  track the addition of Cleveland to the map, which can be found at:

-Longitude 25
-Latitude 25

**Comment by githubteacher** [comment]
:tada: @shbenner you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
