### ISSUE TITLE
Add me!

### ISSUE THREAD

**Issue by realWallawalla** [githubschool/open-enrollment-classes-introduction-to-github#7340]
Hello! :wave: Please add me as a collaborator to this repo. I dont know what im doing.

**Comment by githubteacher** [comment]
:tada: @realWallawalla you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
