### ISSUE TITLE
Add me to the map (for test purposes, as in training video instructions)

### ISSUE THREAD

**Issue by Chris-from-PA** [githubschool/open-enrollment-classes-introduction-to-github#7354]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Chris-from-PA you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
