### ISSUE TITLE
Please add me - Bangalore, India

### ISSUE THREAD

**Issue by amritenduroy** [githubschool/open-enrollment-classes-introduction-to-github#7384]
## Adding Bangalore, India to the map

Latitude: 12.9716° N
Longitude: 77.5946° E

**Comment by githubteacher** [comment]
:tada: @amritenduroy you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
