### ISSUE TITLE
Add Btech

### ISSUE THREAD

**Issue by btechtutor** [githubschool/open-enrollment-classes-introduction-to-github#7389]
Hi, add me to your repo ! thnx

**Comment by githubteacher** [comment]
:tada: @btechtutor you are now a repository collaborator. :balloon:

**Comment by btechtutor** [comment]
thnx tute

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
