### ISSUE TITLE
Adding Amsterdam

### ISSUE THREAD

**Issue by BastiaanHendriks** [githubschool/open-enrollment-classes-introduction-to-github#74]
## Adding Amsterdam to the map

Hi everyone! This issue is to track the addition of Amsterdam to the map, which can be found at:

[52.370216, 4.895168]

**Comment by crichID** [comment]
Hi @BastiaanHendriks we hope you will get a chance to create a pull request and finish adding your pin to the map. Please let us know if there is anything we can do to help!

**Comment by idmarjr** [comment]
I updated @BastiaanHendriks commentary to fix inverted latitude/longitude values from Amsterdam. 😄 

I am from Brazil but I moved to Amsterdam 6 months ago.
I'm gonna add myself to the map as well.

**Comment by cfidelaire** [comment]
Reopening issue to add my name to the pin for Amsterdam because Amsterdam rocks ;)

**Comment by SavasAli** [comment]
Hi, would like to add my name!
