### ISSUE TITLE
Please add me - Rio de Janeiro, RJ (Brazil)

### ISSUE THREAD

**Issue by socorsan** [githubschool/open-enrollment-classes-introduction-to-github#7400]
# # Adding Rio de Janeiro to the map

Hi everyone! This is an issue to track the addition of Rio de Janeiro to the map, which can be found at:

- Longitude: -43.270688
- Latitude: -22.896650

**Comment by githubteacher** [comment]
:tada: @socorsan you are now a repository collaborator. :balloon:
