### ISSUE TITLE
Please Add me - Karnataka,IN

### ISSUE THREAD

**Issue by mirmohsinahmed** [githubschool/open-enrollment-classes-introduction-to-github#7408]
## Adding my city to the map

- Longitude:  77.594563

- Latitude: 12.971599

**Comment by githubteacher** [comment]
:tada: @mirmohsinahmed you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
