### ISSUE TITLE
Please add me - Boston, MA

### ISSUE THREAD

**Issue by vballworld** [githubschool/open-enrollment-classes-introduction-to-github#7409]
## Adding Boston to map

Hi all -- this is to track addition of Boston to map at:

-Longitude: 0
-Latitude: 0

**Comment by githubteacher** [comment]
:tada: @vballworld you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
