### ISSUE TITLE
Add Amsterdam to map

### ISSUE THREAD

**Issue by Chals80** [githubschool/open-enrollment-classes-introduction-to-github#7410]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Amsterdam to the map 👍 

This issue is to track the addition of Amsterdam to the map which can be found at:
- Latitude: 52.3702157
- Longitute: 4.8951679

**Comment by githubteacher** [comment]
:tada: @Chals80 you are now a repository collaborator. :balloon:

**Comment by imperishableavinash** [comment]
add me please

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
