### ISSUE TITLE
ADD ME!!!!

### ISSUE THREAD

**Issue by Jamarc218** [githubschool/open-enrollment-classes-introduction-to-github#7417]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Jamarc218 you are now a repository collaborator. :balloon:

**Comment by Jamarc218** [comment]
@cwizzle hi

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
