### ISSUE TITLE
Pick

### ISSUE THREAD

**Issue by Sweetnesss1** [githubschool/open-enrollment-classes-introduction-to-github#7466]
![img_0068](https://user-images.githubusercontent.com/28884920/27080261-c855cffe-5043-11e7-993a-90e16bb10ba0.JPG)
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Sweetnesss1 you are now a repository collaborator. :balloon:

**Comment by cor138** [comment]
I like to help.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by cor138** [comment]
Hoi Teacher,

 

What do you suppose I should do. I want to know github. So I try again.

 

Kind regards,

 

Met vriendelijke groet

Cor van Dijk

T. 0416 363444  06 13247810

 

 

Van: GitHub Teacher [mailto:notifications@github.com] 
Verzonden: woensdag 21 juni 2017 09:02
Aan: githubschool/open-enrollment-classes-introduction-to-github
CC: cor138; Comment
Onderwerp: Re: [githubschool/open-enrollment-classes-introduction-to-github] Pick (#7466)

 

It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
