### ISSUE TITLE
Indianapolis

### ISSUE THREAD

**Issue by auflint** [githubschool/open-enrollment-classes-introduction-to-github#749]
## Adding Indianapolis to the map

Hi everyone! This issue is to track the addition of Indianapolis (also Naptown, if you will) to the map, which can be found at:

- Longitude: -86.158068
- Latitude: 39.768403

![](http://66.media.tumblr.com/15c90c62424990b267182cc3d0f9e442/tumblr_mjbj4mS9DR1s5wdewo1_500.png)

**Comment by brainfreezepenguin** [comment]
I'll be adding my name to this city

**Comment by courtneyrecker** [comment]
I am adding my name to this city!
