### ISSUE TITLE
please add me - Toronto, ON, Canada

### ISSUE THREAD

**Issue by pierreyin** [githubschool/open-enrollment-classes-introduction-to-github#7498]
## Adding Toronto to the map

Hi everyone! This issue is to track the addition of adding Toronto to the map, which can be found at 
- longitude: -79.383184
- latitude: 43.653226

**Comment by githubteacher** [comment]
:tada: @pierreyin you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
