### ISSUE TITLE
Add Orlando pin to map

### ISSUE THREAD

**Issue by Nathan801** [githubschool/open-enrollment-classes-introduction-to-github#754]
## Adding <Orlando> to the map for @githubteacher 

Hi everyone! I have added my pin to <Orlando> the map for @githubteacher which can be found at:

- Longitude: <-81.379236>
- Latitude: <28.538335>

**Comment by aarvizu** [comment]
Hello Every. I'm adding my pin to the map
**Latitude:** 28.580237

**Longitude:** -81.203904
