### ISSUE TITLE
cli test

### ISSUE THREAD

**Issue by dony-li** [githubschool/open-enrollment-classes-introduction-to-github#7550]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @dony-li you are now a repository collaborator. :balloon:

**Comment by dony-li** [comment]
## adding something
import java.io.*;

Private Class test() {
}

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
