### ISSUE TITLE
it seems 

### ISSUE THREAD

**Issue by geekgurl-muraco** [githubschool/open-enrollment-classes-introduction-to-github#7564]
that we don't do anything here except follow the instructions meaninglessly as instructed from this page

https://services.github.com/on-demand/intro-to-github/edit-files-on-github

but I am learning nothing... for example I don't understand what the _pins were about and why we were to suss out our location https://services.github.com/on-demand/intro-to-github/work-on-github

I don't understand why we were instructed to do this:

Congratulations! You have created your Pull Request. Now it is time to put your collaborator hat on and go help others!

    Now that your pull request has been created, go back to the pull request list to find an open pull request – other than your own.
    Provide feedback :loudspeaker: and motivation :tada:.

provide feedback so the instructor closes the pull requests? huh? what? I'm at a loss to understand how this is instructional - the "show me how" doesn't.

@githubteacher

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
