### ISSUE TITLE
Fort Collins, CO

### ISSUE THREAD

**Issue by oriandaleigh** [githubschool/open-enrollment-classes-introduction-to-github#76]
## Adding Fort Collins to the map

Hi everyone! This issue is to track the addition of Fort Collins to the map, which can be found at:

- Longitude: -105.084423
- Latitude: 40.585260

**Comment by Andrewepstein** [comment]
What does this mean? Closed #76?

**Comment by mvaloris** [comment]
I will be adding my name to the pin for this city!

**Comment by edowdy** [comment]
I will be adding my name to the pin for this city as well.
