### ISSUE TITLE
Please add me - Kongsberg, Norway

### ISSUE THREAD

**Issue by etonw** [githubschool/open-enrollment-classes-introduction-to-github#7677]
## Adding Kongsberg to the map

Hi everyone! This issue is to track the addition of Kongsberg to the map, which can be found at:

-Longitude: 59.663845
-Latitude: 9.637179
@githubteacher 
![capture](https://user-images.githubusercontent.com/13966710/27278344-606da108-54e1-11e7-8172-b8ef094bf6ae.JPG)

**Comment by githubteacher** [comment]
:tada: @etonw you are now a repository collaborator. :balloon:
