### ISSUE TITLE
Add me!

### ISSUE THREAD

**Issue by makubexD** [githubschool/open-enrollment-classes-introduction-to-github#7687]
## Adding Lima to the map
Hello! :wave: Please add me as a collaborator to this repo. 
- Longitude: -77.0282400
- Latitude: -12.0431800

**Comment by githubteacher** [comment]
:tada: @makubexD you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
