### ISSUE TITLE
Please add me - 's Hertogenbosch, NL

### ISSUE THREAD

**Issue by dvankempen** [githubschool/open-enrollment-classes-introduction-to-github#7724]
Hello! :wave: Please add me as a collaborator to this repo. 

This issue is to track the addition of 's Hertogenbosch to the map, which can be found at: 
- Longitude 51.712513
- Latitude: 5.338483

**Comment by githubteacher** [comment]
:tada: @dvankempen you are now a repository collaborator. :balloon:
