### ISSUE TITLE
Imad

### ISSUE THREAD

**Issue by Imad-Khchifati** [githubschool/open-enrollment-classes-introduction-to-github#7729]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Imad-Khchifati you are now a repository collaborator. :balloon:

**Comment by Imad-Khchifati** [comment]
Hey!

**Comment by AlexHartveld** [comment]
Hey Imad!

**Comment by Imad-Khchifati** [comment]
@githubteacher 
closes #7729
