### ISSUE TITLE
Add me plz

### ISSUE THREAD

**Issue by qsmhn** [githubschool/open-enrollment-classes-introduction-to-github#7732]
Please add Me

_Sent from my ZTE A2017G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by githubteacher** [comment]
:tada: @qsmhn you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
