### ISSUE TITLE
Mak

### ISSUE THREAD

**Issue by mak3434** [githubschool/open-enrollment-classes-introduction-to-github#7734]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @mak3434 you are now a repository collaborator. :balloon:

**Comment by mak3434** [comment]
Hi :)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
