### ISSUE TITLE
Please add me - Philadelphia, PA

### ISSUE THREAD

**Issue by jimmymixer** [githubschool/open-enrollment-classes-introduction-to-github#7761]
## Adding Philadelphia to the map

Longitude: -75.314898
Latitude: 40.147138

**Comment by githubteacher** [comment]
:tada: @jimmymixer you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
