### ISSUE TITLE
Still learning how this works, add me- Chicago,IL

### ISSUE THREAD

**Issue by Sprieto117** [githubschool/open-enrollment-classes-introduction-to-github#7765]
Hello! :wave: Please add me as a collaborator 
P.s i have no idea what i'm doing. HELP ME??!!!!?!?!

**Comment by githubteacher** [comment]
:tada: @Sprieto117 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
