### ISSUE TITLE
Please add me - GuangDong,Dongguan

### ISSUE THREAD

**Issue by Williamzhangtw** [githubschool/open-enrollment-classes-introduction-to-github#7798]
## Adding GuangDong to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

- Longitude: 22.903536
- Latitude: 113.870261

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
