### ISSUE TITLE
Class Goals

### ISSUE THREAD

**Issue by montyhossain** [githubschool/open-enrollment-classes-introduction-to-github#78]
## Adding <san-francisco> to the map

Hi everyone! This issue is to track the addition of <san-francisco> to the map, which can be found at:

- Longitude: <-122.419416>
- Latitude: <37.774929>

**Comment by crichID** [comment]
@montyhossain :wave: thank you for starting our on-demand class! We notice your issue is still open - can we help you with finishing the activity? We would :heart: to add your pin to the map!
