### ISSUE TITLE
Eman/Chicago

### ISSUE THREAD

**Issue by smiah4433** [githubschool/open-enrollment-classes-introduction-to-github#7810]
Hello! :wave: Please add me as a collaborator to this repo. 
You're in Chicago, Illinois, United States
Your Latitude: 41.8825
Your Longitude: -87.6441

**Comment by githubteacher** [comment]
:tada: @smiah4433 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
