### ISSUE TITLE
Adding Irvine, CA to the map

### ISSUE THREAD

**Issue by lynnlangit** [githubschool/open-enrollment-classes-introduction-to-github#782]
## Adding Irvine, CA to the map

Hi everyone! This issue is to track the addition of Irvine, CA to the map, which can be found at:
- Longitude: 33.6839° N
- Latitude: 117.7947° W

**Comment by ericaz98** [comment]
Hi, I'll be adding my name to the same city.

**Comment by blinebau** [comment]
Adding my name to Irvine as well.
