### ISSUE TITLE
HTML & CSS

### ISSUE THREAD

**Issue by HyperKlaus** [githubschool/open-enrollment-classes-introduction-to-github#7857]
Need help with this code format? 

	<!DOCTYPE html>
	
	<html>
	
	<head>
	<title> Hey There! Practice Page</title>
	</head>
	<body>
	<h1> Chicago Volleyball Championship</h1>
	<p>Volleyball Championship are fun and add so much fun in your life</p>
	<p>You can have some fun in the sun baby girl!</p>
	
	<p>Take time for <b>Yourself</b> to relax</p>
	
	<p>It will let you <i>think</i> and allow time to take a breather</p>
	
	<p>Hydrate with H<sub>2</sub>0 so that you will not faint</p>
	
	<p>This will be the 5<sup>th</sup> annual Championship</p>
	
	<p>Never<br> GIVE UP</p>
	
	<h1>P</h1>
	<h2>L</h2>
	<h3>A</h3>
	<h4>Y</h4>
	<h5>E</h5>
	<h6>R</h6>
	
	<ul>
	<li>SunScreen</li>
	</ul>
	
	<ol>
	<li>Prevent Sun burn </li>
	</ol>
	
	<blockquote>Stay in the shade</blockquote>
	
	<pre>Too Hot, Ain't It?</pre>
	
	
	
	<p>ESPN Volleyball <a href="http://www.espn.com/espnw/sport/ncaa-volleyball/"> ESPN: Volleyball</a></p>
	
	<a href="http://news.fiu.edu/wp-content/uploads/volleyball-espn.jpg">
	<img src="http://news.fiu.edu/wp-content/uploads/volleyball-espn.jpg"></a>
	
	<h3> Hey!</h3>
	<ul>
	<li><a href="https://finance.yahoo.com/quote/kf?ltr=1"></a></li>
	</ul>
	
	<h3> Hello!</h3>
	<ol>
	<li><a href="https://finance.yahoo.com/quote/kf?ltr=1"></a></li>
	</ol>
	
	</body>
	</html>

**Comment by HyperKlaus** [comment]
First, what is the purpose of this HTML format? 
Second, is it Professional or Personal? 
Lastly, where is the CSS?

**Comment by hollenberry** [comment]
Hey @HyperKlaus ! Unfortunately, I can't help you out with this code, here. This repository is specifically to help users with the Introduction to GitHub On Demand course. 👍
