### ISSUE TITLE
Please add me - Singapore

### ISSUE THREAD

**Issue by someshrathi02** [githubschool/open-enrollment-classes-introduction-to-github#7866]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Singapore to the map

Hi Everyone ! This issue is to track the additional of Singapore to the map ,which can be found at

- Longtitude: 1.3521° N, 

- Latitude: 103.8198° E

**Comment by githubteacher** [comment]
:tada: @someshrathi02 you are now a repository collaborator. :balloon:

**Comment by someshrathi02** [comment]
@githubteacher looking forward to learn git and use it effectively.

**Comment by someshrathi02** [comment]
@githubteacher , how can i add add new test file to above project ? i want to contribute ?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
