### ISSUE TITLE
Please Add Me - Bangalore, India

### ISSUE THREAD

**Issue by polisettyManoj** [githubschool/open-enrollment-classes-introduction-to-github#7867]
Hello!  Please add me as a collaborator to this repo.
Adding Bangalore to the map

Hi Everyone ! This issue is to track the additional of Bangalore,India to the map ,which can be found at

    Longitude: 12.9716° N,

    Latitude: 77.5946° E

**Comment by githubteacher** [comment]
:tada: @polisettyManoj you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
