### ISSUE TITLE
Please Add Me - Selangor, Malaysia

### ISSUE THREAD

**Issue by AnnabelleSP** [githubschool/open-enrollment-classes-introduction-to-github#7873]
##Adding Selangor to the map
Hello! :wave: Please add me as a collaborator to this repo. 

-Latitude: 3.0738
-Longitude: 101.5183

**Comment by githubteacher** [comment]
:tada: @AnnabelleSP you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
