### ISSUE TITLE
Please Add Me - Austin, TX

### ISSUE THREAD

**Issue by casspencer** [githubschool/open-enrollment-classes-introduction-to-github#7896]
Hello! :wave: Please add me as a collaborator to this repo. 

# Adding Austin to the map

- Longitude: W -97.755996
- Latitude: N 30.307182

**Comment by githubteacher** [comment]
:tada: @casspencer you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
