### ISSUE TITLE
Add Sunnyvale CA

### ISSUE THREAD

**Issue by regnerjr** [githubschool/open-enrollment-classes-introduction-to-github#790]
## Adding Sunnyvale CA to the map

Hi everyone! This issue is to track the addition of Sunnyvale to the map, which can be found at:
- Longitude: -122.035747
- Latitude: 37.382076

**Comment by DJBlock19** [comment]
I will be opening this ticket and adding my name to Sunnyvale

**Comment by DJBlock19** [comment]
Reopening to add my pin to Sunnyvale
