### ISSUE TITLE
please add me-khammam

### ISSUE THREAD

**Issue by anilkumarsoma** [githubschool/open-enrollment-classes-introduction-to-github#7917]
hi every one
- longitude:80.322363
- latitude:17.594134

**Comment by githubteacher** [comment]
:tada: @anilkumarsoma you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
