### ISSUE TITLE
Hi, I'm new to GitHub

### ISSUE THREAD

**Issue by cldumont** [githubschool/open-enrollment-classes-introduction-to-github#7918]
Hello! I'm learning how to get involved with the GitHub community

**Comment by githubteacher** [comment]
:tada: @cldumont you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
