### ISSUE TITLE
Adding Cd. Juarez, Chihuahua to the Map

### ISSUE THREAD

**Issue by anaisFTW** [githubschool/open-enrollment-classes-introduction-to-github#792]
## Adding Cd. Juarez to the map

Hi everyone! This issue is to track the addition of Cd. Juarez to the map, which can be found at:

- Longitude: -106.424548
- Latitude: 31.690364

**Comment by YamiG** [comment]
Yo también voy a poner mi pin en el mapa! :smile:

**Comment by PaulinaIsamar** [comment]
Mi pin en el mapa :+1:

**Comment by ctdavid** [comment]
voy agregar mi PIN en el Maps

**Comment by luissantillan** [comment]
voy a poner mi pin en el mapa  :+1:

**Comment by DianaJaramillo** [comment]
Voy agregar mi pin el Maps :octocat:

**Comment by JAntonioA** [comment]
Voy agregar mi pin

**Comment by KarinaContreras** [comment]
Voy a poner mi pin en el mapa :+1:

**Comment by ErnestoValdez** [comment]
voy agregar mi pin en el mapa

**Comment by JocelyneRF** [comment]
Voy a agregar mi pin en el mapa

**Comment by EberLara** [comment]
Voy a poner mi ping en el mapa :v:

**Comment by AldandelysCamacho** [comment]
Lista para empezar

**Comment by erickhp12** [comment]
ya llegue, que dice? como andan

**Comment by luissantillan** [comment]
:

**Comment by AndreaLira** [comment]
Lista yo tambien n.n

**Comment by cristhianhrb** [comment]
Listo

**Comment by landeros1294** [comment]
Voy a proceder a poner el pin in da map :dart:

**Comment by AlexisYescas** [comment]
Yo también pondré el pin en el mapa.

**Comment by valeromaria** [comment]
Por fin.....

**Comment by JAntonioA** [comment]
listo
