### ISSUE TITLE
Please add me- Bhopal,India

### ISSUE THREAD

**Issue by yash9724** [githubschool/open-enrollment-classes-introduction-to-github#7950]
Hello! :wave: Please add me as a collaborator to this repo. 
Bhopal , India
Latitude- 23°15′N 
Longitude-77°25′E

**Comment by githubteacher** [comment]
:tada: @yash9724 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
