### ISSUE TITLE
gi

### ISSUE THREAD

**Issue by vgmxy-03** [githubschool/open-enrollment-classes-introduction-to-github#7952]
Hello! :wave: Please add me as a collaborator to this repo. 
India

**Comment by githubteacher** [comment]
:tada: @vgmxy-03 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
