### ISSUE TITLE
Please add this- Bhopal,M.P, India

### ISSUE THREAD

**Issue by BhanuD19** [githubschool/open-enrollment-classes-introduction-to-github#7960]
##Adding bhopal to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:

-Longitude:23.2599° N
-Latitude: 77.4126° E

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
