### ISSUE TITLE
Please add me - Tucson, AZ

### ISSUE THREAD

**Issue by dedenning** [githubschool/open-enrollment-classes-introduction-to-github#7963]
Hello! :wave: Please add me as a collaborator to this repo. 

Lattitude:  32.0873920

Longitude:  -110.8043930

**Comment by githubteacher** [comment]
:tada: @dedenning you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
