### ISSUE TITLE
New test issue for new user

### ISSUE THREAD

**Issue by mclarkdsllc** [githubschool/open-enrollment-classes-introduction-to-github#7979]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by mclarkdsllc** [comment]
Thanks for your help.

**Comment by githubteacher** [comment]
:tada: @mclarkdsllc you are now a repository collaborator. :balloon:

**Comment by mclarkdsllc** [comment]
Try leaving a new comment. Learning about notifications.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
