### ISSUE TITLE
Please Add me Sydney Australia

### ISSUE THREAD

**Issue by hiralmakwana30** [githubschool/open-enrollment-classes-introduction-to-github#7999]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Sydney to the map
Latitude -33.883109
Longitude 151.130194

**Comment by githubteacher** [comment]
:tada: @hiralmakwana30 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
