### ISSUE TITLE
urpalshuIssue

### ISSUE THREAD

**Issue by SushmaRamakrishna** [githubschool/open-enrollment-classes-introduction-to-github#8009]
Hello! :wave: Please add me Chicago, IL collaborator to this repo. 

Longitude: -53.4223
Latitude 25.999

**Comment by githubteacher** [comment]
:tada: @SushmaRamakrishna you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
