### ISSUE TITLE
first_one

### ISSUE THREAD

**Issue by davestammer** [githubschool/open-enrollment-classes-introduction-to-github#8012]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @davestammer you are now a repository collaborator. :balloon:

**Comment by davestammer** [comment]
Don't know what I'm doing.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
