### ISSUE TITLE
Add Me!! Taipei, Taiwan

### ISSUE THREAD

**Issue by Seanen** [githubschool/open-enrollment-classes-introduction-to-github#8022]
Hello!
👋
Please add me as a collaborator to this repo.
Latitude:  25° 03'N 
Longitude:  121° 30'W

**Comment by githubteacher** [comment]
:tada: @Seanen you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
