### ISSUE TITLE
Please add me -- Shanghai,China

### ISSUE THREAD

**Issue by sdot08** [githubschool/open-enrollment-classes-introduction-to-github#8033]
##adding Shanghai to the map
Hi, everyone, this issue is to track the addition of Shanghai to the map.

**Comment by githubteacher** [comment]
:tada: @sdot08 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
