### ISSUE TITLE
please add me 

### ISSUE THREAD

**Issue by aatoshem** [githubschool/open-enrollment-classes-introduction-to-github#8048]
Please add me as a collaborator ! [www.atoshem.xyz](url)

**Comment by githubteacher** [comment]
:tada: @aatoshem you are now a repository collaborator. :balloon:

**Comment by aatoshem** [comment]
yes

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
