### ISSUE TITLE
Please add me - Levin New Zealand

### ISSUE THREAD

**Issue by Deroles** [githubschool/open-enrollment-classes-introduction-to-github#8061]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Deroles you are now a repository collaborator. :balloon:

**Comment by Deroles** [comment]
Can't get the training videos to run - so can't work out next steps at all. Says to mention @githubteacher but no idea where to mentions this???

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
