### ISSUE TITLE
poi

### ISSUE THREAD

**Issue by OsvaldoDiaz** [githubschool/open-enrollment-classes-introduction-to-github#8074]
Hello! :wave: Please add me as a collaborator to this repo. 
hello

**Comment by githubteacher** [comment]
:tada: @OsvaldoDiaz you are now a repository collaborator. :balloon:

**Comment by OsvaldoDiaz** [comment]
ahora que gato pulpo?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
