### ISSUE TITLE
Please add me-Guadalajara, Jalisco

### ISSUE THREAD

**Issue by zublime** [githubschool/open-enrollment-classes-introduction-to-github#8075]
## Adding Guadalajara to the map

Hi everyone i am adding this to the map.

**Comment by githubteacher** [comment]
:tada: @zublime you are now a repository collaborator. :balloon:

**Comment by zublime** [comment]
Yes,

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
