### ISSUE TITLE
Please add me - Guadalajara, Mex.

### ISSUE THREAD

**Issue by lumartch** [githubschool/open-enrollment-classes-introduction-to-github#8083]
## Adding-Guadalajara to the map
Hi everyone! This issue is to track addition of Guadalajara to the map, which can found at: 

-Longitude: -103.0583
-Latitude: 20.5

**Comment by githubteacher** [comment]
:tada: @lumartch you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
