### ISSUE TITLE
This is my issue ... MAC 2017

### ISSUE THREAD

**Issue by angel1967** [githubschool/open-enrollment-classes-introduction-to-github#8084]
Hello! :wave: Please add me as a collaborator to this repo. 

ok

**Comment by githubteacher** [comment]
:tada: @angel1967 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
