### ISSUE TITLE
Adding Berlin

### ISSUE THREAD

**Issue by jules-p** [githubschool/open-enrollment-classes-introduction-to-github#81]
## Adding Berlin to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: 13.404954
- Latitude: 52.520007

**Comment by Klickspektrum** [comment]
Hi,
I´m adding my name to the pin for Berlin.

**Comment by tommiii** [comment]
i will be adding my name to the pin for berlin, too
