### ISSUE TITLE
Class Goals

### ISSUE THREAD

**Issue by DanielaWM** [githubschool/open-enrollment-classes-introduction-to-github#8117]
## My Goals 

 
![tumblr_o3ks365xtl1s5qhggo7_1280](https://user-images.githubusercontent.com/29473795/27716614-3b5bc59e-5d05-11e7-8d54-018e3a2d393a.jpg)
-[ ] Learn how to use issues on Github

@githubstudent what other goals should add here ?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
