### ISSUE TITLE
Pls add me! - Barletta, Italy

### ISSUE THREAD

**Issue by PeppeVash** [githubschool/open-enrollment-classes-introduction-to-github#8159]
## Adding Barletta to the map

Hello! :wave: Please add me as a collaborator to this repo. 

Latitude: 41.3142900
Longitude: 16.2816500

**Comment by githubteacher** [comment]
:tada: @PeppeVash you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
