### ISSUE TITLE
Please add me - Hannover, NDS

### ISSUE THREAD

**Issue by 42tg** [githubschool/open-enrollment-classes-introduction-to-github#8161]
## Adding Hannover to the Map

Hello! 👋 Please add me as a collaborator to this repo.

Latitude: 52.3795836
Longitude: 9.6213892

**Comment by githubteacher** [comment]
:tada: @42tg you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
