### ISSUE TITLE
Please add me - Tahlequah, OK

### ISSUE THREAD

**Issue by brooksienoodlesoup** [githubschool/open-enrollment-classes-introduction-to-github#8173]
## Adding Tahlequah to the map

Hi everyone!  This issue is to track the addition of Tahlequah to the map, which can be found at:

- Longitude: -94.969956
- Latitude: 35.915370

**Comment by githubteacher** [comment]
:tada: @brooksienoodlesoup you are now a repository collaborator. :balloon:
