### ISSUE TITLE
Add me - Hasama, JPN

### ISSUE THREAD

**Issue by koichiwb** [githubschool/open-enrollment-classes-introduction-to-github#8199]
## Adding Hasama to the map

- Longitude 140.0196° E
- Latitude 35.7057° N

**Comment by githubteacher** [comment]
:tada: @koichiwb you are now a repository collaborator. :balloon:

**Comment by koichiwb** [comment]
Thank you !

**Comment by tradfabio** [comment]
@koichiwb **Nice Job!** 🎉
