### ISSUE TITLE
Please add me-Bulandshahr

### ISSUE THREAD

**Issue by aliole05** [githubschool/open-enrollment-classes-introduction-to-github#8206]
Hello! :wave: Please add me as a collaborator to this repo. 
longitude:77.849829
latitude:28.406963

**Comment by githubteacher** [comment]
:tada: @aliole05 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
