### ISSUE TITLE
Experiencing problems when joining 

### ISSUE THREAD

**Issue by RyanMartin226** [githubschool/open-enrollment-classes-introduction-to-github#8235]
Hello! :wave: Please add me as a collaborator to this repo. 
When I attempt to join I am met with both the checks failing (https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/8231) and I am unsure of how to fix the problem

**Comment by brianamarie** [comment]
Hi @RyanMartin226! It looks like you got the checks all sorted. I'm going to close this issue now. Please let me know if you have any  more questions. 😄
