### ISSUE TITLE
Please add me - Hyderabad,India

### ISSUE THREAD

**Issue by ashwinash333** [githubschool/open-enrollment-classes-introduction-to-github#8276]
Hello! :wave: Please add me as a collaborator to this repo. 
##Adding Hyderabad to map
-Longitude: 78.5324269
-Latitude: 17.3909761

**Comment by githubteacher** [comment]
:tada: @ashwinash333 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
