### ISSUE TITLE
Please add me - Frankfurt am Main, Germany

### ISSUE THREAD

**Issue by tx1985** [githubschool/open-enrollment-classes-introduction-to-github#8293]
## Adding Frankfurt am Main to the map 

Hi everyone! This issue is to track the addition of Frankfurt am Main to the map, which can be found at:

- Longitude: 50,1155
- Latitude:  8,68417

**Comment by githubteacher** [comment]
:tada: @tx1985 you are now a repository collaborator. :balloon:
