### ISSUE TITLE
Adding yes another person from Canada!!!!

### ISSUE THREAD

**Issue by JayemN** [githubschool/open-enrollment-classes-introduction-to-github#8303]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @JayemN you are now a repository collaborator. :balloon:

**Comment by JayemN** [comment]
Was supposed to open issue 927...my bad

**Comment by JayemN** [comment]
Cause I don't know what I am doing

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
