### ISSUE TITLE
Please add me - Hamilton, Ontario

### ISSUE THREAD

**Issue by christinebaird** [githubschool/open-enrollment-classes-introduction-to-github#8305]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @christinebaird you are now a repository collaborator. :balloon:

**Comment by christinebaird** [comment]
Thank you.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
