### ISSUE TITLE
Please Add Me - Taiwan, NTHU

### ISSUE THREAD

**Issue by tso0159753** [githubschool/open-enrollment-classes-introduction-to-github#8309]
Hello! :wave: Please add me as a collaborator to this repo. 

I am in Shilin Nightmarket now.

- Longitude: 25.088414
- Latitude: 121.526436

**Comment by githubteacher** [comment]
:tada: @tso0159753 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
