### ISSUE TITLE
Pin did not show up

### ISSUE THREAD

**Issue by psford1** [githubschool/open-enrollment-classes-introduction-to-github#8347]
@githubteacher My pin is not displaying on the map.

Successful merge from commit 3e34a90

**Comment by brianamarie** [comment]
Hi @psford1! Sometimes it takes a few minutes to show up, and also sometimes you have to do a 'hard refresh' or clear your cache.

Wait five minutes, open it in a different browser or clear your cache, and try again. Let me know if that doesn't work. 😄

**Comment by psford1** [comment]
Of course as soon as I put the issue in it showed up :man_facepalming: 
Thanks!
