### ISSUE TITLE
Please add me - Cumming, GA

### ISSUE THREAD

**Issue by meierjp57** [githubschool/open-enrollment-classes-introduction-to-github#8348]
Hello! :wave: Please add me as a collaborator to this repo. 

Cumming, Georgia USA
Longitude: 34.2073N
Latitude:    84.1402W

**Comment by githubteacher** [comment]
:tada: @meierjp57 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
