### ISSUE TITLE
please add me :Colombo,Sri Lanka

### ISSUE THREAD

**Issue by xQuadrox** [githubschool/open-enrollment-classes-introduction-to-github#8361]
Hello! :wave: Please add me as a collaborator to this repo. 
yo

**Comment by githubteacher** [comment]
:tada: @xQuadrox you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
