### ISSUE TITLE
Please add me -Dalian,China

### ISSUE THREAD

**Issue by correctresponse** [githubschool/open-enrollment-classes-introduction-to-github#8365]
Hello! :wave: Please add me as a collaborator to this repo. 
## Add Dalian to the map
-Longtitude: 121.62
-Latitude:      38.92

**Comment by githubteacher** [comment]
:tada: @correctresponse you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
