### ISSUE TITLE
please add me, H.T.Shieh

### ISSUE THREAD

**Issue by brennenhuang** [githubschool/open-enrollment-classes-introduction-to-github#8392]
## Hello! :wave: Please add me as a collaborator to this repo.

-longitude:120.224879
-latitude :22.996918

**Comment by githubteacher** [comment]
:tada: @brennenhuang you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
