### ISSUE TITLE
New first timer

### ISSUE THREAD

**Issue by clough11** [githubschool/open-enrollment-classes-introduction-to-github#8395]
Hello! :wave: @githubteacher Please add me as a collaborator to this repo. Getting started is slow. 😜

**Comment by githubteacher** [comment]
:tada: @clough11 you are now a repository collaborator. :balloon:

**Comment by clough11** [comment]
Woohoo!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
