### ISSUE TITLE
Please add me :)

### ISSUE THREAD

**Issue by cscov** [githubschool/open-enrollment-classes-introduction-to-github#8397]
Hello! :wave: Please add me as a collaborator to this repo. I'm excited to dive into GitHub for the first time!

**Comment by githubteacher** [comment]
:tada: @cscov you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
