### ISSUE TITLE
dheeraj gakkhr

### ISSUE THREAD

**Issue by dheeraj15** [githubschool/open-enrollment-classes-introduction-to-github#8406]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @dheeraj15 you are now a repository collaborator. :balloon:

**Comment by dheeraj15** [comment]
thank u

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
