### ISSUE TITLE
Add me I guess :) woooooooooooo!!!, what happened to the longitude, latitude?

### ISSUE THREAD

**Issue by gooshtie** [githubschool/open-enrollment-classes-introduction-to-github#8421]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @gooshtie you are now a repository collaborator. :balloon:

**Comment by gooshtie** [comment]
Awesome!! :)

**Comment by gooshtie** [comment]
Thanks for the response! I'm just starting to get into programming and have been doing codecademy's free courses. I've done HTML & CSS, JS, React I, and am almost done with React II. I was wondering if you had any suggestions that would help me to be able to get an entry level job programming or to help build my knowledge?  Trying to get have a career and stop struggling with dead end jobs :)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
