### ISSUE TITLE
Yes, Quite.

### ISSUE THREAD

**Issue by Theoval23Blumenkraft** [githubschool/open-enrollment-classes-introduction-to-github#8472]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Theoval23Blumenkraft you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
