### ISSUE TITLE
Newbie on the loose in virtual training facilities 

### ISSUE THREAD

**Issue by rinyheuvelman** [githubschool/open-enrollment-classes-introduction-to-github#8478]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @rinyheuvelman you are now a repository collaborator. :balloon:

**Comment by rinyheuvelman** [comment]
Hope to become familiar with GitHub basics. 
Doing is experience build

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
