### ISSUE TITLE
lansing

### ISSUE THREAD

**Issue by lyndraco** [githubschool/open-enrollment-classes-introduction-to-github#863]
## Adding Lansing to the map

Hi everyone! This issue is to track the addition of Lansing to the map, which can be found at:

- Longitude: <-84.555535>
- Latitude: <42.732535>

**Comment by eriukristene** [comment]
I'll be adding my name to this! Thanks for the coordinates!

**Comment by holcom73** [comment]
I am also adding my name to this.  Thanks for the info.

**Comment by KorysKennedy** [comment]
Adding my name. Thank you!

**Comment by smahnke** [comment]
Adding mine, as well! Thanks
