### ISSUE TITLE
Add me!!! - Greenfield, OH

### ISSUE THREAD

**Issue by hdaugherty** [githubschool/open-enrollment-classes-introduction-to-github#8634]
Hello! :wave: Please add me as a collaborator to this repo. 
+---
+githubHandle:hdaugherty
+latitude:39.355
+longitude: -83.386
+---

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
