### ISSUE TITLE
Please add me - Saint Ignace, MI

### ISSUE THREAD

**Issue by MatthewBenjaminLittle** [githubschool/open-enrollment-classes-introduction-to-github#8651]
## Adding Saint Ignace to the map

Hello! :wave: Please add me as a collaborator to this repo. 

This issue is to track the addition of Saint Igance, MI to the map, which can be found at:

- Latitude:  45.8756
- Longitude:  -84.7323

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
