### ISSUE TITLE
Please Add me - Richmond, VA

### ISSUE THREAD

**Issue by Ragmad01** [githubschool/open-enrollment-classes-introduction-to-github#8733]
Hello! :wave: Please add me as a collaborator to this repo. 

From Raghav, Richmond VA

**Comment by Ragmad01** [comment]
Thanks Mr. Robot, I'm glad to be here

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
