### ISSUE TITLE
n-th attempt

### ISSUE THREAD

**Issue by erik-vorik** [githubschool/open-enrollment-classes-introduction-to-github#8748]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by erik-vorik** [comment]
Hi there, if there is a hu-man assistant to tell me what I did wrong would be really great. I did try so many times to do this from scratch but to no avail

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
