### ISSUE TITLE
East Lansing

### ISSUE THREAD

**Issue by ramyasat** [githubschool/open-enrollment-classes-introduction-to-github#877]
## Adding East Lansing to the map

Hi everyone! This issue is to track the addition of East Lansing to the map, which can be found at:

- Longitude: -84.483865
- Latitude: 42.736979

**Comment by johndoyleraso** [comment]
I'll add my name to this pin!

**Comment by fricanol** [comment]
I'll be adding my name too

**Comment by 6edavila** [comment]
I'll be adding my name too

**Comment by muell228** [comment]
I'll be adding my name!
