### ISSUE TITLE
Please add me - Caterham, Surrey

### ISSUE THREAD

**Issue by Greenroomgithubuser** [githubschool/open-enrollment-classes-introduction-to-github#8774]
## Adding Caterham to the map

Hi Everyone.  This is to track the addition of Caterham to the map which can be found at:

Lat: 51.289
Long: -0.087

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
