### ISSUE TITLE
Los Mochis

### ISSUE THREAD

**Issue by elcone** [githubschool/open-enrollment-classes-introduction-to-github#882]
## Adding Los Mochis to the map

Hi everyone! This issue is to track the addition of Los Mochis to the map, which can be found at:

- Longitude: -108.985882
- Latitude: 25.790466

**Comment by cesargafer** [comment]
Sup??

Divertido vdd!?

Checa esta app me ayudo un monton

http://pcottle.github.io/learnGitBranching/

See ya!!

**Comment by elcone** [comment]
perfecto @cesargafer gracias!
