### ISSUE TITLE
Please add me - Montevideo, Uruguay

### ISSUE THREAD

**Issue by Breathof** [githubschool/open-enrollment-classes-introduction-to-github#9069]
## Adding Montevideo to the map
Hi everyone! This issue is to track the addition to Montevideo to the map, which can be found at:

-  Longitude: -56.17713
-  Latitude: -34.898885

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
