### ISSUE TITLE
please add me

### ISSUE THREAD

**Issue by satyapati0** [githubschool/open-enrollment-classes-introduction-to-github#9243]
Hello! :wave: Please add me as a collaborator to this repo. 

This issue is to track the addition of Bhubaneswar to the map, which can be found
 at longitude - 20.2961N
latitude - 85.8245E

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
