### ISSUE TITLE
plz add me - BBSR, Odisha

### ISSUE THREAD

**Issue by satyapati0** [githubschool/open-enrollment-classes-introduction-to-github#9271]
Hello! :wave: Please add me as a collaborator to this repo. 
Adding bhubaneswar to the map
- Longitude: 20.2961
- Latitude: 85.8245

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
