### ISSUE TITLE
Greetings everyone!

### ISSUE THREAD

**Issue by ImKenner** [githubschool/open-enrollment-classes-introduction-to-github#9273]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by zjutszl** [comment]
Hello! Please add me as a collaborator here.

**Comment by ImKenner** [comment]
@zjutszl You have to create your own issue for the bot to add you as a collaborator

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
