### ISSUE TITLE
Adding Los Angeles to the map

### ISSUE THREAD

**Issue by jiyoungparkbello** [githubschool/open-enrollment-classes-introduction-to-github#93]
## Adding Los Angeles to the map

Hi everyone! This issue is to track the addition of Los Angeles to the map, which can be found at:
- Longitude: -118.2437
- Latitude: 34.0522

**Comment by francis-m** [comment]
Hi, I'll be adding my name to the Los Angeles pin.

**Comment by moranjay** [comment]
Also adding Los Angeles.

**Comment by geofftrojans** [comment]
I'm adding Los Angeles as well!
