### ISSUE TITLE
Please add me - Bronx, NY

### ISSUE THREAD

**Issue by morsegates** [githubschool/open-enrollment-classes-introduction-to-github#9326]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by cor138** [comment]
Still learning. Welcome.

**Comment by cor138** [comment]
Looks now like a chatbox. But it is a repository. My personal goal is to become a Joomla developer. But first know github.

**Comment by morsegates** [comment]
fascinating stuff and Thank you.

**Comment by morsegates** [comment]
I keep running into github lately so leaning into curiosity.

**Comment by cor138** [comment]
Me too. Used subversion 6 years ago. Should be the same. But still looking around.
