### ISSUE TITLE
Please add Venetia to the Map

### ISSUE THREAD

**Issue by dnodev** [githubschool/open-enrollment-classes-introduction-to-github#9352]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by dnodev** [comment]
Please add my location to the map
Latitude: 40.2523° N
Longitude: 0.0028° W

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
