### ISSUE TITLE
ZPeterson2-Orlando

### ISSUE THREAD

**Issue by ZPeterson2** [githubschool/open-enrollment-classes-introduction-to-github#937]
## Adding <Orlando> to the map

Hi everyone! This issue is to track the addition of <Orlando> to the map, which can be found at:
---

- Longitude: 28.551418

- Latitude: -81.414753 

---

**Comment by GoogleFox** [comment]
Hello! I would like to be added to this city also! :)

**Comment by Javier-of-the-Rich-Port** [comment]
Reopening this issue to add myself to it.
