### ISSUE TITLE
Add me pleeeaaazzzz

### ISSUE THREAD

**Issue by BillBridge** [githubschool/open-enrollment-classes-introduction-to-github#9392]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by cor138** [comment]
I'll skip the 100 messages and try to learn moer. Thank you for all advise.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
