### ISSUE TITLE
San Francisco

### ISSUE THREAD

**Issue by alrightjones** [githubschool/open-enrollment-classes-introduction-to-github#940]
## Adding San Francisco to the map

Hi everyone! This issue is to track the addition of San Francisco to the map, which can be found at:
- Longitude: 37.775928
- Latitude:  -122.444024

**Comment by sainathdevi** [comment]
i am adding

**Comment by smauvais** [comment]
open

**Comment by githubstudent** [comment]
❤️ ! I'll be adding my pin as well.
