### ISSUE TITLE
Please add me - Arnold, MO

### ISSUE THREAD

**Issue by BitPrisoner** [githubschool/open-enrollment-classes-introduction-to-github#9436]
## Adding Arnold to the map

Hi everyone! This issue is to track the addition of Arnold to the map, which can be found at 

- Longitude: -90.3693
- Latitude:  38.4260

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
