### ISSUE TITLE
Please add me

### ISSUE THREAD

**Issue by Johnny1500** [githubschool/open-enrollment-classes-introduction-to-github#9439]
## Adding Ekaterinburg to the map

Hello! :wave: Please add me as a collaborator to this repo. 
Ekaterinburg
- Longitude: 60.6125
- Latitude: 56.8575

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
