### ISSUE TITLE
affrae - add me as a collaborator

### ISSUE THREAD

**Issue by affrae** [githubschool/open-enrollment-classes-introduction-to-github#9481]
Hello! :wave: **_Please_** add me as a collaborator to this repo. 

# This is a heading
###### I don't think this one works

- This is item one
- This is item two

1. One
2. Two

- Three

1. Four

- [x] eggs
- [x] milk

[GitHub](http://github.com)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
