### ISSUE TITLE
Res4MeAdmin I'm here and ready to go

### ISSUE THREAD

**Issue by Res4MeAdmin** [githubschool/open-enrollment-classes-introduction-to-github#9483]
Hello! :wave: **Please** add me as a collaborator to this repo. 

- [ ] list 1
- [ ] list 2
- [ ] list 3

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
