### ISSUE TITLE
asiandub1 - add me as a collaborator

### ISSUE THREAD

**Issue by asiandub1** [githubschool/open-enrollment-classes-introduction-to-github#9484]
Hello! :wave: **_Please_** add me as a collaborator to this repo. 

# This is a heading.
### This is a heading.

GitHub[ ]  (http://github.com)

- This is item one.
- This is item two.

Checkbox
-[ ]eggs
-[ ]milk

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
