### ISSUE TITLE
Adding Beijing to the map

### ISSUE THREAD

**Issue by logindave** [githubschool/open-enrollment-classes-introduction-to-github#95]
## Adding Beijing to the map

Hi everyone! This issue is to track the addition of Beijing to the map, which can be found at:
- Longitude: 116.407395
- Latitude: 39.904211

**Comment by logindave** [comment]
balabala @githubteacher

**Comment by MaciasGD** [comment]
yeh ;)

**Comment by Johnny2014** [comment]
hey :)

**Comment by JacksonL1** [comment]
glad to see Beijing at Github@githubteacher

**Comment by CS14491** [comment]
agree

**Comment by Xdudu** [comment]
aha~
