### ISSUE TITLE
Adding Jakarta to the Map

### ISSUE THREAD

**Issue by sekti92** [githubschool/open-enrollment-classes-introduction-to-github#96]
## Adding Jakarta to the map

Hi everyone! This issue is to track the addition of Jakarta to the map, which can be found at:

- Longitude: 106.845599
- Latitude: -6.208763

![git](https://cloud.githubusercontent.com/assets/14885417/17150763/e4411058-539a-11e6-8aed-a39c774f1f7c.jpeg)

**Comment by FajriFadli** [comment]
Hi everyone! This issue is to track the addition of Jakarta to the map, which can be found at:

    

- Longitude: 106.845599
    

- Latitude: -6.2087634
