### ISSUE TITLE
dartanian

### ISSUE THREAD

**Issue by Dartanianbagby1** [githubschool/open-enrollment-classes-introduction-to-github#9628]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by Dartanianbagby1** [comment]
hi

**Comment by Dartanianbagby1** [comment]
![face](https://user-images.githubusercontent.com/24845898/29645111-1faa3046-8830-11e7-8421-67c9e971dbba.png)

**Comment by Dartanianbagby1** [comment]
hi

**Comment by beardofedu** [comment]
@Dartanianbagby1 :wave: teacherbot is currently down for an update, so I manually added you to the course. An email should have been sent to the email you signed up with.
