### ISSUE TITLE
Please add me!

### ISSUE THREAD

**Issue by myou11** [githubschool/open-enrollment-classes-introduction-to-github#9630]
##Adding Fort Collins, CO to the map

-Longitude: 40.585260
-Latitude: -105.084423

**Comment by myou11** [comment]
I don't think I am a contributor yet because I still can't create a branch in this repo

**Comment by beardofedu** [comment]
@myou11 I just manually added you as a collaborator, you should have an email with an invitation link. Sorry about the delay.
