### ISSUE TITLE
PLEASE add me =)

### ISSUE THREAD

**Issue by LEVONTUTUNJIAN** [githubschool/open-enrollment-classes-introduction-to-github#9652]
Hello! :wave: Please add me as a collaborator to this repo.

**Comment by beardofedu** [comment]
@LEVONTUTUNJIAN 👋 teacherbot is currently down for an update, so I manually added you to the course. An email should have been sent to the email you signed up with.

**Comment by LEVONTUTUNJIAN** [comment]
Thank u teacher!
