### ISSUE TITLE
Please add me - Sioux Falls, SD

### ISSUE THREAD

**Issue by bryanbronson** [githubschool/open-enrollment-classes-introduction-to-github#9666]
Hello! :wave: Please add me as a collaborator to this repo. 
## Adding Sioux Falls to the map

Hi everyone! This issue is to track the addition of Sioux Falls to the map, which can be found at:

-Longitude: -96.731998
-Latitude: 43.538335

**Comment by beardofedu** [comment]
@bryanbronson 👋 teacherbot is currently down for an update, so I manually added you to the course. An email should have been sent to the email you signed up with.
