### ISSUE TITLE
Please add me - Zamora, Michoacan, Mexico

### ISSUE THREAD

**Issue by web2bruno** [githubschool/open-enrollment-classes-introduction-to-github#9667]
## Adding Zamora to the map

Hi everyone! This issue is to track the addition of Zamora, Michoacan to the map, which can be found at:

- Longitude: -102.2863801
- Latitude: 19.980644

**Comment by beardofedu** [comment]
@web2bruno 👋 teacherbot is currently down for an update, so I manually added you to the course. An email should have been sent to the email you signed up with.
