### ISSUE TITLE
Please add me - Floating Adrift

### ISSUE THREAD

**Issue by confidentidiot** [githubschool/open-enrollment-classes-introduction-to-github#9669]
## Adding me to the map

Hi everyone!  This issue is to track the addition of my raft to the map which can be found at:

- Longitude: 97.91015625
- Latitude: -25.48295118

**Comment by beardofedu** [comment]
@confidentidiot 👋 teacherbot is currently down for an update, so I manually added you to the course. An email should have been sent to the email you signed up with.

**Comment by confidentidiot** [comment]
Thanks!
