### ISSUE TITLE
Please add me Hong Kong SAR

### ISSUE THREAD

**Issue by Funkey-monkey** [githubschool/open-enrollment-classes-introduction-to-github#9674]
## Adding Hong Kong to the map

Hi Everyone, this issue is to track the addition of Hong Kong SAR to the map, which can be found at:

-Longitute: 22.2832130
-Latitude: 114.1520760

**Comment by anlexN** [comment]
please use your github username.

**Comment by beardofedu** [comment]
@Funkey-monkey 👋 it appears teacherbot took a nap over the weekend, so I manually added you to the course. An email should have been sent to the email you signed up with.
