### ISSUE TITLE
Unable to create a branch

### ISSUE THREAD

**Issue by rajansingh96** [githubschool/open-enrollment-classes-introduction-to-github#9705]
Hi @githubteacher,

I am not able to create a new branch. Thank you!

**Comment by baoman09** [comment]
same here :dagger:

**Comment by antonpalinau** [comment]
same)

**Comment by hectorsector** [comment]
Apologies, @rajansingh96 @baoman09 @antonpalinau. Teacherbot has been feeling under the weather 🤒.

I've sent you an [invitation](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations) to the repo which you should now be able to accept.

**Comment by carsontyler** [comment]
Can you send me an invitation as well? I can't create a branch

**Comment by hectorsector** [comment]
Just did, @carsontyler!

**Comment by hectorsector** [comment]
@billyjoebaron we appreciate your willingness to help, but please allow the author of issues and PRs to close or merge their own.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
