### ISSUE TITLE
marioSantos97

### ISSUE THREAD

**Issue by marioSantos97** [githubschool/open-enrollment-classes-introduction-to-github#9844]
Hello! @githubteacher im trying to do my first pull request in here, which should be automatically merged right? but i cant merge it because the checks keep failing, can i get some help please?

**Comment by marioSantos97** [comment]
I have solved the problem already, close #9844

**Comment by hectorsector** [comment]
Glad you got it solved @marioSantos97! Closing this issue out.

**Comment by marioSantos97** [comment]
im trying, how can i do that @hectorsector ?
