### ISSUE TITLE
Please add me - The Woodlands, TX

### ISSUE THREAD

**Issue by AgentMonocle** [githubschool/open-enrollment-classes-introduction-to-github#9853]
## Adding The Woodlands to the map.

Hi everyone!  This issue is to track the addition of The Woodlands, TX to the map, which can be found at:

- Longitude: -95.461794
-Latitude: 30.172813

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
