### ISSUE TITLE
Please add me - Gentbrugge BE

### ISSUE THREAD

**Issue by louagej** [githubschool/open-enrollment-classes-introduction-to-github#9869]
##Adding Gentbrugge to the map

Hi everyone! This issue is to track the addition of Gentbrugge to the map, which can be found at:

- Longitude: 51.0408183
- Latitude:  3.7565897

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
