### ISSUE TITLE
Please add me - Shaanxi, Xi'an

### ISSUE THREAD

**Issue by qq75997972** [githubschool/open-enrollment-classes-introduction-to-github#9872]
Hello! :wave: Please add me as a collaborator to this repo. 

##Adding Xi'an to the map 

-Longitude:108.93
-Latitude:34.27

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
