### ISSUE TITLE
Please add me - Pleasant Hill, CA

### ISSUE THREAD

**Issue by BobRak** [githubschool/open-enrollment-classes-introduction-to-github#9873]
## Adding Pleasant Hill to the map

This issue is to track the addition of Pleasant Hill, which can be found at:

- Longitude: 37.951052
- Latitude: -122.096254

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
