### ISSUE TITLE
Please add me - Lima, Pe

### ISSUE THREAD

**Issue by GlisseLisbeth** [githubschool/open-enrollment-classes-introduction-to-github#9875]
## Adding Lima to the map

Hi everyone! This issue is to track the addition of Lima-Peru, which can be found at:

Longitude: -77.042754
Latitude: -12.046373

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
