### ISSUE TITLE
Please add me! Mililani, Hawaii

### ISSUE THREAD

**Issue by jdigiacinto** [githubschool/open-enrollment-classes-introduction-to-github#9884]
Hello! :wave: Please add me as a collaborator to this repo. 
##Adding Mililani to the map!

-Longitude: -158.016357
-Latitude: 21.447990

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
