### ISSUE TITLE
Please add me - Davis, CA

### ISSUE THREAD

**Issue by LindaKatehi** [githubschool/open-enrollment-classes-introduction-to-github#9932]
## Adding Davis to the map

Hi everyone! This issue is to track the addition of Davis, CA on the map

- Longitude: -121.7405
- Latitude: 38.5449

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
