### ISSUE TITLE
did many commits all of which failed

### ISSUE THREAD

**Issue by veeraragav** [githubschool/open-enrollment-classes-introduction-to-github#9942]
@githubteacher 

Initially i added the json file to .pins folder and later i found that was wrong and again I tried to add the file veeraragav.json to _pin. Both shows x mark. How can i delete my first commit?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
