### ISSUE TITLE
Please, add me Kyiv, UA

### ISSUE THREAD

**Issue by BohdanGivbygo** [githubschool/open-enrollment-classes-introduction-to-github#9996]
Hello! :wave: Please add me as a collaborator to this repo. 
#Adding Kyiv to the map
- Longitude: 50.456874
- Latitude: 30.507249

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
